<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Global Spatial Autocorrelation 1 | Hands-On Spatial Data Science with R</title>
  <meta name="description" content="Chapter 10 Global Spatial Autocorrelation 1 | Hands-On Spatial Data Science with R" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Global Spatial Autocorrelation 1 | Hands-On Spatial Data Science with R" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="spatialanalysis/handsonspatialdata" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Global Spatial Autocorrelation 1 | Hands-On Spatial Data Science with R" />
  
  
  

<meta name="author" content="Luc Anselin, Grant Morrison, Angela Li, Karina Acosta" />


<meta name="date" content="2023-10-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="applications-of-spatial-weights.html"/>
<link rel="next" href="global-spatial-autocorrelation-2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.2.0/leaflet.js"></script>
<script src="libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.2.0/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i>Disclaimer</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#using-this-book"><i class="fa fa-check"></i>Using This Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#who-this-book-is-for"><i class="fa fa-check"></i>Who This Book Is For</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html"><i class="fa fa-check"></i><b>1</b> Spatial Data Handling</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#introduction-1"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#objectives"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#preliminaries"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#loading-packages"><i class="fa fa-check"></i>Loading packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#obtaining-data-from-the-chicago-open-data-portal"><i class="fa fa-check"></i>Obtaining data from the Chicago Open Data portal</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#selecting-observations-for-a-given-time-period"><i class="fa fa-check"></i>Selecting Observations for a Given Time Period</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-observations-for-the-desired-time-period"><i class="fa fa-check"></i>Extracting observations for the desired time period</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#selecting-the-variables-for-the-final-table"><i class="fa fa-check"></i>Selecting the variables for the final table</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-point-layer"><i class="fa fa-check"></i>Creating a Point Layer</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-point-layer-from-coordinates-in-a-table---principle"><i class="fa fa-check"></i>Creating a point layer from coordinates in a table - principle</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-spatial-points-object"><i class="fa fa-check"></i>Creating a spatial points object</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#abandoned-vehicles-by-community-area"><i class="fa fa-check"></i>Abandoned Vehicles by Community Area</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#community-area-boundary-file"><i class="fa fa-check"></i>Community Area boundary file</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#spatial-join"><i class="fa fa-check"></i>Spatial join</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#counts-by-community-area"><i class="fa fa-check"></i>Counts by community area</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#mapping-the-vehicle-counts"><i class="fa fa-check"></i>Mapping the vehicle counts</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#community-area-population-data"><i class="fa fa-check"></i>Community Area Population Data</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-a-pdf-file"><i class="fa fa-check"></i>Extracting a pdf file</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#parsing-the-pdf-file"><i class="fa fa-check"></i>Parsing the pdf file</a></li>
<li class="chapter" data-level="1.0.1" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-the-population-values"><i class="fa fa-check"></i><b>1.0.1</b> Extracting the population values</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-data-frame-with-population-values"><i class="fa fa-check"></i>Creating a data frame with population values</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#mapping-community-area-abandoned-vehicles-per-capita"><i class="fa fa-check"></i>Mapping Community Area Abandoned Vehicles Per Capita</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#computing-abandoned-vehicles-per-capita"><i class="fa fa-check"></i>Computing abandoned vehicles per capita</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#final-choropleth-map"><i class="fa fa-check"></i>Final choropleth map</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html"><i class="fa fa-check"></i><b>2</b> Exploratory Data Analysis 1</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#introduction-2"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#objectives-1"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#preliminaries-1"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#load-packages"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#obtaining-the-data"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#analyzing-the-distribution-of-a-single-variable"><i class="fa fa-check"></i>Analyzing the Distribution of a Single Variable</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#a-quick-introduction-to-ggplot"><i class="fa fa-check"></i>A quick introduction to <strong>ggplot</strong></a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#bivariate-analysis-the-scatter-plot"><i class="fa fa-check"></i>Bivariate Analysis: The Scatter Plot</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#smoothing-the-scatter-plot"><i class="fa fa-check"></i>Smoothing the scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#spatial-heterogeneity"><i class="fa fa-check"></i>Spatial heterogeneity</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#structural-breaks-in-the-scatter-plot"><i class="fa fa-check"></i>Structural breaks in the scatter plot</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#chow-test"><i class="fa fa-check"></i>Chow test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html"><i class="fa fa-check"></i><b>3</b> Exploratory Data Analysis 2</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#introduction-3"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#objectives-2"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#preliminaries-2"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#load-packages-1"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#obtaining-the-data-1"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#scatter-plot-matrix"><i class="fa fa-check"></i>Scatter Plot Matrix</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#basic-scatter-plot-matrix"><i class="fa fa-check"></i>Basic scatter plot matrix</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#scatter-plot-matrix-with-smoothing"><i class="fa fa-check"></i>Scatter plot matrix with smoothing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#three-variables-bubble-chart-and-3d-scatter-plot"><i class="fa fa-check"></i>Three Variables: Bubble Chart and 3D Scatter Plot</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#bubble-chart"><i class="fa fa-check"></i>Bubble chart</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#d-scatter-plot"><i class="fa fa-check"></i>3D Scatter Plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#true-multivariate-eda-parallel-coordinate-plot-and-conditional-plots"><i class="fa fa-check"></i>True Multivariate EDA: Parallel Coordinate Plot and Conditional Plots</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#parallel-coordinate-plot-pcp"><i class="fa fa-check"></i>Parallel Coordinate Plot (PCP)</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#conditional-plots"><i class="fa fa-check"></i>Conditional Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="basic-mapping.html"><a href="basic-mapping.html"><i class="fa fa-check"></i><b>4</b> Basic Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#introduction-4"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#objectives-3"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#preliminaries-3"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#load-packages-2"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#obtaining-the-data-2"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#basic-choropleth-mapping"><i class="fa fa-check"></i>Basic Choropleth Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#default-settings-1"><i class="fa fa-check"></i>Default settings</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#color-palette"><i class="fa fa-check"></i>Color palette</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#legend"><i class="fa fa-check"></i>Legend</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#title"><i class="fa fa-check"></i>Title</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#border-options"><i class="fa fa-check"></i>Border options</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#interactive-base-map"><i class="fa fa-check"></i>Interactive base map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#saving-a-map-as-a-file"><i class="fa fa-check"></i>Saving a map as a file</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#shape-centers"><i class="fa fa-check"></i>Shape centers</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#common-map-classifications"><i class="fa fa-check"></i>Common Map Classifications</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#quantile-map"><i class="fa fa-check"></i>Quantile map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#natural-breaks-map"><i class="fa fa-check"></i>Natural breaks map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#equal-intervals-map"><i class="fa fa-check"></i>Equal intervals map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#custom-breaks"><i class="fa fa-check"></i>Custom breaks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#extreme-value-maps"><i class="fa fa-check"></i>Extreme Value Maps</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#percentile-map"><i class="fa fa-check"></i>Percentile map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#box-map"><i class="fa fa-check"></i>Box map</a></li>
<li class="chapter" data-level="4.0.1" data-path="basic-mapping.html"><a href="basic-mapping.html#standard-deviation-map"><i class="fa fa-check"></i><b>4.0.1</b> Standard deviation map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#mapping-categorical-variables"><i class="fa fa-check"></i>Mapping Categorical Variables</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#unique-value-map"><i class="fa fa-check"></i>Unique value map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#co-location-map"><i class="fa fa-check"></i>Co-location map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#conditional-map"><i class="fa fa-check"></i>Conditional Map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#cartogram"><i class="fa fa-check"></i>Cartogram</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rate-mapping.html"><a href="rate-mapping.html"><i class="fa fa-check"></i><b>5</b> Rate Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="rate-mapping.html"><a href="rate-mapping.html#introduction-5"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="rate-mapping.html"><a href="rate-mapping.html#objectives-4"><i class="fa fa-check"></i><b>5.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="5.1" data-path="rate-mapping.html"><a href="rate-mapping.html#preliminaries-4"><i class="fa fa-check"></i><b>5.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="rate-mapping.html"><a href="rate-mapping.html#load-packages-3"><i class="fa fa-check"></i><b>5.1.1</b> Load packages</a></li>
<li class="chapter" data-level="5.1.2" data-path="rate-mapping.html"><a href="rate-mapping.html#geodadata"><i class="fa fa-check"></i><b>5.1.2</b> geodaData</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="rate-mapping.html"><a href="rate-mapping.html#choropleth-map-for-rates"><i class="fa fa-check"></i><b>5.2</b> Choropleth Map for Rates</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="rate-mapping.html"><a href="rate-mapping.html#spatially-extensive-and-intensive-variables"><i class="fa fa-check"></i><b>5.2.1</b> Spatially extensive and intensive variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="rate-mapping.html"><a href="rate-mapping.html#raw-rate-map"><i class="fa fa-check"></i><b>5.2.2</b> Raw rate map</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="rate-mapping.html"><a href="rate-mapping.html#excess-risk"><i class="fa fa-check"></i><b>5.3</b> Excess risk</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="rate-mapping.html"><a href="rate-mapping.html#relative-risk"><i class="fa fa-check"></i><b>5.3.1</b> Relative risk</a></li>
<li class="chapter" data-level="5.3.2" data-path="rate-mapping.html"><a href="rate-mapping.html#excess-risk-map"><i class="fa fa-check"></i><b>5.3.2</b> Excess risk map</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="rate-mapping.html"><a href="rate-mapping.html#empirical-bayes-smoothed-rate-map"><i class="fa fa-check"></i><b>5.4</b> Empirical Bayes Smoothed Rate Map</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="rate-mapping.html"><a href="rate-mapping.html#borrowing-strength"><i class="fa fa-check"></i><b>5.4.1</b> Borrowing strength</a></li>
<li class="chapter" data-level="5.4.2" data-path="rate-mapping.html"><a href="rate-mapping.html#bayes-law"><i class="fa fa-check"></i><b>5.4.2</b> Bayes law</a></li>
<li class="chapter" data-level="5.4.3" data-path="rate-mapping.html"><a href="rate-mapping.html#the-poisson-gamma-model"><i class="fa fa-check"></i><b>5.4.3</b> The Poisson-Gamma model</a></li>
<li class="chapter" data-level="5.4.4" data-path="rate-mapping.html"><a href="rate-mapping.html#the-empirical-bayes-approach"><i class="fa fa-check"></i><b>5.4.4</b> The Empirical Bayes approach</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="rate-mapping.html"><a href="rate-mapping.html#eb-rate-map"><i class="fa fa-check"></i><b>5.5</b> EB rate map</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html"><i class="fa fa-check"></i><b>6</b> Contiguity-Based Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#introduction-6"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#objectives-5"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#preliminaries-5"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#load-packages-4"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#geodadata-1"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#contiguity-weights"><i class="fa fa-check"></i>Contiguity Weights</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#rook-contiguity"><i class="fa fa-check"></i>Rook Contiguity</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#queen-contiguity"><i class="fa fa-check"></i>Queen Contiguity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#higher-order-contiguity"><i class="fa fa-check"></i>Higher Order Contiguity</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#visualizing-contiguity-neighbors"><i class="fa fa-check"></i>Visualizing Contiguity Neighbors</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#connectivity-graph"><i class="fa fa-check"></i>Connectivity Graph</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#connectivity-histogram"><i class="fa fa-check"></i>Connectivity Histogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#saving-neighbors"><i class="fa fa-check"></i>Saving Neighbors</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#oldstyle"><i class="fa fa-check"></i>Oldstyle</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#geoda-header-format"><i class="fa fa-check"></i>GeoDA Header Format</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html"><i class="fa fa-check"></i><b>7</b> Distance-Based Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#introduction-7"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#objectives-6"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#preliminaries-6"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#load-packages-5"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#geodadata-2"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#visualizing-point-data"><i class="fa fa-check"></i>Visualizing point data</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#distance-band-weights"><i class="fa fa-check"></i>Distance-Band Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#concepts"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#creating-distance-band-weights"><i class="fa fa-check"></i>Creating distance-band weights</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#weights-characteristics"><i class="fa fa-check"></i>Weights characteristics</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#isolates"><i class="fa fa-check"></i>Isolates</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#k-nearest-neighbor-weights"><i class="fa fa-check"></i>K-Nearest Neighbor Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#concept"><i class="fa fa-check"></i>Concept</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#creating-knn-weights"><i class="fa fa-check"></i>Creating KNN Weights</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#properties-of-knn-weights"><i class="fa fa-check"></i>Properties of KNN weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#generalizing-the-concept-of-contiguity"><i class="fa fa-check"></i>Generalizing the Concept of Contiguity</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#contiguity-based-weights-for-points"><i class="fa fa-check"></i>Contiguity-based weights for points</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#contiguity-weights-for-thiessen-polygons"><i class="fa fa-check"></i>Contiguity weights for Thiessen polygons</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#distance-based-weights-for-polygons"><i class="fa fa-check"></i>Distance-based weights for polygons</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#getting-the-data"><i class="fa fa-check"></i>Getting the data</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-the-centroids"><i class="fa fa-check"></i>Computing the centroids</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-the-critical-threshold"><i class="fa fa-check"></i>Computing the critical threshold</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-distance-band-neighbors"><i class="fa fa-check"></i>Computing distance-band neighbors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html"><i class="fa fa-check"></i><b>8</b> Spatial Weights as Distance Functions</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#introduction-8"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#objectives-7"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#preliminaries-7"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#load-packages-6"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#obtaining-the-data-from-the-geoda-website"><i class="fa fa-check"></i>Obtaining the Data from the GeoDa website</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#inverse-distance-weights"><i class="fa fa-check"></i>Inverse Distance Weights</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#concepts-1"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="8.0.1" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-inverse-distance-functions-for-distance-bands"><i class="fa fa-check"></i><b>8.0.1</b> Creating inverse distance functions for distance bands</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-inverse-distance-functions-for-k-nearest-neighbors"><i class="fa fa-check"></i>Creating inverse distance functions for k-nearest neighbors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#kernal-weights"><i class="fa fa-check"></i>Kernal Weights</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#concepts-2"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-kernal-weights"><i class="fa fa-check"></i>Creating Kernal weights</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html"><i class="fa fa-check"></i><b>9</b> Applications of Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#introduction-9"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#objectives-8"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#preliminaries-8"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#load-packages-7"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#geodadata-3"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables"><i class="fa fa-check"></i>Spatially lagged variables</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#creating-a-spatially-lagged-variable"><i class="fa fa-check"></i>Creating a spatially lagged variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables-from-inverse-distance-weights"><i class="fa fa-check"></i>Spatially lagged variables from inverse distance weights</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#default-approach"><i class="fa fa-check"></i>Default approach</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-lags-with-row-standardized-inverse-distance-weights"><i class="fa fa-check"></i>Spatial lags with row-standardized inverse distance weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables-from-kernel-weights"><i class="fa fa-check"></i>Spatially lagged variables from kernel weights</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-rate-smoothing"><i class="fa fa-check"></i>Spatial rate smoothing</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle-1"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#preliminaries-9"><i class="fa fa-check"></i>Preliminaries</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#simple-window-average-of-rates"><i class="fa fa-check"></i>Simple window average of rates</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-smoothed-rates"><i class="fa fa-check"></i>Spatially Smoothed Rates</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-empirical-bayes-smoothing"><i class="fa fa-check"></i>Spatial Empirical Bayes smoothing</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle-2"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-eb-rate-smoother"><i class="fa fa-check"></i>Spatial EB rate smoother</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html"><i class="fa fa-check"></i><b>10</b> Global Spatial Autocorrelation 1</a>
<ul>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#introduction-10"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="10.0.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#objectives-9"><i class="fa fa-check"></i><b>10.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="10.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#preliminaries-10"><i class="fa fa-check"></i><b>10.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#load-packages-8"><i class="fa fa-check"></i><b>10.1.1</b> Load packages</a></li>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#geodadata-website"><i class="fa fa-check"></i>geodaData website</a></li>
<li class="chapter" data-level="10.1.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#making-the-weights"><i class="fa fa-check"></i><b>10.1.2</b> Making the weights</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#the-moran-scatter-plot"><i class="fa fa-check"></i><b>10.2</b> The Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#concept-1"><i class="fa fa-check"></i><b>10.2.1</b> Concept</a></li>
<li class="chapter" data-level="10.2.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#creating-a-moran-scatter-plot"><i class="fa fa-check"></i><b>10.2.2</b> Creating a Moran scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#spatial-correlogram"><i class="fa fa-check"></i><b>10.3</b> Spatial Correlogram</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#concept-2"><i class="fa fa-check"></i><b>10.3.1</b> Concept</a></li>
<li class="chapter" data-level="10.3.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#creating-a-spatial-correlogram"><i class="fa fa-check"></i><b>10.3.2</b> Creating a spatial correlogram</a></li>
<li class="chapter" data-level="10.3.3" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#interpretation-1"><i class="fa fa-check"></i><b>10.3.3</b> Interpretation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html"><i class="fa fa-check"></i><b>11</b> Global Spatial Autocorrelation 2</a>
<ul>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#introduction-11"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="11.0.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#objectives-10"><i class="fa fa-check"></i><b>11.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="11.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#preliminaries-11"><i class="fa fa-check"></i><b>11.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#load-packages-9"><i class="fa fa-check"></i><b>11.1.1</b> Load packages</a></li>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#obtaining-the-data-from-the-geoda-website-1"><i class="fa fa-check"></i>Obtaining the Data from the GeoDa website</a></li>
<li class="chapter" data-level="11.1.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#creating-the-weights-2"><i class="fa fa-check"></i><b>11.1.2</b> Creating the weights</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#bivariate-spatial-correlation---a-word-of-caution"><i class="fa fa-check"></i><b>11.2</b> Bivariate spatial correlation - a Word of Caution</a></li>
<li class="chapter" data-level="11.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#bivariate-moran-scatter-plot"><i class="fa fa-check"></i><b>11.3</b> Bivariate Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-3"><i class="fa fa-check"></i><b>11.3.1</b> Concept</a></li>
<li class="chapter" data-level="11.3.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#creating-a-bivariate-moran-scatter-plot"><i class="fa fa-check"></i><b>11.3.2</b> Creating a bivariate Moran scatter plot</a></li>
<li class="chapter" data-level="11.3.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#a-closer-look-at-bivariate-spatial-correlation"><i class="fa fa-check"></i><b>11.3.3</b> A closer look at bivariate spatial correlation</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#differential-moran-scatter-plot"><i class="fa fa-check"></i><b>11.4</b> Differential Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-4"><i class="fa fa-check"></i><b>11.4.1</b> Concept</a></li>
<li class="chapter" data-level="11.4.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#implementation"><i class="fa fa-check"></i><b>11.4.2</b> Implementation</a></li>
<li class="chapter" data-level="11.4.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#options"><i class="fa fa-check"></i><b>11.4.3</b> Options</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#moran-scatter-plot-for-eb-rates"><i class="fa fa-check"></i><b>11.5</b> Moran Scatter Plot for EB Rates</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-5"><i class="fa fa-check"></i><b>11.5.1</b> Concept</a></li>
<li class="chapter" data-level="11.5.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#implementation-1"><i class="fa fa-check"></i><b>11.5.2</b> Implementation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html"><i class="fa fa-check"></i><b>12</b> Local Spatial Autocorrelation 1</a>
<ul>
<li class="chapter" data-level="" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#introduction-12"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#objectives-11"><i class="fa fa-check"></i><b>12.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="12.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#preliminaries-12"><i class="fa fa-check"></i><b>12.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#load-packages-10"><i class="fa fa-check"></i><b>12.1.1</b> Load packages</a></li>
<li class="chapter" data-level="12.1.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#spatmap"><i class="fa fa-check"></i><b>12.1.2</b> spatmap</a></li>
<li class="chapter" data-level="12.1.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#geodadata-5"><i class="fa fa-check"></i><b>12.1.3</b> geodaData</a></li>
<li class="chapter" data-level="12.1.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#univariate-analysis"><i class="fa fa-check"></i><b>12.1.4</b> Univariate analysis</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-moran"><i class="fa fa-check"></i><b>12.2</b> Local Moran</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-3"><i class="fa fa-check"></i><b>12.2.1</b> Principle</a></li>
<li class="chapter" data-level="12.2.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-2"><i class="fa fa-check"></i><b>12.2.2</b> Implementation</a></li>
<li class="chapter" data-level="12.2.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#randomization-options"><i class="fa fa-check"></i><b>12.2.3</b> Randomization Options</a></li>
<li class="chapter" data-level="12.2.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#significance"><i class="fa fa-check"></i><b>12.2.4</b> Significance</a></li>
<li class="chapter" data-level="12.2.5" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#interpretation-of-clusters"><i class="fa fa-check"></i><b>12.2.5</b> Interpretation of clusters</a></li>
<li class="chapter" data-level="12.2.6" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#conditional-local-cluster-maps"><i class="fa fa-check"></i><b>12.2.6</b> Conditional local cluster maps</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-geary"><i class="fa fa-check"></i><b>12.3</b> Local Geary</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-4"><i class="fa fa-check"></i><b>12.3.1</b> Principle</a></li>
<li class="chapter" data-level="12.3.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-3"><i class="fa fa-check"></i><b>12.3.2</b> Implementation</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#getis-ord-statistics"><i class="fa fa-check"></i><b>12.4</b> Getis-Ord Statistics</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-5"><i class="fa fa-check"></i><b>12.4.1</b> Principle</a></li>
<li class="chapter" data-level="12.4.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-4"><i class="fa fa-check"></i><b>12.4.2</b> Implementation</a></li>
<li class="chapter" data-level="12.4.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#interpretation-and-significance-1"><i class="fa fa-check"></i><b>12.4.3</b> Interpretation and significance</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-join-count-statistic"><i class="fa fa-check"></i><b>12.5</b> Local Join Count Statistic</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-6"><i class="fa fa-check"></i><b>12.5.1</b> Principle</a></li>
<li class="chapter" data-level="12.5.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-5"><i class="fa fa-check"></i><b>12.5.2</b> Implementation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>13</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Hands-On Spatial Data Science with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="global-spatial-autocorrelation-1" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Global Spatial Autocorrelation 1<a href="global-spatial-autocorrelation-1.html#global-spatial-autocorrelation-1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-10" class="section level2 unnumbered hasAnchor">
<h2>Introduction<a href="global-spatial-autocorrelation-1.html#introduction-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This notebook cover the functionality of the <a href="https://geodacenter.github.io/workbook/5a_global_auto/lab5a.html">Global Spatial Autocorrelation 1</a> section of the GeoDa workbook. We refer to that document for details on the methodology, references, etc. The goal of these notes is to approximate as closely as possible the operations carried out using GeoDa by means of a range of R packages.</p>
<p>The notes are written with R beginners in mind, more seasoned R users can probably skip most of the comments
on data structures and other R particulars. Also, as always in R, there are typically several ways to achieve a specific objective, so what is shown here is just one way that works, but there often are others (that may even be more elegant, work faster, or scale better).</p>
<p>For this notebook, we use Cleveland house price data. Our goal in this lab is show how to assign spatial weights based on different distance functions.</p>
<div id="objectives-9" class="section level3 hasAnchor" number="10.0.1">
<h3><span class="header-section-number">10.0.1</span> Objectives<a href="global-spatial-autocorrelation-1.html#objectives-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After completing the notebook, you should know how to carry out the following tasks:</p>
<ul>
<li><p>Visualize Moran’s I with a Moran scatterplot</p></li>
<li><p>Carry out inference using the permutation approach</p></li>
<li><p>Make analysis reproducible with the random seed</p></li>
<li><p>Create a LOWESS smooth of the Moran scatter plot</p></li>
<li><p>Conduct a Chow test with the Moran scatterplot</p></li>
<li><p>Analyze the range of spatial autocorrelation by means of a spatial correlogram</p></li>
</ul>
<div id="r-packages-used-9" class="section level4 hasAnchor" number="10.0.1.1">
<h4><span class="header-section-number">10.0.1.1</span> R Packages used<a href="global-spatial-autocorrelation-1.html#r-packages-used-9" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p><strong>sf</strong>: To read in the shapefile and make queen contiguity weights</p></li>
<li><p><strong>spdep</strong>: To create k-nearest neighbors and distance-band neighbors, calculate distances between neighbors, convert to a weights structure, and coercion methods to sparse matrices.</p></li>
<li><p><strong>ggplot2</strong>: To make customized plots such as a Moran’s I scatter plot and spatial
correlogram.</p></li>
<li><p><strong>Hmisc</strong>: To get LOWESS smoother functionality in ggplot2.</p></li>
<li><p><strong>robustHD</strong>: To compute standarized scores for variables and lag variables. in construction of a Moran’s I scatterplot</p></li>
<li><p><strong>deldir</strong>: To create voronoi polygons.</p></li>
<li><p><strong>tidyverse</strong>: For basic data frame manipulation.</p></li>
<li><p><strong>gap</strong>: To compute chow test statistics.</p></li>
<li><p><strong>gridExtra</strong>: To pack multiple plots into one, mainly used to construct the spatial correlogram</p></li>
<li><p><strong>geodaData</strong>: To access the data for this tutorial</p></li>
</ul>
</div>
<div id="r-commands-used-9" class="section level4 hasAnchor" number="10.0.1.2">
<h4><span class="header-section-number">10.0.1.2</span> R Commands used<a href="global-spatial-autocorrelation-1.html#r-commands-used-9" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Below follows a list of the commands used in this notebook. For further details
and a comprehensive list of options, please consult the
<a href="https://www.rdocumentation.org">R documentation</a>.</p>
<ul>
<li><p><strong>Base R</strong>: <code>install.packages</code>, <code>library</code>, <code>setwd</code>, <code>rep</code>, <code>sd</code>, <code>mean</code>, <code>summary</code>, <code>attributes</code>, <code>lapply</code>, <code>class</code>, <code>length</code>, <code>which</code>, <code>data.frame</code>, <code>plot</code></p></li>
<li><p><strong>sf</strong>: <code>st_read</code>, <code>st_relate</code>, <code>st_as_sf</code></p></li>
<li><p><strong>spdep</strong>: <code>dnearneigh</code>, <code>nb2listw</code>, <code>sp.correlogram</code>, <code>Szero</code></p></li>
<li><p><strong>ggplot2</strong>: <code>ggplot</code>, <code>geom_smooth</code>, <code>geom_point</code>, <code>xlim</code>, <code>ylim</code>, <code>geom_hline</code>, <code>geom_vline</code>, <code>geom_line</code>,
<code>ggtitle</code>, <code>scale_x_continous</code></p></li>
<li><p><strong>Hmisc</strong>: <code>stat_plsmo</code></p></li>
<li><p><strong>robustHD</strong>: <code>standardized</code></p></li>
<li><p><strong>deldir</strong>: <code>deldir</code></p></li>
<li><p><strong>tidyverse</strong>: <code>filter</code></p></li>
<li><p><strong>gap</strong>: <code>chow.test</code></p></li>
<li><p><strong>gridExtra</strong>: <code>grid.arrange</code></p></li>
</ul>
</div>
</div>
</div>
<div id="preliminaries-10" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Preliminaries<a href="global-spatial-autocorrelation-1.html#preliminaries-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before starting, make sure to have the latest version of R and of packages that are compiled for the matching version of R (this document was created using R 3.5.1 of 2018-07-02). Also, optionally, set a working directory, even though we will not
actually be saving any files.<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a></p>
<div id="load-packages-8" class="section level3 hasAnchor" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> Load packages<a href="global-spatial-autocorrelation-1.html#load-packages-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, we load all the required packages using the <code>library</code> command. If you don’t have some of these in your system, make sure to install them first as well as
their dependencies.<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a> You will get an error message if something is missing. If needed, just install the missing piece and everything will work after that.</p>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="global-spatial-autocorrelation-1.html#cb543-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb543-2"><a href="global-spatial-autocorrelation-1.html#cb543-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb543-3"><a href="global-spatial-autocorrelation-1.html#cb543-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb543-4"><a href="global-spatial-autocorrelation-1.html#cb543-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(deldir)</span>
<span id="cb543-5"><a href="global-spatial-autocorrelation-1.html#cb543-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(robustHD)</span>
<span id="cb543-6"><a href="global-spatial-autocorrelation-1.html#cb543-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb543-7"><a href="global-spatial-autocorrelation-1.html#cb543-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb543-8"><a href="global-spatial-autocorrelation-1.html#cb543-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gap)</span>
<span id="cb543-9"><a href="global-spatial-autocorrelation-1.html#cb543-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb543-10"><a href="global-spatial-autocorrelation-1.html#cb543-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geodaData)</span></code></pre></div>
</div>
<div id="geodadata-website" class="section level3 unnumbered hasAnchor">
<h3>geodaData website<a href="global-spatial-autocorrelation-1.html#geodadata-website" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>All of the data for the R notebooks is available in the <strong>geodaData</strong>
package. We loaded the library earlier, now to access the individual
data sets, we use the double colon notation. This works similar to
to accessing a variable with <code>$</code>, in that a drop down menu will
appear with a list of the datasets included in the package. For this
notebook, we use <code>clev_pts</code>.</p>
<p>Otherwise, to get the data for this notebook, you will and to go to <a href="https://geodacenter.github.io/data-and-lab//clev_sls_154_core/">Cleveland Home Sales</a> The download format is a
zipfile, so you will need to unzip it by double clicking on the file in your file
finder. From there move the resulting folder titled: nyc into your working directory
to continue. Once that is done, you can use the <strong>sf</strong> function: <code>st_read()</code> to read
the shapefile into your R environment.</p>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="global-spatial-autocorrelation-1.html#cb544-1" aria-hidden="true" tabindex="-1"></a>clev.points <span class="ot">&lt;-</span> geodaData<span class="sc">::</span>clev_pts</span></code></pre></div>
</div>
<div id="making-the-weights" class="section level3 hasAnchor" number="10.1.2">
<h3><span class="header-section-number">10.1.2</span> Making the weights<a href="global-spatial-autocorrelation-1.html#making-the-weights" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The weights used for this notebook are queen contiguity, based off voronoi polygons contructed
from the point data for this notebook. In order to make the weights, we must first construct
voronoi polygons from the cleveland point data. There are a number of ways to do this. We
will be using the <strong>deldir</strong> package as a starting point. We will need to convert the result from
the <strong>deldir</strong> package to class <strong>sf</strong>, which we have been working with throughout the notebooks.</p>
<p>The only function we need from <strong>deldir</strong> is <code>deldir</code>, which outputs a data structure with
voronoi polygons. The only inputs needed are a vector of the x coordinates and a vector of the y
coordinates. The base R <code>plot</code> function can give us a preliminary look at the voronoi polygons.
We will need a few additional parameters other than <strong>vtess</strong>, so the plot is legitable.
Set <code>wlines = "tess"</code>, <code>wpoints = "none"</code> and <code>lty = 1</code>.</p>
<div class="sourceCode" id="cb545"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb545-1"><a href="global-spatial-autocorrelation-1.html#cb545-1" aria-hidden="true" tabindex="-1"></a>vtess <span class="ot">&lt;-</span> <span class="fu">deldir</span>(clev.points<span class="sc">$</span>x, clev.points<span class="sc">$</span>y)</span>
<span id="cb545-2"><a href="global-spatial-autocorrelation-1.html#cb545-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vtess, <span class="at">wlines=</span><span class="st">&quot;tess&quot;</span>, <span class="at">wpoints=</span><span class="st">&quot;none&quot;</span>,</span>
<span id="cb545-3"><a href="global-spatial-autocorrelation-1.html#cb545-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-397-1.png" width="672" /></p>
<p>This function will be used to convert the <strong>deldir</strong> voronoi polygons to <strong>sp</strong>, where we
can easily convert them to <strong>sf</strong>. We are not going to cover the individual steps of this
function because it is outside the scope of these notebooks. The important thing to note
here is that this function converts <strong>deldir</strong> voronoi polygons to <strong>sp</strong>.</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="global-spatial-autocorrelation-1.html#cb546-1" aria-hidden="true" tabindex="-1"></a>voronoipolygons <span class="ot">=</span> <span class="cf">function</span>(thiess) {</span>
<span id="cb546-2"><a href="global-spatial-autocorrelation-1.html#cb546-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">=</span> <span class="fu">tile.list</span>(thiess)</span>
<span id="cb546-3"><a href="global-spatial-autocorrelation-1.html#cb546-3" aria-hidden="true" tabindex="-1"></a>polys <span class="ot">=</span> <span class="fu">vector</span>(<span class="at">mode=</span><span class="st">&#39;list&#39;</span>, <span class="at">length=</span><span class="fu">length</span>(w))</span>
<span id="cb546-4"><a href="global-spatial-autocorrelation-1.html#cb546-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq</span>(<span class="at">along=</span>polys)) {</span>
<span id="cb546-5"><a href="global-spatial-autocorrelation-1.html#cb546-5" aria-hidden="true" tabindex="-1"></a>    pcrds <span class="ot">=</span> <span class="fu">cbind</span>(w[[i]]<span class="sc">$</span>x, w[[i]]<span class="sc">$</span>y)</span>
<span id="cb546-6"><a href="global-spatial-autocorrelation-1.html#cb546-6" aria-hidden="true" tabindex="-1"></a>    pcrds <span class="ot">=</span> <span class="fu">rbind</span>(pcrds, pcrds[<span class="dv">1</span>,])</span>
<span id="cb546-7"><a href="global-spatial-autocorrelation-1.html#cb546-7" aria-hidden="true" tabindex="-1"></a>    polys[[i]] <span class="ot">=</span> <span class="fu">Polygons</span>(<span class="fu">list</span>(<span class="fu">Polygon</span>(pcrds)), <span class="at">ID=</span><span class="fu">as.character</span>(i))</span>
<span id="cb546-8"><a href="global-spatial-autocorrelation-1.html#cb546-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb546-9"><a href="global-spatial-autocorrelation-1.html#cb546-9" aria-hidden="true" tabindex="-1"></a>SP <span class="ot">=</span> <span class="fu">SpatialPolygons</span>(polys)</span>
<span id="cb546-10"><a href="global-spatial-autocorrelation-1.html#cb546-10" aria-hidden="true" tabindex="-1"></a> voronoi <span class="ot">=</span> <span class="fu">SpatialPolygonsDataFrame</span>(SP, <span class="at">data=</span><span class="fu">data.frame</span>(<span class="at">dummy =</span> <span class="fu">seq</span>(<span class="fu">length</span>(SP)), <span class="at">row.names=</span><span class="fu">sapply</span>(<span class="fu">slot</span>(SP, <span class="st">&#39;polygons&#39;</span>), </span>
<span id="cb546-11"><a href="global-spatial-autocorrelation-1.html#cb546-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">function</span>(x) <span class="fu">slot</span>(x, <span class="st">&#39;ID&#39;</span>))))</span>
<span id="cb546-12"><a href="global-spatial-autocorrelation-1.html#cb546-12" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Again, we can use the base R <code>plot</code> function to take a look at voronoi polygons. Now that they
are class <strong>sp</strong>, we don’t need the extra parameters in <code>plot</code>.</p>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="global-spatial-autocorrelation-1.html#cb547-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">voronoipolygons</span>(vtess)</span>
<span id="cb547-2"><a href="global-spatial-autocorrelation-1.html#cb547-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(v)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-399-1.png" width="672" /></p>
<p>With the voronoi polygons in <strong>sp</strong> class, we can easily conert them to <strong>sf</strong> with
<code>st_as_sf</code>. Again we use the base R <code>plot</code> function to view the polygons.</p>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="global-spatial-autocorrelation-1.html#cb548-1" aria-hidden="true" tabindex="-1"></a>vtess.sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(v)</span>
<span id="cb548-2"><a href="global-spatial-autocorrelation-1.html#cb548-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vtess.sf<span class="sc">$</span>geometry)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-400-1.png" width="672" /></p>
<p>Now that we have the voronoi polygons as an <strong>sf</strong> object, we can use the queen contiguity
process outline in the Contiguity Based Weights notebook. We will briefly cover
each step of the process. For more indepth information please see the Contiguity
Based Weights notebook.</p>
<p>To start we create a function for queen contiguity, which is just <code>st_relate</code> with
the specified pattern for queen contiguity which is <code>F***T****</code></p>
<div class="sourceCode" id="cb549"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb549-1"><a href="global-spatial-autocorrelation-1.html#cb549-1" aria-hidden="true" tabindex="-1"></a>st_queen <span class="ot">&lt;-</span> <span class="cf">function</span>(a, <span class="at">b =</span> a) <span class="fu">st_relate</span>(a, b, <span class="at">pattern =</span> <span class="st">&quot;F***T****&quot;</span>)</span></code></pre></div>
<p>We apply the queen contiguity function to the voronoi polygons and see that the class
of the output is <strong>sgbp</strong>. This structure is close to the <strong>nb</strong> structure, but has
a few differences that we will need to correct to use the rest of <strong>spdep</strong> functionality.</p>
<div class="sourceCode" id="cb550"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb550-1"><a href="global-spatial-autocorrelation-1.html#cb550-1" aria-hidden="true" tabindex="-1"></a>queen.sgbp <span class="ot">&lt;-</span> <span class="fu">st_queen</span>(vtess.sf)</span>
<span id="cb550-2"><a href="global-spatial-autocorrelation-1.html#cb550-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(queen.sgbp)</span></code></pre></div>
<pre><code>## [1] &quot;sgbp&quot; &quot;list&quot;</code></pre>
<p>This function converts type <strong>sgbp</strong> to <strong>nb</strong>. It is covered in more depth in the
Contiguity Based Weight notebook. In short, it explicitly changes the name of the
class and deals with the observations that have no neighbors.</p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="global-spatial-autocorrelation-1.html#cb552-1" aria-hidden="true" tabindex="-1"></a>as.nb.sgbp <span class="ot">&lt;-</span> <span class="cf">function</span>(x, ...) {</span>
<span id="cb552-2"><a href="global-spatial-autocorrelation-1.html#cb552-2" aria-hidden="true" tabindex="-1"></a>  attrs <span class="ot">&lt;-</span> <span class="fu">attributes</span>(x)</span>
<span id="cb552-3"><a href="global-spatial-autocorrelation-1.html#cb552-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">lapply</span>(x, <span class="cf">function</span>(i) { <span class="cf">if</span>(<span class="fu">length</span>(i) <span class="sc">==</span> 0L) 0L <span class="cf">else</span> i } )</span>
<span id="cb552-4"><a href="global-spatial-autocorrelation-1.html#cb552-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">attributes</span>(x) <span class="ot">&lt;-</span> attrs</span>
<span id="cb552-5"><a href="global-spatial-autocorrelation-1.html#cb552-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">class</span>(x) <span class="ot">&lt;-</span> <span class="st">&quot;nb&quot;</span></span>
<span id="cb552-6"><a href="global-spatial-autocorrelation-1.html#cb552-6" aria-hidden="true" tabindex="-1"></a>  x</span>
<span id="cb552-7"><a href="global-spatial-autocorrelation-1.html#cb552-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>We use <code>as.nb.sgbp</code> to convert neighbor types and then check the class with <code>class</code>.</p>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="global-spatial-autocorrelation-1.html#cb553-1" aria-hidden="true" tabindex="-1"></a>queen.nb <span class="ot">&lt;-</span> <span class="fu">as.nb.sgbp</span>(queen.sgbp)</span>
<span id="cb553-2"><a href="global-spatial-autocorrelation-1.html#cb553-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(queen.nb)</span></code></pre></div>
<pre><code>## [1] &quot;nb&quot;</code></pre>
<p>To go from neighbors object to weights object, we use <code>nb2listw</code>, with default parameters, we will
get row standardized weights.</p>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="global-spatial-autocorrelation-1.html#cb555-1" aria-hidden="true" tabindex="-1"></a>queen.weights <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(queen.nb)</span></code></pre></div>
</div>
</div>
<div id="the-moran-scatter-plot" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> The Moran Scatter Plot<a href="global-spatial-autocorrelation-1.html#the-moran-scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="concept-1" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Concept<a href="global-spatial-autocorrelation-1.html#concept-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="morans-i" class="section level4 hasAnchor" number="10.2.1.1">
<h4><span class="header-section-number">10.2.1.1</span> Moran’s I<a href="global-spatial-autocorrelation-1.html#morans-i" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Moran’s I statistic is arguably the most commonly used indicator of global spatial
autocorrelation. It was initially suggested by Moran (1948), and popularized through
the classic work on spatial autocorrelation by Cliff and Ord (1973). In essence, it is
a cross-product statistic between a variable and its spatial lag, with the variable
expressed in deviations from its mean. For an observation at location i, this is
expressed as <span class="math inline">\(z_i = x_i - \bar{x}\)</span>, where <span class="math inline">\(\bar{x}\)</span>is the mean of variable x.</p>
<p>Moran’s I statistic is then:</p>
<p><span class="math display">\[I = \frac{\Sigma_i\Sigma_jw_{ij}z_iz_j/S_0}{\Sigma_iz_i^2/n}\]</span>
with <span class="math inline">\(w_{ij}\)</span> as elements of the spatial weights matrix, <span class="math inline">\(S_0 = \Sigma_i\Sigma_jw_{ij}\)</span>
as the sum of all of the weights and n as the number of observations.</p>
</div>
<div id="permutation-inference" class="section level4 hasAnchor" number="10.2.1.2">
<h4><span class="header-section-number">10.2.1.2</span> Permutation inference<a href="global-spatial-autocorrelation-1.html#permutation-inference" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Inference for Moran’s I is based on a null hypothesis of spatial randomness. The
distribution of the statistic under the null can be derived using either an
assumption of normality (independent normal random variates), or so-called
randomization (i.e., each value is equally likely to occur at any location).</p>
<p>An alternative to an analytical derivation is a computational approach based on
permutation. This calculates a reference distribution for the statistic under the
null hypothesis of spatial randomness by randomly permuting the observed values
over the locations. The statistic is computed for each of these randomly
reshuffled data sets, which yields a reference distribution.</p>
<p>This distribution is then used to calculate a so-called pseudo p-value. This is
found as
<span class="math display">\[p = \frac{R +1}{M+1}\]</span>
where R is the number of times the computed Moran’s I from the spatial random data
sets (the permuted data sets) is equal to or more extreme than the observed
statistic. M equals the number of permutations. The latter is typically taken as
99, 999, etc., to yield nicely rounded pseudo p-values.</p>
<p>The pseudo p-value is only a summary of the results from the reference
distribution and should not be interpreted as an analytical p-value. Most
importantly, it should be kept in mind that the extent of significance is
determined in part by the number of random pemutations. More precisely, a result
that has a p-value of 0.01 with 99 permutations is not necessarily more
significant than a result with a p-value of 0.001 with 999 permutations.</p>
</div>
<div id="moran-scatter-plot" class="section level4 hasAnchor" number="10.2.1.3">
<h4><span class="header-section-number">10.2.1.3</span> Moran scatter plot<a href="global-spatial-autocorrelation-1.html#moran-scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Moran scatter plot, first outlined in Anselin (1996), consists of a plot with the spatially
lagged variable on the y-axis and the original variable on the x-axis. The slope of the linear fit to
the scatter plot equals Moran’s I.</p>
<p>We consider a variable z, given in deviations from the mean. With row-standardized weights, the sum
of all the weights (S0) equals the number of obsevations (n). As a result, the expression for Moran’s
I simplifies to:</p>
<p><span class="math display">\[I= \frac{\Sigma_i\Sigma_jw_{ij}z_iz_j}{\Sigma_iz_i^2} = \frac{\Sigma_i(z_i*\Sigma_jw_{ij}z_j)}{\Sigma_iz_i^2}\]</span></p>
<p>Upon closer examination, this turns out to be the slope of a regression of <span class="math inline">\(\Sigma_jw_{ij}z_i\)</span> on <span class="math inline">\(z_i\)</span>
This is the principle underlying the Moran scatter plot.</p>
<p>An important aspect of the visualization in the Moran scatter plot is the classification of the
nature of spatial autocorrelation into four categories. Since the plot is centered on the mean (of
zero), all points to the right of the mean have <span class="math inline">\(z_i&gt;0\)</span> and all points to the left have <span class="math inline">\(z_i&lt;0\)</span>.
We refer to these values respectively as high and low, in the limited sense of higher or lower than
average. Similarly, we can classify the values for the spatial lag above and below the mean as high
and low.</p>
<p>The scatter plot is then easily decomposed into four quadrants. The upper-right
quadrant and the lower-left quadrant correspond with positive spatial
autocorrelation (similar values at neighboring locations). We refer to them as
respectively high-high and low-low spatial autocorrelation. In contrast, the
lower-right and upper-left quadrant correspond to negative spatial autocorrelation
(dissimilar values at neighboring locations). We refer to them as respectively
high-low and low-high spatial autocorrelation.</p>
<p>The classification of the spatial autocorrelation into four types begins to make
the connection between global and local spatial autocorrelation. However, it is
important to keep in mind that the classification as such does not imply
significance. This is further explored in our discussion of local indicators of
spatial association (LISA).</p>
</div>
</div>
<div id="creating-a-moran-scatter-plot" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> Creating a Moran scatter plot<a href="global-spatial-autocorrelation-1.html#creating-a-moran-scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before we create the Moran’s I scatterplot, we will get the statistic using <code>moran</code> from
<strong>spdep</strong>. For this function, we need the a variable to do the Moran’s I on, a weights
structure, the length of the dataset, and then <code>Szero</code> of the queen
weights, which calculates the constants needed for tests of spatial
autocorrelation.</p>
<div class="sourceCode" id="cb556"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb556-1"><a href="global-spatial-autocorrelation-1.html#cb556-1" aria-hidden="true" tabindex="-1"></a>moran <span class="ot">&lt;-</span> <span class="fu">moran</span>(clev.points<span class="sc">$</span>sale_price, queen.weights, <span class="fu">length</span>(queen.nb), <span class="fu">Szero</span>(queen.weights))</span>
<span id="cb556-2"><a href="global-spatial-autocorrelation-1.html#cb556-2" aria-hidden="true" tabindex="-1"></a>moran<span class="sc">$</span>I</span></code></pre></div>
<pre><code>## [1] 0.2810649</code></pre>
<p>We get a value of .281, which is the Moran’s I statistic, which also
corresponds to the slope of the Moran’s I scatter plot.</p>
<p>In creating the Moran’s I scatterplot, we will need to to create a lag variable of sale price from
our queen weights. This is just done with the function <code>lag.listw</code>, which takes a weights structure
and a variable of equal length to create a lag variable from.</p>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="global-spatial-autocorrelation-1.html#cb558-1" aria-hidden="true" tabindex="-1"></a>clev.points<span class="sc">$</span>lagged_sale_price <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights,clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb558-2"><a href="global-spatial-autocorrelation-1.html#cb558-2" aria-hidden="true" tabindex="-1"></a>clev.points<span class="sc">$</span>lagged_sale_price</span></code></pre></div>
<pre><code>##   [1]  83287.500 112912.500  80178.571 108550.000  58375.000  96816.667
##   [7] 115600.000  41503.571  59732.143  80025.000  48785.714 110750.000
##  [13] 103000.000  72300.000 113050.000 141918.167 112900.000  55142.857
##  [19] 140594.143  88871.429 213734.833 176844.143 201950.000 134800.000
##  [25]  67350.000  46371.375  88125.000 137600.000 107625.000  28357.143
##  [31]  26218.750   9025.000  18291.667  25950.000   7002.667  41863.300
##  [37]  28187.500  17300.000  10250.000  25333.333  18418.750  21437.500
##  [43]  26430.000  20771.000  60539.000  43412.500 102080.375  24936.667
##  [49]  29619.143  28094.200  16657.000  18691.500  22193.625  21575.667
##  [55]  17804.571 128700.000  35710.400  45935.250  36411.500  42500.000
##  [61]  82133.333  71680.000  81100.000  55733.333  69066.667  66600.000
##  [67]  39300.000  59750.000  58000.000  48625.000  45593.750  15441.667
##  [73]  47174.750  33416.667  35150.000  34083.500  51762.500  36304.750
##  [79]  31783.600  12908.000  14676.600  15166.667  22483.333  19541.667
##  [85]  20426.600  21100.000  36212.000  20900.000  32775.000  29946.600
##  [91]  44350.333  24431.286  21279.750  62380.000  21683.667  25914.900
##  [97]  42369.667   8481.000  10904.800  13657.000  13830.000  14412.250
## [103]  24264.143  14487.333  32960.571  12226.800   8708.500  12655.667
## [109]  15714.286  20383.333  21151.667  10258.571  18451.667 131651.500
## [115]  20420.000 182072.714 140650.000  22034.000  43550.000  53100.000
## [121]  41488.889  26500.000  13095.714   8764.444   9208.667   6156.667
## [127]  11761.333   5529.500   7409.600  40510.000  34388.286   9250.000
## [133]   9128.000  15470.000  12699.714  18842.000  14440.000  10125.000
## [139]  17967.500   9500.000  30250.000  17400.000  11174.000  13248.833
## [145]   9068.750  25633.333   7248.500  66900.000  62812.500  67125.000
## [151]  88250.000  28300.000  78900.000  71093.750   9750.000  14085.714
## [157]  12350.000  15216.667  25670.000  26750.000  57414.286  21920.000
## [163]  43500.000  16912.500  19062.500  15666.667  65044.444  20583.333
## [169]  11358.333  34816.667  34750.000  39360.000  29092.857  24422.222
## [175]  23360.000  42685.714  29080.000  16983.333  21666.667  31960.000
## [181]  24400.000   7242.857  16180.000  28216.667   9633.333  32742.857
## [187]  28833.333  21360.000  29391.667  24414.286  34720.000  14083.333
## [193]  14860.000  17916.667  23133.333  27850.000  18370.000  16975.000
## [199]  45980.000  36700.000  33583.333  29750.000  35416.667  28614.286
## [205]  22000.000</code></pre>
<p>We need standardized values for both the lag variable and the sale price variable
to build the Moran’I scatterplot. Standardized values are just z scores for each
observation(<span class="math inline">\(z_i =\frac{ x_i -\mu}{\sqrt{Var(x)}}\)</span>). To get the standardized values, we will use <code>standardize</code>
from the <strong>robustHD</strong> package. We could very easily calculate these with Base R
vectorized operations, but it is faster to just use a package function.</p>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="global-spatial-autocorrelation-1.html#cb560-1" aria-hidden="true" tabindex="-1"></a>clev.points<span class="sc">$</span>standardized_sale_price <span class="ot">&lt;-</span> <span class="fu">standardize</span>(clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb560-2"><a href="global-spatial-autocorrelation-1.html#cb560-2" aria-hidden="true" tabindex="-1"></a>clev.points<span class="sc">$</span>standardized_lag_sale_price <span class="ot">&lt;-</span> <span class="fu">standardize</span>(clev.points<span class="sc">$</span>lagged_sale_price)</span></code></pre></div>
<p>To construct the moran’s I scatterplot, we will use <strong>ggplot2</strong> for more aesthically
pleasing plots. We will not go into too much depth on the options available for
for these plots, but for more information, check out <a href="https://ggplot2.tidyverse.org/reference/index.html">ggplot2 documentation</a>. In addition, The first
Exploratory Data Analysis notebook is also a good resource to look at.</p>
<p>To make the Moran’s I scatterplot, we make a scatterplot in <strong>ggplot2</strong>
with the standardized sale price values as the x axis and the
standardized lag sale price variable as the y axis. We use <code>geom_point</code> to add the points to the plot. <code>geom_smooth</code> adds a regression line. The
default option is a loess smooth line, we specify the <code>method = lm</code> to get a standard linear regression line . We add dotted lines at the
x and y axis to separate the 4 types of spatial autocorrelation. We do this with
<code>geom_hline</code> for the x axis and <code>geom_vline</code> for the y axis. To get the speciifcations of
the scatterplot to better match up with GeoDa, we set the x and y scale limits to -10 and 10.</p>
<div class="sourceCode" id="cb561"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb561-1"><a href="global-spatial-autocorrelation-1.html#cb561-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> clev.points, <span class="fu">aes</span>(<span class="at">x=</span>standardized_sale_price, <span class="at">y =</span> standardized_lag_sale_price)) <span class="sc">+</span></span>
<span id="cb561-2"><a href="global-spatial-autocorrelation-1.html#cb561-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb561-3"><a href="global-spatial-autocorrelation-1.html#cb561-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb561-4"><a href="global-spatial-autocorrelation-1.html#cb561-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb561-5"><a href="global-spatial-autocorrelation-1.html#cb561-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb561-6"><a href="global-spatial-autocorrelation-1.html#cb561-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb561-7"><a href="global-spatial-autocorrelation-1.html#cb561-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>) <span class="sc">+</span> </span>
<span id="cb561-8"><a href="global-spatial-autocorrelation-1.html#cb561-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Moran scatter plot sale price&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-409-1.png" width="672" /></p>
<div id="interpretation" class="section level4 hasAnchor" number="10.2.2.1">
<h4><span class="header-section-number">10.2.2.1</span> Interpretation<a href="global-spatial-autocorrelation-1.html#interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can see that the shape of the point cloud is determined by the presence of
several outliers on the high end (e.g., larger than three standard deviational
units from the mean). One observation, with a sales price of 527,409 (compared to
the median sales prices of 20,000), is as large as 8 standard deviational units
above the mean. On the lower end of the spectrum (to the left of the dashed line
in the middle that represents the mean), there is much less spread in the house
prices, and those points end up bunched together. By eliminating some of the
outliers, one may be able to see more detail for the remaining observations, but
we will not pursue that here.</p>
</div>
<div id="assessing-significance" class="section level4 hasAnchor" number="10.2.2.2">
<h4><span class="header-section-number">10.2.2.2</span> Assessing significance<a href="global-spatial-autocorrelation-1.html#assessing-significance" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have an estimate of the Moran’s I statistic, but no information on the significance
of that statistic. This can be obtained by constructing a distribution by means of
random assignment. In order to do this, we first choose the number of permutations desired,
which will directly affect the minimum pseudo p-value we can obtain for the test statistic.
In the case of 999 permutation the minimum p-value would be .001, which would mean none
of the sample distribution statistics are as extreme or more extreme than the test statistic.</p>
<div id="replicability---the-random-seed" class="section level5 hasAnchor" number="10.2.2.2.1">
<h5><span class="header-section-number">10.2.2.2.1</span> Replicability - the random seed<a href="global-spatial-autocorrelation-1.html#replicability---the-random-seed" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>To faciliate replication, it is best to set a seed for the random number generator. The one
used in GeoDa is 123456789, so we will demonstrate how to set the seed here. It is just
<code>set.seed</code> and the desired seed number as an input.</p>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="global-spatial-autocorrelation-1.html#cb562-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123456789</span>)</span></code></pre></div>
</div>
</div>
<div id="reference-distribution" class="section level4 hasAnchor" number="10.2.2.3">
<h4><span class="header-section-number">10.2.2.3</span> Reference distribution<a href="global-spatial-autocorrelation-1.html#reference-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To make the reference distribution, we
will need to draw 999 randomized samples of the housing point data of the same
size as the number of observations in the housing point data. This random
sample will allow us to assign the values to random locations, which will give
us a spatially random distribution. To get to this point, we will build up in steps
in order to better understand the process.</p>
<p>We start by taking one random sample of our points with the base R <code>sample</code>
function. We choose the same size as the number of sale price data observations
to make a spatially randomized vector of our sale price data. The point of this is to randomly
assign the housing prices to the voronoi polygons, then to compute the Moran’s I
statistic for the spatially random assignment based off the original weights structure.</p>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="global-spatial-autocorrelation-1.html#cb563-1" aria-hidden="true" tabindex="-1"></a>draw <span class="ot">&lt;-</span> <span class="fu">sample</span>(clev.points<span class="sc">$</span>sale_price, <span class="at">size =</span> <span class="fu">length</span>(clev.points<span class="sc">$</span>sale_price))</span>
<span id="cb563-2"><a href="global-spatial-autocorrelation-1.html#cb563-2" aria-hidden="true" tabindex="-1"></a>draw</span></code></pre></div>
<pre><code>##   [1]  28000  82500  14500 135000  29150  13000  25250  34750  30000  14000
##  [11]   3500  45000  76000   8000  25000  14500  15000   7500   5000  26400
##  [21]  40000  65000  25750  15000   5800   4924   9000  41000  65000 527409
##  [31]  29900   5968  11000  33500   6800  64000  41500  21199   8000  15000
##  [41]  47000   7900   8400   8000  16000  20000   9000  15500   4149  17500
##  [51]  22000  19000  27600  72900   5200   4775   4500   9500  32500   5000
##  [61] 122500   7000  26000   2910 138500 165000   2500  92000  15000  40000
##  [71]  75000  32500   5000   7000  11750  20000  49000  41069  49000  15000
##  [81]   6370  15000  26000  38200  15000  85000  62000 120000  65000  70000
##  [91]  25000  84900  65000  28500   1300   6483 155000  73400  13000   4000
## [101] 305000 230000  11750 100000  15000  21119  75000  42000  20000   3000
## [111]  76000  12000  20000  11500   5000  10000  25750 116250  13100   7000
## [121]  48000  16000  10000   1448  29000 167000   5000  25000   8500   6300
## [131]   8600  27750 235500  81500  78000 228000  69000   3000  32500  20000
## [141]   4250 169500  10000  10000   8000 109900  20000  19000   7000  56900
## [151]  47000 103000   1049   5500  10500  26000  25000 125000  23000  24900
## [161]  48500  13000  16500   5500  17000  11500  10000  12000  45900  51000
## [171] 131650  24800  11582   6375  73000  11750  16900 172500   7000   2100
## [181]  48500  16500  15000  42500 275000  18000  15834  89500   6500  27000
## [191]   8000  23500   5000  48900   5000  19971  63000  10000  72000  38500
## [201]   7000  12000  68900  34000   5000</code></pre>
<p>Now we can begin to calculate the Moran’s I statistic by first calculating the
spatial lag variable based on our queen weights and the spatially random sample.</p>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="global-spatial-autocorrelation-1.html#cb565-1" aria-hidden="true" tabindex="-1"></a>lag1 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights,draw)</span></code></pre></div>
<p>We can get the Moran’s I statistic by regressing the standardized values of
the spatial lag variable on the standardized values of the random draw. We
can get the standardized value with the <code>standardize</code> function. The <code>summary</code>
function allows us to see a summary of the regression statistics.</p>
<div class="sourceCode" id="cb566"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb566-1"><a href="global-spatial-autocorrelation-1.html#cb566-1" aria-hidden="true" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">standardize</span>(lag1) <span class="sc">~</span> <span class="fu">standardize</span>(draw))</span>
<span id="cb566-2"><a href="global-spatial-autocorrelation-1.html#cb566-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = standardize(lag1) ~ standardize(draw))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.2872 -0.6826 -0.2114  0.3316  4.4708 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)       -1.236e-16  6.997e-02   0.000    1.000
## standardize(draw)  3.735e-02  7.014e-02   0.532    0.595
## 
## Residual standard error: 1.002 on 203 degrees of freedom
## Multiple R-squared:  0.001395,   Adjusted R-squared:  -0.003525 
## F-statistic: 0.2835 on 1 and 203 DF,  p-value: 0.595</code></pre>
<p>The slope here is the estimate for <strong>standardize(draw)</strong>. This value is fairly
close to zero as the randomization process makes makes the draw spatially random.</p>
<p>To build our distribution, we will need to repeat this process many times over.
We can accomplish this by way of a <code>for</code> loop. We will need somewhere to store
our Moran’s I result for each iteration. To do this we will make an empty
vector of a length corresponding to our desired number of permutations.</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb568-1"><a href="global-spatial-autocorrelation-1.html#cb568-1" aria-hidden="true" tabindex="-1"></a>randomized_moran <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">999</span>)</span></code></pre></div>
<p>The process here is the same as the one followed for one draw, but here we use the
<code>for</code> loop to get 999 iterations and store the resulting Moran’s I values in the vector
that we created above. First we do the random sample with the <code>sample</code> function.
Then we make a lag variable based upon the random draw and our queen weights. Next
we run the regression with the <code>lm</code> function between the stanardized values
of the lag variable and random draw variable. Lastly, we extract the slope
coefficient which is our Moran’s I statistic and store it in index i. Each
iteration of the loop will store the value at the subsequent index ie 1, then 2,
then 3, and so on.</p>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="global-spatial-autocorrelation-1.html#cb569-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>){</span>
<span id="cb569-2"><a href="global-spatial-autocorrelation-1.html#cb569-2" aria-hidden="true" tabindex="-1"></a>  draw <span class="ot">&lt;-</span> <span class="fu">sample</span>(clev.points<span class="sc">$</span>sale_price, <span class="at">size =</span> <span class="fu">length</span>(clev.points<span class="sc">$</span>sale_price))</span>
<span id="cb569-3"><a href="global-spatial-autocorrelation-1.html#cb569-3" aria-hidden="true" tabindex="-1"></a>  lag <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights,draw)</span>
<span id="cb569-4"><a href="global-spatial-autocorrelation-1.html#cb569-4" aria-hidden="true" tabindex="-1"></a>  lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">standardize</span>(lag) <span class="sc">~</span> <span class="fu">standardize</span>(draw))</span>
<span id="cb569-5"><a href="global-spatial-autocorrelation-1.html#cb569-5" aria-hidden="true" tabindex="-1"></a>  randomized_moran[i] <span class="ot">&lt;-</span> lmfit<span class="sc">$</span>coefficients[<span class="dv">2</span>] </span>
<span id="cb569-6"><a href="global-spatial-autocorrelation-1.html#cb569-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>We can obtain summary statistics of our distribution with <code>summary</code></p>
<div class="sourceCode" id="cb570"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb570-1"><a href="global-spatial-autocorrelation-1.html#cb570-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(randomized_moran)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -0.26210 -0.08531 -0.02554 -0.01655  0.04257  0.31351</code></pre>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="global-spatial-autocorrelation-1.html#cb572-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(randomized_moran)</span></code></pre></div>
<pre><code>## [1] 0.09375454</code></pre>
<p>Now to get the p value, we will check the number of samples that had higher Moran’s I
statistic than the observed value. To do this, we use the base R <code>which</code> function
to get a vector of the indices at which the conditional is TRUE. We then get the length
of the vector with <code>length</code>.</p>
<div class="sourceCode" id="cb574"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb574-1"><a href="global-spatial-autocorrelation-1.html#cb574-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(randomized_moran <span class="sc">&gt;</span> .<span class="dv">281</span>))</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>Since the result is 1, there is only 1 value in all of the permutations that is higher
than the test statistic. This means that the p value is .002, <span class="math inline">\(\frac{1 + R}{1 + M}\)</span>, where
R = 1 and M = 999.</p>
<p>There are a number of ways we can visualize the distribution that we just constructed
in R. We will use <strong>ggplot2</strong> to do these visualizations because it looks much
better than base R visualizations.</p>
<p>To start, we convert our vector with the randomized moran’s I values into a data frame,
so we can use <strong>ggplot2</strong> functions. For this, we just use the <code>data.frame</code> function with
the vector of randomized moran’s I values as an argument and then assign a name for the
column, which is just <code>moran</code> in this case.</p>
<p>The first option is a density plot. This requires the standard <code>ggplot</code> function with
<code>aes</code> containing the x axis. Additionally we need <code>geom_density</code>. We use <code>geom_vline</code>
to plot the mean of the distribution and our observed statistic.</p>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb576-1"><a href="global-spatial-autocorrelation-1.html#cb576-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">moran =</span> randomized_moran)</span>
<span id="cb576-2"><a href="global-spatial-autocorrelation-1.html#cb576-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df,<span class="fu">aes</span>(<span class="at">x=</span>moran)) <span class="sc">+</span></span>
<span id="cb576-3"><a href="global-spatial-autocorrelation-1.html#cb576-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb576-4"><a href="global-spatial-autocorrelation-1.html#cb576-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> moran[[<span class="dv">1</span>]], <span class="at">col =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span></span>
<span id="cb576-5"><a href="global-spatial-autocorrelation-1.html#cb576-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(randomized_moran), <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-419-1.png" width="672" /></p>
<p>The next option is a histogram. The only difference here is that we use <code>geom_histogram</code>
instead of `geom_density.</p>
<div class="sourceCode" id="cb577"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb577-1"><a href="global-spatial-autocorrelation-1.html#cb577-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x=</span>moran)) <span class="sc">+</span></span>
<span id="cb577-2"><a href="global-spatial-autocorrelation-1.html#cb577-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb577-3"><a href="global-spatial-autocorrelation-1.html#cb577-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> moran[[<span class="dv">1</span>]], <span class="at">col =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span></span>
<span id="cb577-4"><a href="global-spatial-autocorrelation-1.html#cb577-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(randomized_moran), <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-420-1.png" width="672" />
#### LOWESS smoother</p>
<p>The LOWESS smoother is not implemented directly in <strong>ggplot2</strong>, but can be found in an
add-on package. We use the <strong>Hmisc</strong> package to add this functionality to the
<strong>ggplot2</strong> plots. To add the smoother to our Moran’s I scatter plot, we use the
<code>stat_plsmo</code> from the <strong>Hmisc</strong> package. The default span for GeoDa is .2 so we will
set the <code>span =</code> parameter to .2.</p>
<p>With the LOWESS smoother, we can see potential structural breaks in the pattern of
spatial autocorrelation. For example some parts of the data, the curve may be very steep,
and positive, indicating strong spatial autocorrelation, whereas in other parts, it
could be flat, indicating no spatial autocorrelation.</p>
<div class="sourceCode" id="cb578"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb578-1"><a href="global-spatial-autocorrelation-1.html#cb578-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> clev.points, <span class="fu">aes</span>(<span class="at">x=</span>standardized_sale_price, <span class="at">y =</span> standardized_lag_sale_price)) <span class="sc">+</span></span>
<span id="cb578-2"><a href="global-spatial-autocorrelation-1.html#cb578-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb578-3"><a href="global-spatial-autocorrelation-1.html#cb578-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_plsmo</span>(<span class="at">span =</span> .<span class="dv">2</span>, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb578-4"><a href="global-spatial-autocorrelation-1.html#cb578-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb578-5"><a href="global-spatial-autocorrelation-1.html#cb578-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb578-6"><a href="global-spatial-autocorrelation-1.html#cb578-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb578-7"><a href="global-spatial-autocorrelation-1.html#cb578-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>) <span class="sc">+</span> </span>
<span id="cb578-8"><a href="global-spatial-autocorrelation-1.html#cb578-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;LOWESS smooth of Moran Scatterplot&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-421-1.png" width="672" /></p>
</div>
<div id="chow-test-morans-i-scatterplot" class="section level4 hasAnchor" number="10.2.2.4">
<h4><span class="header-section-number">10.2.2.4</span> Chow test Moran’s I scatterplot<a href="global-spatial-autocorrelation-1.html#chow-test-morans-i-scatterplot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Chow test is a statistical test of whether or not the coeffiecients of two
different linear regressions are equal. In the case of the Moran’s I scatterplot,
it is just the slope of the regression line and the intercepts, since it is a simple
linear regression.</p>
<p>The brushing operation in GeoDa is fairly difficult to implement in R, but we can
do a less interactive version. First we must consider which criteria we want to
select points on. This could be anything from its location to other characteristics
in the data. In our case we will do it based on location. As an approximation for the
midpoint of the set of points, we take the the mean of the x and y coordinates.
From there we assign “Select” to the points in the bottom left quadrant and “Rest”
to the rest of the points by way of the <code>if_else</code> function. This function takes
a conditional, a result to assign in the case where the conditional is TRUE, and
a result to assign when the conditional is FALSE. In our case it is “Select” and
“Rest”.</p>
<div class="sourceCode" id="cb579"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb579-1"><a href="global-spatial-autocorrelation-1.html#cb579-1" aria-hidden="true" tabindex="-1"></a>mid_x <span class="ot">&lt;-</span> <span class="fu">mean</span>(clev.points<span class="sc">$</span>x)</span>
<span id="cb579-2"><a href="global-spatial-autocorrelation-1.html#cb579-2" aria-hidden="true" tabindex="-1"></a>mid_y <span class="ot">&lt;-</span> <span class="fu">mean</span>(clev.points<span class="sc">$</span>y)</span>
<span id="cb579-3"><a href="global-spatial-autocorrelation-1.html#cb579-3" aria-hidden="true" tabindex="-1"></a>clev.points<span class="ot">&lt;-</span> clev.points <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">bottom_left =</span> <span class="fu">if_else</span>((x <span class="sc">&lt;</span> mid_x <span class="sc">&amp;</span> y <span class="sc">&lt;</span> mid_y),<span class="st">&quot;Select&quot;</span>, <span class="st">&quot;Rest&quot;</span>))</span></code></pre></div>
<p>Before we run the chow test, we will visualize the difference in slopes of the selected data, non-selected
data and the aggregate data. With <strong>ggplot2</strong>, we can accomplish this by setting categorical colors based
whether or not an observation is “Selected” or “Rest”. To do this, we specify <code>aes(color = bottom_left)</code> in
both <code>geom_point</code> and <code>geom_smooth</code>. This will give us colored points and regression lines for “Selected”
and “Rest”. Then to get blue and red colors, we use <code>scale_color_manual</code>. For this plot, we do not set
x and y limits because the -10 to 10 speciifcation is too dificult to see the differences in the regression
lines.</p>
<div class="sourceCode" id="cb580"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb580-1"><a href="global-spatial-autocorrelation-1.html#cb580-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(clev.points, <span class="fu">aes</span>(<span class="at">x=</span>standardized_sale_price,<span class="at">y=</span>standardized_lag_sale_price)) <span class="sc">+</span></span>
<span id="cb580-2"><a href="global-spatial-autocorrelation-1.html#cb580-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>bottom_left)) <span class="sc">+</span></span>
<span id="cb580-3"><a href="global-spatial-autocorrelation-1.html#cb580-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">color=</span>bottom_left), <span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb580-4"><a href="global-spatial-autocorrelation-1.html#cb580-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm,<span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb580-5"><a href="global-spatial-autocorrelation-1.html#cb580-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;red&quot;</span>))  <span class="sc">+</span></span>
<span id="cb580-6"><a href="global-spatial-autocorrelation-1.html#cb580-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color=</span><span class="st">&quot;Selection&quot;</span>) <span class="sc">+</span></span>
<span id="cb580-7"><a href="global-spatial-autocorrelation-1.html#cb580-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb580-8"><a href="global-spatial-autocorrelation-1.html#cb580-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb580-9"><a href="global-spatial-autocorrelation-1.html#cb580-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Chow test Moran Scatterplot&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-423-1.png" width="672" /></p>
<p>To perform the chow test, we need two separate data frames as inputs for the function. To get the
two data frames, we use the <strong>tidyverse</strong> <code>filter</code> function. This function filter out observations
based on a conditional. TRUE values for the conditional remain in the data frame while FALSE values are
filtered out.</p>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="global-spatial-autocorrelation-1.html#cb581-1" aria-hidden="true" tabindex="-1"></a>clev.select <span class="ot">&lt;-</span> clev.points <span class="sc">%&gt;%</span> <span class="fu">filter</span>(bottom_left <span class="sc">==</span> <span class="st">&quot;Select&quot;</span>)</span>
<span id="cb581-2"><a href="global-spatial-autocorrelation-1.html#cb581-2" aria-hidden="true" tabindex="-1"></a>clev.rest <span class="ot">&lt;-</span> clev.points <span class="sc">%&gt;%</span> <span class="fu">filter</span>(bottom_left <span class="sc">==</span> <span class="st">&quot;Rest&quot;</span>)</span></code></pre></div>
<p>Now we use the base R <code>lm</code> function to run separate regressions on the standardized lag variable and
standardized sale price variable.</p>
<div class="sourceCode" id="cb582"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb582-1"><a href="global-spatial-autocorrelation-1.html#cb582-1" aria-hidden="true" tabindex="-1"></a>reg.select <span class="ot">&lt;-</span> <span class="fu">lm</span>(standardized_lag_sale_price<span class="sc">~</span>standardized_sale_price, <span class="at">data=</span>clev.select)</span>
<span id="cb582-2"><a href="global-spatial-autocorrelation-1.html#cb582-2" aria-hidden="true" tabindex="-1"></a>reg.rest <span class="ot">&lt;-</span> <span class="fu">lm</span>(standardized_lag_sale_price<span class="sc">~</span>standardized_sale_price, <span class="at">data=</span>clev.rest)</span></code></pre></div>
<p>Now we use the <code>summary</code> function on each regression object to get summary statistics of the residuals,
the regression coefficients and and their respective standard errors, the R squared values, and the
F statistic.</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="global-spatial-autocorrelation-1.html#cb583-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg.select)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = standardized_lag_sale_price ~ standardized_sale_price, 
##     data = clev.select)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.32083 -0.26382 -0.08486  0.25641  2.38954 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             -0.15667    0.06062  -2.584   0.0117 *  
## standardized_sale_price  0.51228    0.11818   4.335 4.53e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.492 on 74 degrees of freedom
## Multiple R-squared:  0.2025, Adjusted R-squared:  0.1917 
## F-statistic: 18.79 on 1 and 74 DF,  p-value: 4.534e-05</code></pre>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="global-spatial-autocorrelation-1.html#cb585-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg.rest)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = standardized_lag_sale_price ~ standardized_sale_price, 
##     data = clev.rest)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.2276 -0.6161 -0.3336  0.2146  4.5370 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              0.10241    0.09335   1.097    0.275    
## standardized_sale_price  0.42072    0.07816   5.383 3.42e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.056 on 127 degrees of freedom
## Multiple R-squared:  0.1858, Adjusted R-squared:  0.1793 
## F-statistic: 28.97 on 1 and 127 DF,  p-value: 3.418e-07</code></pre>
<p>We see that the slopes vary by about .08 and the intercepts vary by .25</p>
<p>To run the chow test, we need 4 inputs for <code>chow.test</code>. We need the two standardized
variables from the the “Select” data frame: <strong>clev.select</strong> and the two standardized
variables from the the “Rest” data frame: <strong>clev.rest</strong>.</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="global-spatial-autocorrelation-1.html#cb587-1" aria-hidden="true" tabindex="-1"></a>chow <span class="ot">&lt;-</span> <span class="fu">chow.test</span>(clev.select<span class="sc">$</span>standardized_lag_sale_price, clev.select<span class="sc">$</span>standardized_sale_price, clev.rest<span class="sc">$</span>standardized_lag_sale_price, clev.rest<span class="sc">$</span>standardized_sale_price)</span>
<span id="cb587-2"><a href="global-spatial-autocorrelation-1.html#cb587-2" aria-hidden="true" tabindex="-1"></a>chow</span></code></pre></div>
<pre><code>##     F value       d.f.1       d.f.2     P value 
##   2.2974700   2.0000000 201.0000000   0.1031467</code></pre>
<p>With a p-value of .103 we do not have significant evidence to conclude that the slopes of the
two regressions are different under a standard alpha level of .05.</p>
</div>
</div>
</div>
<div id="spatial-correlogram" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Spatial Correlogram<a href="global-spatial-autocorrelation-1.html#spatial-correlogram" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="concept-2" class="section level3 hasAnchor" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> Concept<a href="global-spatial-autocorrelation-1.html#concept-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A non-parametric spatial correlogram is an alternative measure of global spatial
autocorrelation that does not rely on the specification of a spatial weights
matrix. Instead, a local regression is fit to the covariances or correlations
computed for all pairs of observations as a function of the distance between them
(for example, as outlined in Bjornstad and Falck 2001).</p>
<p>With standardized variables z, this boils down to a local regression:</p>
<p><span class="math display">\[z_iz_j = f(d_{ij}) + u\]</span></p>
<p>where <span class="math inline">\(d_{ij}\)</span> is the distance between a pair of locations i - j, u is an
error term and f is a non-parametric function to be determined from the data.
Typically, the latter is a LOWESS or kernel regression.</p>
</div>
<div id="creating-a-spatial-correlogram" class="section level3 hasAnchor" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> Creating a spatial correlogram<a href="global-spatial-autocorrelation-1.html#creating-a-spatial-correlogram" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In GeoDa, creating a spatial correlogram is much more straight forward than
in R. The process in r requires us to start with the sale price points, then to
create a neighbors structure base on the distance breaks desired for the
correlogram.</p>
<p>To start, we use <code>cbind</code> to put the x and y coordinates together for use in
the distance based neighbor functions of <strong>spdep</strong>.</p>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="global-spatial-autocorrelation-1.html#cb589-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(clev.points<span class="sc">$</span>x, clev.points<span class="sc">$</span>y)</span></code></pre></div>
<p>Now we create distance based neighbors coordinate matrix and lower distance bound and an upper distance bound, which is used to define neighbors. We use <code>dnearneigh</code> to create
the distance band neighbors. For more in depth information on distance based neighbors,
please see the Disatnce Based Weights notebook. We use a distance of 4823.27 to emulate
the first example in the GeoDa workbook.</p>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb590-1"><a href="global-spatial-autocorrelation-1.html#cb590-1" aria-hidden="true" tabindex="-1"></a>dist.band.nb <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords,<span class="dv">0</span>,<span class="fl">4823.27</span>)</span></code></pre></div>
<p>Using the <strong>spdep</strong> function `sp.correlogram, we can get measures of spatial autocorrelation
for an input number of lag orders. We can then use the base R plotting function to get a look
at the autocorrelation values for each lag order.</p>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb591-1"><a href="global-spatial-autocorrelation-1.html#cb591-1" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">sp.correlogram</span>(dist.band.nb, clev.points<span class="sc">$</span>sale_price, <span class="at">order =</span> <span class="dv">10</span>, <span class="at">method =</span> <span class="st">&quot;I&quot;</span>,<span class="at">style =</span> <span class="st">&quot;W&quot;</span>, <span class="at">randomisation =</span> <span class="cn">TRUE</span>, <span class="at">spChk =</span> <span class="cn">NULL</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb591-2"><a href="global-spatial-autocorrelation-1.html#cb591-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sp)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-431-1.png" width="672" /></p>
<p>To get a better looking plot, we can extract the moran’s I values and put
them into a data frame, so we can use <strong>ggplot2</strong> plotting functionality.</p>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="global-spatial-autocorrelation-1.html#cb592-1" aria-hidden="true" tabindex="-1"></a>morans <span class="ot">&lt;-</span> sp<span class="sc">$</span>res[,<span class="dv">1</span>]</span>
<span id="cb592-2"><a href="global-spatial-autocorrelation-1.html#cb592-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Morans_I =</span> morans,<span class="at">lags =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span> )</span>
<span id="cb592-3"><a href="global-spatial-autocorrelation-1.html#cb592-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x=</span>lags,<span class="at">y=</span>Morans_I)) <span class="sc">+</span></span>
<span id="cb592-4"><a href="global-spatial-autocorrelation-1.html#cb592-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb592-5"><a href="global-spatial-autocorrelation-1.html#cb592-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb592-6"><a href="global-spatial-autocorrelation-1.html#cb592-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb592-7"><a href="global-spatial-autocorrelation-1.html#cb592-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span>.<span class="dv">5</span>,.<span class="dv">5</span>) </span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-432-1.png" width="672" /></p>
<p>To get closer to the GeoDa correlogram plotting functionality, we can convert lags to
euclidean distance.</p>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb593-1"><a href="global-spatial-autocorrelation-1.html#cb593-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>euclidean_distance <span class="ot">&lt;-</span> df<span class="sc">$</span>lags <span class="sc">*</span> <span class="fl">4823.3</span></span>
<span id="cb593-2"><a href="global-spatial-autocorrelation-1.html#cb593-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x=</span>euclidean_distance,<span class="at">y=</span>Morans_I)) <span class="sc">+</span></span>
<span id="cb593-3"><a href="global-spatial-autocorrelation-1.html#cb593-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb593-4"><a href="global-spatial-autocorrelation-1.html#cb593-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb593-5"><a href="global-spatial-autocorrelation-1.html#cb593-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb593-6"><a href="global-spatial-autocorrelation-1.html#cb593-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span>.<span class="dv">5</span>,.<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb593-7"><a href="global-spatial-autocorrelation-1.html#cb593-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> df<span class="sc">$</span>euclidean_distance)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-433-1.png" width="672" /></p>
<p>The spatial correlogram can be paired with a bar chart that shows the number of
neighbor pairs for each lag order. To get this information, we will need to work
outside the <strong>spdep</strong> package and compute them ourselves.</p>
<p>To begin, we set up an empty vector to store the pair numbers.</p>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="global-spatial-autocorrelation-1.html#cb594-1" aria-hidden="true" tabindex="-1"></a>pairs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10</span>)</span></code></pre></div>
<p>Here we run <code>dnearneigh</code> on each interval of euclidean distance that corresponds to a lag in
1 to 10. To get the number of pairs for each lag order, we simply sum up the cardinality
of the neighbor structure per each lag order and then divide it by two because this sum gives the
total number of neighbors and the total number of pairs will be half this number.</p>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="global-spatial-autocorrelation-1.html#cb595-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>){</span>
<span id="cb595-2"><a href="global-spatial-autocorrelation-1.html#cb595-2" aria-hidden="true" tabindex="-1"></a>  nb <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, (i <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">4823.28</span>, i <span class="sc">*</span> <span class="fl">4823.28</span>)</span>
<span id="cb595-3"><a href="global-spatial-autocorrelation-1.html#cb595-3" aria-hidden="true" tabindex="-1"></a>  pairs[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">card</span>(nb)) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb595-4"><a href="global-spatial-autocorrelation-1.html#cb595-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Now we create a data frame from the two vectors we create with the lag order values and
associated euclidean distance values.</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="global-spatial-autocorrelation-1.html#cb596-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">lag_order =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">auto_corr =</span> morans, <span class="at">num_pairs =</span> pairs)</span>
<span id="cb596-2"><a href="global-spatial-autocorrelation-1.html#cb596-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>euclidean_distance <span class="ot">&lt;-</span> df<span class="sc">$</span>lag_order <span class="sc">*</span> <span class="dv">4823</span></span></code></pre></div>
<p>Here we create two different plots, one is a histogram with the number of pairs in each bin, the other
is the spatial correlogram</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb597-1"><a href="global-spatial-autocorrelation-1.html#cb597-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> euclidean_distance,<span class="at">y =</span> auto_corr)) <span class="sc">+</span></span>
<span id="cb597-2"><a href="global-spatial-autocorrelation-1.html#cb597-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb597-3"><a href="global-spatial-autocorrelation-1.html#cb597-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb597-4"><a href="global-spatial-autocorrelation-1.html#cb597-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb597-5"><a href="global-spatial-autocorrelation-1.html#cb597-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb597-6"><a href="global-spatial-autocorrelation-1.html#cb597-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> df<span class="sc">$</span>euclidean_distance)</span>
<span id="cb597-7"><a href="global-spatial-autocorrelation-1.html#cb597-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x=</span>euclidean_distance,<span class="at">y =</span> num_pairs, <span class="at">fill =</span> <span class="fu">as.factor</span>(euclidean_distance))) <span class="sc">+</span></span>
<span id="cb597-8"><a href="global-spatial-autocorrelation-1.html#cb597-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb597-9"><a href="global-spatial-autocorrelation-1.html#cb597-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Paired&quot;</span>) <span class="sc">+</span></span>
<span id="cb597-10"><a href="global-spatial-autocorrelation-1.html#cb597-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb597-11"><a href="global-spatial-autocorrelation-1.html#cb597-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>num_pairs), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> .<span class="dv">9</span>), <span class="at">vjust=</span><span class="sc">-</span>.<span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb597-12"><a href="global-spatial-autocorrelation-1.html#cb597-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fl">1.2</span> <span class="sc">*</span> <span class="fu">max</span>(pairs)) <span class="sc">+</span></span>
<span id="cb597-13"><a href="global-spatial-autocorrelation-1.html#cb597-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> df<span class="sc">$</span>euclidean_distance)</span>
<span id="cb597-14"><a href="global-spatial-autocorrelation-1.html#cb597-14" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-437-1.png" width="672" /></p>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="global-spatial-autocorrelation-1.html#cb598-1" aria-hidden="true" tabindex="-1"></a>p2</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-437-2.png" width="672" /></p>
<p>Using <code>grid.arrange</code> from the <strong>gridExtra</strong> package, we can combine the two plots into one
image.</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="global-spatial-autocorrelation-1.html#cb599-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1,p2,<span class="at">ncol =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-438-1.png" width="672" /></p>
<p>Following the same process outlined above, we can make a function that constructs the correlogram
based on the desired lag order, distance band, variable, and coordinates.</p>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="global-spatial-autocorrelation-1.html#cb600-1" aria-hidden="true" tabindex="-1"></a>geoda_correlogram <span class="ot">&lt;-</span> <span class="cf">function</span>(lag.order, distance, var,coords){</span>
<span id="cb600-2"><a href="global-spatial-autocorrelation-1.html#cb600-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Funtion that outputs a spatial correlogram with a bar plot of neighbor pairs</span></span>
<span id="cb600-3"><a href="global-spatial-autocorrelation-1.html#cb600-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Inputs:</span></span>
<span id="cb600-4"><a href="global-spatial-autocorrelation-1.html#cb600-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#        lag.order: The desired number of lag orders to be included in the plot</span></span>
<span id="cb600-5"><a href="global-spatial-autocorrelation-1.html#cb600-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#        distance: The desired distance band for the lags</span></span>
<span id="cb600-6"><a href="global-spatial-autocorrelation-1.html#cb600-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#        var: A variable to analyze the spatial autocorelation</span></span>
<span id="cb600-7"><a href="global-spatial-autocorrelation-1.html#cb600-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#        coords: A matrix of coordinates of the same length as var</span></span>
<span id="cb600-8"><a href="global-spatial-autocorrelation-1.html#cb600-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># creating vectors to store autocorrelation values and number of pairs</span></span>
<span id="cb600-9"><a href="global-spatial-autocorrelation-1.html#cb600-9" aria-hidden="true" tabindex="-1"></a>  pairs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, lag.order)</span>
<span id="cb600-10"><a href="global-spatial-autocorrelation-1.html#cb600-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb600-11"><a href="global-spatial-autocorrelation-1.html#cb600-11" aria-hidden="true" tabindex="-1"></a>  <span class="co">#loop to calculate number of pairs for each lag order</span></span>
<span id="cb600-12"><a href="global-spatial-autocorrelation-1.html#cb600-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>lag.order) {</span>
<span id="cb600-13"><a href="global-spatial-autocorrelation-1.html#cb600-13" aria-hidden="true" tabindex="-1"></a>    nb <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, (i<span class="dv">-1</span>) <span class="sc">*</span> distance, i <span class="sc">*</span> distance)</span>
<span id="cb600-14"><a href="global-spatial-autocorrelation-1.html#cb600-14" aria-hidden="true" tabindex="-1"></a>    pairs[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">card</span>(nb)) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb600-15"><a href="global-spatial-autocorrelation-1.html#cb600-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb600-16"><a href="global-spatial-autocorrelation-1.html#cb600-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb600-17"><a href="global-spatial-autocorrelation-1.html#cb600-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Computing spatial autocorrelation</span></span>
<span id="cb600-18"><a href="global-spatial-autocorrelation-1.html#cb600-18" aria-hidden="true" tabindex="-1"></a>  nb1 <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, <span class="dv">0</span> , distance)</span>
<span id="cb600-19"><a href="global-spatial-autocorrelation-1.html#cb600-19" aria-hidden="true" tabindex="-1"></a>  sp <span class="ot">&lt;-</span> <span class="fu">sp.correlogram</span>(nb1, var, <span class="at">order =</span> lag.order, <span class="at">method =</span> <span class="st">&quot;I&quot;</span>, <span class="at">style =</span> <span class="st">&quot;W&quot;</span>, <span class="at">randomisation =</span> <span class="cn">FALSE</span>, <span class="at">spChk =</span> <span class="cn">NULL</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb600-20"><a href="global-spatial-autocorrelation-1.html#cb600-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb600-21"><a href="global-spatial-autocorrelation-1.html#cb600-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Putting the lag orders, autocorrelation, pairs and distance into a dataframe</span></span>
<span id="cb600-22"><a href="global-spatial-autocorrelation-1.html#cb600-22" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">lag =</span> <span class="dv">1</span><span class="sc">:</span>lag.order, <span class="at">num_pairs =</span> pairs, <span class="at">auto_corr =</span> sp<span class="sc">$</span>res[,<span class="dv">1</span>])</span>
<span id="cb600-23"><a href="global-spatial-autocorrelation-1.html#cb600-23" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>euclidean_distance <span class="ot">&lt;-</span> df<span class="sc">$</span>lag <span class="sc">*</span> <span class="fu">round</span>(distance, <span class="at">digits =</span> <span class="dv">0</span>)</span>
<span id="cb600-24"><a href="global-spatial-autocorrelation-1.html#cb600-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb600-25"><a href="global-spatial-autocorrelation-1.html#cb600-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Making plots</span></span>
<span id="cb600-26"><a href="global-spatial-autocorrelation-1.html#cb600-26" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> euclidean_distance,<span class="at">y =</span> auto_corr)) <span class="sc">+</span></span>
<span id="cb600-27"><a href="global-spatial-autocorrelation-1.html#cb600-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb600-28"><a href="global-spatial-autocorrelation-1.html#cb600-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb600-29"><a href="global-spatial-autocorrelation-1.html#cb600-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb600-30"><a href="global-spatial-autocorrelation-1.html#cb600-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)  <span class="sc">+</span></span>
<span id="cb600-31"><a href="global-spatial-autocorrelation-1.html#cb600-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> df<span class="sc">$</span>euclidean_distance)</span>
<span id="cb600-32"><a href="global-spatial-autocorrelation-1.html#cb600-32" aria-hidden="true" tabindex="-1"></a>  p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x=</span>euclidean_distance,<span class="at">y=</span>num_pairs, <span class="at">fill =</span> <span class="fu">as.factor</span>(euclidean_distance))) <span class="sc">+</span></span>
<span id="cb600-33"><a href="global-spatial-autocorrelation-1.html#cb600-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat=</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb600-34"><a href="global-spatial-autocorrelation-1.html#cb600-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Paired&quot;</span>) <span class="sc">+</span></span>
<span id="cb600-35"><a href="global-spatial-autocorrelation-1.html#cb600-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb600-36"><a href="global-spatial-autocorrelation-1.html#cb600-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>num_pairs), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> .<span class="dv">9</span>), <span class="at">vjust=</span><span class="sc">-</span>.<span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb600-37"><a href="global-spatial-autocorrelation-1.html#cb600-37" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fl">1.2</span> <span class="sc">*</span> <span class="fu">max</span>(pairs)) <span class="sc">+</span></span>
<span id="cb600-38"><a href="global-spatial-autocorrelation-1.html#cb600-38" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> df<span class="sc">$</span>euclidean_distance)</span>
<span id="cb600-39"><a href="global-spatial-autocorrelation-1.html#cb600-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">grid.arrange</span>(p1,p2,<span class="at">ncol =</span><span class="dv">1</span>)</span>
<span id="cb600-40"><a href="global-spatial-autocorrelation-1.html#cb600-40" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb600-41"><a href="global-spatial-autocorrelation-1.html#cb600-41" aria-hidden="true" tabindex="-1"></a><span class="fu">geoda_correlogram</span>(<span class="dv">10</span>, <span class="fl">4823.3</span>, clev.points<span class="sc">$</span>sale_price, coords)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-439-1.png" width="672" /></p>
</div>
<div id="interpretation-1" class="section level3 hasAnchor" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> Interpretation<a href="global-spatial-autocorrelation-1.html#interpretation-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The top of the above graph is the actual correlogram. This depicts how spatial autocorrelation
changes with distance. The first dot correpsonds with distances between 0 and 4823 feet.
The dashed line indicates a spatial autocorrelation of 0. The autocorrelation starts positive
and then fluctates above and below the dashed line.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="27">
<li id="fn27"><p>Use <code>setwd(directorypath)</code> to specify the working directory.<a href="global-spatial-autocorrelation-1.html#fnref27" class="footnote-back">↩︎</a></p></li>
<li id="fn28"><p>Use
<code>install.packages(packagename)</code>.<a href="global-spatial-autocorrelation-1.html#fnref28" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="applications-of-spatial-weights.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="global-spatial-autocorrelation-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/spatialanalysis/handsonspatialdata/edit/master/10-global-spatial-autocorrelation1.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
