<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Applications of Spatial Weights | Hands-On Spatial Data Science with R</title>
  <meta name="description" content="Chapter 9 Applications of Spatial Weights | Hands-On Spatial Data Science with R" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Applications of Spatial Weights | Hands-On Spatial Data Science with R" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="spatialanalysis/handsonspatialdata" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Applications of Spatial Weights | Hands-On Spatial Data Science with R" />
  
  
  

<meta name="author" content="Luc Anselin, Grant Morrison, Angela Li, Karina Acosta" />


<meta name="date" content="2023-10-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="spatial-weights-as-distance-functions.html"/>
<link rel="next" href="global-spatial-autocorrelation-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.2.0/leaflet.js"></script>
<script src="libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.2.0/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i>Disclaimer</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#using-this-book"><i class="fa fa-check"></i>Using This Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#who-this-book-is-for"><i class="fa fa-check"></i>Who This Book Is For</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html"><i class="fa fa-check"></i><b>1</b> Spatial Data Handling</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#introduction-1"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#objectives"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#preliminaries"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#loading-packages"><i class="fa fa-check"></i>Loading packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#obtaining-data-from-the-chicago-open-data-portal"><i class="fa fa-check"></i>Obtaining data from the Chicago Open Data portal</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#selecting-observations-for-a-given-time-period"><i class="fa fa-check"></i>Selecting Observations for a Given Time Period</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-observations-for-the-desired-time-period"><i class="fa fa-check"></i>Extracting observations for the desired time period</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#selecting-the-variables-for-the-final-table"><i class="fa fa-check"></i>Selecting the variables for the final table</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-point-layer"><i class="fa fa-check"></i>Creating a Point Layer</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-point-layer-from-coordinates-in-a-table---principle"><i class="fa fa-check"></i>Creating a point layer from coordinates in a table - principle</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-spatial-points-object"><i class="fa fa-check"></i>Creating a spatial points object</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#abandoned-vehicles-by-community-area"><i class="fa fa-check"></i>Abandoned Vehicles by Community Area</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#community-area-boundary-file"><i class="fa fa-check"></i>Community Area boundary file</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#spatial-join"><i class="fa fa-check"></i>Spatial join</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#counts-by-community-area"><i class="fa fa-check"></i>Counts by community area</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#mapping-the-vehicle-counts"><i class="fa fa-check"></i>Mapping the vehicle counts</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#community-area-population-data"><i class="fa fa-check"></i>Community Area Population Data</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-a-pdf-file"><i class="fa fa-check"></i>Extracting a pdf file</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#parsing-the-pdf-file"><i class="fa fa-check"></i>Parsing the pdf file</a></li>
<li class="chapter" data-level="1.0.1" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-the-population-values"><i class="fa fa-check"></i><b>1.0.1</b> Extracting the population values</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-data-frame-with-population-values"><i class="fa fa-check"></i>Creating a data frame with population values</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#mapping-community-area-abandoned-vehicles-per-capita"><i class="fa fa-check"></i>Mapping Community Area Abandoned Vehicles Per Capita</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#computing-abandoned-vehicles-per-capita"><i class="fa fa-check"></i>Computing abandoned vehicles per capita</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#final-choropleth-map"><i class="fa fa-check"></i>Final choropleth map</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html"><i class="fa fa-check"></i><b>2</b> Exploratory Data Analysis 1</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#introduction-2"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#objectives-1"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#preliminaries-1"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#load-packages"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#obtaining-the-data"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#analyzing-the-distribution-of-a-single-variable"><i class="fa fa-check"></i>Analyzing the Distribution of a Single Variable</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#a-quick-introduction-to-ggplot"><i class="fa fa-check"></i>A quick introduction to <strong>ggplot</strong></a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#bivariate-analysis-the-scatter-plot"><i class="fa fa-check"></i>Bivariate Analysis: The Scatter Plot</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#smoothing-the-scatter-plot"><i class="fa fa-check"></i>Smoothing the scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#spatial-heterogeneity"><i class="fa fa-check"></i>Spatial heterogeneity</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#structural-breaks-in-the-scatter-plot"><i class="fa fa-check"></i>Structural breaks in the scatter plot</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#chow-test"><i class="fa fa-check"></i>Chow test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html"><i class="fa fa-check"></i><b>3</b> Exploratory Data Analysis 2</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#introduction-3"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#objectives-2"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#preliminaries-2"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#load-packages-1"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#obtaining-the-data-1"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#scatter-plot-matrix"><i class="fa fa-check"></i>Scatter Plot Matrix</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#basic-scatter-plot-matrix"><i class="fa fa-check"></i>Basic scatter plot matrix</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#scatter-plot-matrix-with-smoothing"><i class="fa fa-check"></i>Scatter plot matrix with smoothing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#three-variables-bubble-chart-and-3d-scatter-plot"><i class="fa fa-check"></i>Three Variables: Bubble Chart and 3D Scatter Plot</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#bubble-chart"><i class="fa fa-check"></i>Bubble chart</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#d-scatter-plot"><i class="fa fa-check"></i>3D Scatter Plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#true-multivariate-eda-parallel-coordinate-plot-and-conditional-plots"><i class="fa fa-check"></i>True Multivariate EDA: Parallel Coordinate Plot and Conditional Plots</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#parallel-coordinate-plot-pcp"><i class="fa fa-check"></i>Parallel Coordinate Plot (PCP)</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#conditional-plots"><i class="fa fa-check"></i>Conditional Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="basic-mapping.html"><a href="basic-mapping.html"><i class="fa fa-check"></i><b>4</b> Basic Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#introduction-4"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#objectives-3"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#preliminaries-3"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#load-packages-2"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#obtaining-the-data-2"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#basic-choropleth-mapping"><i class="fa fa-check"></i>Basic Choropleth Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#default-settings-1"><i class="fa fa-check"></i>Default settings</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#color-palette"><i class="fa fa-check"></i>Color palette</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#legend"><i class="fa fa-check"></i>Legend</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#title"><i class="fa fa-check"></i>Title</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#border-options"><i class="fa fa-check"></i>Border options</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#interactive-base-map"><i class="fa fa-check"></i>Interactive base map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#saving-a-map-as-a-file"><i class="fa fa-check"></i>Saving a map as a file</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#shape-centers"><i class="fa fa-check"></i>Shape centers</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#common-map-classifications"><i class="fa fa-check"></i>Common Map Classifications</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#quantile-map"><i class="fa fa-check"></i>Quantile map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#natural-breaks-map"><i class="fa fa-check"></i>Natural breaks map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#equal-intervals-map"><i class="fa fa-check"></i>Equal intervals map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#custom-breaks"><i class="fa fa-check"></i>Custom breaks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#extreme-value-maps"><i class="fa fa-check"></i>Extreme Value Maps</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#percentile-map"><i class="fa fa-check"></i>Percentile map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#box-map"><i class="fa fa-check"></i>Box map</a></li>
<li class="chapter" data-level="4.0.1" data-path="basic-mapping.html"><a href="basic-mapping.html#standard-deviation-map"><i class="fa fa-check"></i><b>4.0.1</b> Standard deviation map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#mapping-categorical-variables"><i class="fa fa-check"></i>Mapping Categorical Variables</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#unique-value-map"><i class="fa fa-check"></i>Unique value map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#co-location-map"><i class="fa fa-check"></i>Co-location map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#conditional-map"><i class="fa fa-check"></i>Conditional Map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#cartogram"><i class="fa fa-check"></i>Cartogram</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rate-mapping.html"><a href="rate-mapping.html"><i class="fa fa-check"></i><b>5</b> Rate Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="rate-mapping.html"><a href="rate-mapping.html#introduction-5"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="rate-mapping.html"><a href="rate-mapping.html#objectives-4"><i class="fa fa-check"></i><b>5.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="5.1" data-path="rate-mapping.html"><a href="rate-mapping.html#preliminaries-4"><i class="fa fa-check"></i><b>5.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="rate-mapping.html"><a href="rate-mapping.html#load-packages-3"><i class="fa fa-check"></i><b>5.1.1</b> Load packages</a></li>
<li class="chapter" data-level="5.1.2" data-path="rate-mapping.html"><a href="rate-mapping.html#geodadata"><i class="fa fa-check"></i><b>5.1.2</b> geodaData</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="rate-mapping.html"><a href="rate-mapping.html#choropleth-map-for-rates"><i class="fa fa-check"></i><b>5.2</b> Choropleth Map for Rates</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="rate-mapping.html"><a href="rate-mapping.html#spatially-extensive-and-intensive-variables"><i class="fa fa-check"></i><b>5.2.1</b> Spatially extensive and intensive variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="rate-mapping.html"><a href="rate-mapping.html#raw-rate-map"><i class="fa fa-check"></i><b>5.2.2</b> Raw rate map</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="rate-mapping.html"><a href="rate-mapping.html#excess-risk"><i class="fa fa-check"></i><b>5.3</b> Excess risk</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="rate-mapping.html"><a href="rate-mapping.html#relative-risk"><i class="fa fa-check"></i><b>5.3.1</b> Relative risk</a></li>
<li class="chapter" data-level="5.3.2" data-path="rate-mapping.html"><a href="rate-mapping.html#excess-risk-map"><i class="fa fa-check"></i><b>5.3.2</b> Excess risk map</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="rate-mapping.html"><a href="rate-mapping.html#empirical-bayes-smoothed-rate-map"><i class="fa fa-check"></i><b>5.4</b> Empirical Bayes Smoothed Rate Map</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="rate-mapping.html"><a href="rate-mapping.html#borrowing-strength"><i class="fa fa-check"></i><b>5.4.1</b> Borrowing strength</a></li>
<li class="chapter" data-level="5.4.2" data-path="rate-mapping.html"><a href="rate-mapping.html#bayes-law"><i class="fa fa-check"></i><b>5.4.2</b> Bayes law</a></li>
<li class="chapter" data-level="5.4.3" data-path="rate-mapping.html"><a href="rate-mapping.html#the-poisson-gamma-model"><i class="fa fa-check"></i><b>5.4.3</b> The Poisson-Gamma model</a></li>
<li class="chapter" data-level="5.4.4" data-path="rate-mapping.html"><a href="rate-mapping.html#the-empirical-bayes-approach"><i class="fa fa-check"></i><b>5.4.4</b> The Empirical Bayes approach</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="rate-mapping.html"><a href="rate-mapping.html#eb-rate-map"><i class="fa fa-check"></i><b>5.5</b> EB rate map</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html"><i class="fa fa-check"></i><b>6</b> Contiguity-Based Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#introduction-6"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#objectives-5"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#preliminaries-5"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#load-packages-4"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#geodadata-1"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#contiguity-weights"><i class="fa fa-check"></i>Contiguity Weights</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#rook-contiguity"><i class="fa fa-check"></i>Rook Contiguity</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#queen-contiguity"><i class="fa fa-check"></i>Queen Contiguity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#higher-order-contiguity"><i class="fa fa-check"></i>Higher Order Contiguity</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#visualizing-contiguity-neighbors"><i class="fa fa-check"></i>Visualizing Contiguity Neighbors</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#connectivity-graph"><i class="fa fa-check"></i>Connectivity Graph</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#connectivity-histogram"><i class="fa fa-check"></i>Connectivity Histogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#saving-neighbors"><i class="fa fa-check"></i>Saving Neighbors</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#oldstyle"><i class="fa fa-check"></i>Oldstyle</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#geoda-header-format"><i class="fa fa-check"></i>GeoDA Header Format</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html"><i class="fa fa-check"></i><b>7</b> Distance-Based Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#introduction-7"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#objectives-6"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#preliminaries-6"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#load-packages-5"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#geodadata-2"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#visualizing-point-data"><i class="fa fa-check"></i>Visualizing point data</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#distance-band-weights"><i class="fa fa-check"></i>Distance-Band Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#concepts"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#creating-distance-band-weights"><i class="fa fa-check"></i>Creating distance-band weights</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#weights-characteristics"><i class="fa fa-check"></i>Weights characteristics</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#isolates"><i class="fa fa-check"></i>Isolates</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#k-nearest-neighbor-weights"><i class="fa fa-check"></i>K-Nearest Neighbor Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#concept"><i class="fa fa-check"></i>Concept</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#creating-knn-weights"><i class="fa fa-check"></i>Creating KNN Weights</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#properties-of-knn-weights"><i class="fa fa-check"></i>Properties of KNN weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#generalizing-the-concept-of-contiguity"><i class="fa fa-check"></i>Generalizing the Concept of Contiguity</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#contiguity-based-weights-for-points"><i class="fa fa-check"></i>Contiguity-based weights for points</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#contiguity-weights-for-thiessen-polygons"><i class="fa fa-check"></i>Contiguity weights for Thiessen polygons</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#distance-based-weights-for-polygons"><i class="fa fa-check"></i>Distance-based weights for polygons</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#getting-the-data"><i class="fa fa-check"></i>Getting the data</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-the-centroids"><i class="fa fa-check"></i>Computing the centroids</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-the-critical-threshold"><i class="fa fa-check"></i>Computing the critical threshold</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-distance-band-neighbors"><i class="fa fa-check"></i>Computing distance-band neighbors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html"><i class="fa fa-check"></i><b>8</b> Spatial Weights as Distance Functions</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#introduction-8"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#objectives-7"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#preliminaries-7"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#load-packages-6"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#obtaining-the-data-from-the-geoda-website"><i class="fa fa-check"></i>Obtaining the Data from the GeoDa website</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#inverse-distance-weights"><i class="fa fa-check"></i>Inverse Distance Weights</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#concepts-1"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="8.0.1" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-inverse-distance-functions-for-distance-bands"><i class="fa fa-check"></i><b>8.0.1</b> Creating inverse distance functions for distance bands</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-inverse-distance-functions-for-k-nearest-neighbors"><i class="fa fa-check"></i>Creating inverse distance functions for k-nearest neighbors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#kernal-weights"><i class="fa fa-check"></i>Kernal Weights</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#concepts-2"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-kernal-weights"><i class="fa fa-check"></i>Creating Kernal weights</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html"><i class="fa fa-check"></i><b>9</b> Applications of Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#introduction-9"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#objectives-8"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#preliminaries-8"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#load-packages-7"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#geodadata-3"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables"><i class="fa fa-check"></i>Spatially lagged variables</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#creating-a-spatially-lagged-variable"><i class="fa fa-check"></i>Creating a spatially lagged variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables-from-inverse-distance-weights"><i class="fa fa-check"></i>Spatially lagged variables from inverse distance weights</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#default-approach"><i class="fa fa-check"></i>Default approach</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-lags-with-row-standardized-inverse-distance-weights"><i class="fa fa-check"></i>Spatial lags with row-standardized inverse distance weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables-from-kernel-weights"><i class="fa fa-check"></i>Spatially lagged variables from kernel weights</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-rate-smoothing"><i class="fa fa-check"></i>Spatial rate smoothing</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle-1"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#preliminaries-9"><i class="fa fa-check"></i>Preliminaries</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#simple-window-average-of-rates"><i class="fa fa-check"></i>Simple window average of rates</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-smoothed-rates"><i class="fa fa-check"></i>Spatially Smoothed Rates</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-empirical-bayes-smoothing"><i class="fa fa-check"></i>Spatial Empirical Bayes smoothing</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle-2"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-eb-rate-smoother"><i class="fa fa-check"></i>Spatial EB rate smoother</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html"><i class="fa fa-check"></i><b>10</b> Global Spatial Autocorrelation 1</a>
<ul>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#introduction-10"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="10.0.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#objectives-9"><i class="fa fa-check"></i><b>10.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="10.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#preliminaries-10"><i class="fa fa-check"></i><b>10.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#load-packages-8"><i class="fa fa-check"></i><b>10.1.1</b> Load packages</a></li>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#geodadata-website"><i class="fa fa-check"></i>geodaData website</a></li>
<li class="chapter" data-level="10.1.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#making-the-weights"><i class="fa fa-check"></i><b>10.1.2</b> Making the weights</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#the-moran-scatter-plot"><i class="fa fa-check"></i><b>10.2</b> The Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#concept-1"><i class="fa fa-check"></i><b>10.2.1</b> Concept</a></li>
<li class="chapter" data-level="10.2.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#creating-a-moran-scatter-plot"><i class="fa fa-check"></i><b>10.2.2</b> Creating a Moran scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#spatial-correlogram"><i class="fa fa-check"></i><b>10.3</b> Spatial Correlogram</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#concept-2"><i class="fa fa-check"></i><b>10.3.1</b> Concept</a></li>
<li class="chapter" data-level="10.3.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#creating-a-spatial-correlogram"><i class="fa fa-check"></i><b>10.3.2</b> Creating a spatial correlogram</a></li>
<li class="chapter" data-level="10.3.3" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#interpretation-1"><i class="fa fa-check"></i><b>10.3.3</b> Interpretation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html"><i class="fa fa-check"></i><b>11</b> Global Spatial Autocorrelation 2</a>
<ul>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#introduction-11"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="11.0.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#objectives-10"><i class="fa fa-check"></i><b>11.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="11.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#preliminaries-11"><i class="fa fa-check"></i><b>11.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#load-packages-9"><i class="fa fa-check"></i><b>11.1.1</b> Load packages</a></li>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#obtaining-the-data-from-the-geoda-website-1"><i class="fa fa-check"></i>Obtaining the Data from the GeoDa website</a></li>
<li class="chapter" data-level="11.1.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#creating-the-weights-2"><i class="fa fa-check"></i><b>11.1.2</b> Creating the weights</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#bivariate-spatial-correlation---a-word-of-caution"><i class="fa fa-check"></i><b>11.2</b> Bivariate spatial correlation - a Word of Caution</a></li>
<li class="chapter" data-level="11.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#bivariate-moran-scatter-plot"><i class="fa fa-check"></i><b>11.3</b> Bivariate Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-3"><i class="fa fa-check"></i><b>11.3.1</b> Concept</a></li>
<li class="chapter" data-level="11.3.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#creating-a-bivariate-moran-scatter-plot"><i class="fa fa-check"></i><b>11.3.2</b> Creating a bivariate Moran scatter plot</a></li>
<li class="chapter" data-level="11.3.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#a-closer-look-at-bivariate-spatial-correlation"><i class="fa fa-check"></i><b>11.3.3</b> A closer look at bivariate spatial correlation</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#differential-moran-scatter-plot"><i class="fa fa-check"></i><b>11.4</b> Differential Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-4"><i class="fa fa-check"></i><b>11.4.1</b> Concept</a></li>
<li class="chapter" data-level="11.4.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#implementation"><i class="fa fa-check"></i><b>11.4.2</b> Implementation</a></li>
<li class="chapter" data-level="11.4.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#options"><i class="fa fa-check"></i><b>11.4.3</b> Options</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#moran-scatter-plot-for-eb-rates"><i class="fa fa-check"></i><b>11.5</b> Moran Scatter Plot for EB Rates</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-5"><i class="fa fa-check"></i><b>11.5.1</b> Concept</a></li>
<li class="chapter" data-level="11.5.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#implementation-1"><i class="fa fa-check"></i><b>11.5.2</b> Implementation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html"><i class="fa fa-check"></i><b>12</b> Local Spatial Autocorrelation 1</a>
<ul>
<li class="chapter" data-level="" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#introduction-12"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#objectives-11"><i class="fa fa-check"></i><b>12.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="12.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#preliminaries-12"><i class="fa fa-check"></i><b>12.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#load-packages-10"><i class="fa fa-check"></i><b>12.1.1</b> Load packages</a></li>
<li class="chapter" data-level="12.1.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#spatmap"><i class="fa fa-check"></i><b>12.1.2</b> spatmap</a></li>
<li class="chapter" data-level="12.1.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#geodadata-5"><i class="fa fa-check"></i><b>12.1.3</b> geodaData</a></li>
<li class="chapter" data-level="12.1.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#univariate-analysis"><i class="fa fa-check"></i><b>12.1.4</b> Univariate analysis</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-moran"><i class="fa fa-check"></i><b>12.2</b> Local Moran</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-3"><i class="fa fa-check"></i><b>12.2.1</b> Principle</a></li>
<li class="chapter" data-level="12.2.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-2"><i class="fa fa-check"></i><b>12.2.2</b> Implementation</a></li>
<li class="chapter" data-level="12.2.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#randomization-options"><i class="fa fa-check"></i><b>12.2.3</b> Randomization Options</a></li>
<li class="chapter" data-level="12.2.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#significance"><i class="fa fa-check"></i><b>12.2.4</b> Significance</a></li>
<li class="chapter" data-level="12.2.5" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#interpretation-of-clusters"><i class="fa fa-check"></i><b>12.2.5</b> Interpretation of clusters</a></li>
<li class="chapter" data-level="12.2.6" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#conditional-local-cluster-maps"><i class="fa fa-check"></i><b>12.2.6</b> Conditional local cluster maps</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-geary"><i class="fa fa-check"></i><b>12.3</b> Local Geary</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-4"><i class="fa fa-check"></i><b>12.3.1</b> Principle</a></li>
<li class="chapter" data-level="12.3.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-3"><i class="fa fa-check"></i><b>12.3.2</b> Implementation</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#getis-ord-statistics"><i class="fa fa-check"></i><b>12.4</b> Getis-Ord Statistics</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-5"><i class="fa fa-check"></i><b>12.4.1</b> Principle</a></li>
<li class="chapter" data-level="12.4.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-4"><i class="fa fa-check"></i><b>12.4.2</b> Implementation</a></li>
<li class="chapter" data-level="12.4.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#interpretation-and-significance-1"><i class="fa fa-check"></i><b>12.4.3</b> Interpretation and significance</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-join-count-statistic"><i class="fa fa-check"></i><b>12.5</b> Local Join Count Statistic</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-6"><i class="fa fa-check"></i><b>12.5.1</b> Principle</a></li>
<li class="chapter" data-level="12.5.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-5"><i class="fa fa-check"></i><b>12.5.2</b> Implementation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>13</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Hands-On Spatial Data Science with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="applications-of-spatial-weights" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Applications of Spatial Weights<a href="applications-of-spatial-weights.html#applications-of-spatial-weights" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-9" class="section level2 unnumbered hasAnchor">
<h2>Introduction<a href="applications-of-spatial-weights.html#introduction-9" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This notebook cover the functionality of the <a href="https://geodacenter.github.io/workbook/4d_weights_applications/lab4d.html">Applications of Spatial Weights</a> section of the GeoDa workbook. We refer to that document for details on the methodology, references, etc. The goal of these notes is to approximate as closely as possible the operations carried out using GeoDa by means of a range of R packages.</p>
<p>The notes are written with R beginners in mind, more seasoned R users can probably skip most of the comments
on data structures and other R particulars. Also, as always in R, there are typically several ways to achieve a specific objective, so what is shown here is just one way that works, but there often are others (that may even be more elegant, work faster, or scale better).</p>
<p>For this notebook, we use Cleveland house price data. Our goal in this lab is show how to assign spatial weights based on different distance functions.</p>
<div id="objectives-8" class="section level3 unnumbered hasAnchor">
<h3>Objectives<a href="applications-of-spatial-weights.html#objectives-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After completing the notebook, you should know how to carry out the following tasks:</p>
<ul>
<li><p>Create a spatially lagged variable as an average or sum of the neighbors</p></li>
<li><p>Create a spatially lagged variable as a window sum or average</p></li>
<li><p>Create a spatially lagged variable based on inverse distance weights</p></li>
<li><p>Create a spatially lagged variable based on kernel weights</p></li>
<li><p>Rescaling coordinates to obtain inverse distance weights</p></li>
<li><p>Compute and map spatially smoothed rates</p></li>
<li><p>Compute and map spatial Empirical Bayes smoothed rates</p></li>
</ul>
<div id="r-packages-used-8" class="section level4 unnumbered hasAnchor">
<h4>R Packages used<a href="applications-of-spatial-weights.html#r-packages-used-8" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p><strong>sf</strong>: To read in the shapefile.</p></li>
<li><p><strong>spdep</strong>: To create k-nearest neighbors and distance-band neighbors, calculate distances between neighbors, convert to a weights structure, and coercion methods to sparse matrices.</p></li>
<li><p><strong>knitr</strong>: To make nicer looking tables</p></li>
<li><p><strong>ggplot2</strong>: To make a scatterplot comparing two different rate variables</p></li>
<li><p><strong>tmap</strong>: To make maps of different spatial rate variables</p></li>
<li><p><strong>broom</strong>: To get regression statistics in a tidy format</p></li>
<li><p><strong>GGally</strong>: To make a parallel coordinates plot</p></li>
<li><p><strong>purrr</strong>: To map a centroid function of the geometry column of an <strong>sf</strong> data structure</p></li>
<li><p><strong>geodaData</strong>: To access the data for this notebook</p></li>
<li><p><strong>tidyverse</strong>: Basic data frame manipulation</p></li>
</ul>
</div>
<div id="r-commands-used-8" class="section level4 unnumbered hasAnchor">
<h4>R Commands used<a href="applications-of-spatial-weights.html#r-commands-used-8" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Below follows a list of the commands used in this notebook. For further details
and a comprehensive list of options, please consult the
<a href="https://www.rdocumentation.org">R documentation</a>.</p>
<ul>
<li><p><strong>Base R</strong>: <code>install.packages</code>, <code>library</code>, <code>setwd</code>, <code>class</code>, <code>str</code>, <code>lapply</code>, <code>attributes</code>, <code>summary</code>, <code>head</code>, <code>seq</code>, <code>as</code>, <code>cbind</code>, <code>max</code>, <code>unlist</code>, <code>length</code>, <code>sqrt</code>, <code>exp</code>, <code>diag</code>, <code>sort</code>, <code>append</code>, <code>sum</code></p></li>
<li><p><strong>sf</strong>: <code>st_read</code>, <code>plot</code></p></li>
<li><p><strong>spdep</strong>: <code>knn2nb</code>, <code>dnearneigh</code>, <code>knearneigh</code>, <code>nb2listw</code>, <code>mat2listw</code>, <code>EBlocal</code>, <code>lag.listw</code>, <code>include.self</code></p></li>
<li><p><strong>knitr</strong>: <code>kable</code></p></li>
<li><p><strong>ggplot2</strong>: <code>ggplot</code>, <code>geom_smooth</code>, <code>geom_point</code>, <code>ggtitle</code></p></li>
<li><p><strong>tmap</strong>: <code>tm_shape</code>, <code>tm_fill</code>, <code>tm_border</code>, <code>tm_layout</code></p></li>
<li><p><strong>broom</strong>: <code>tidy</code></p></li>
<li><p><strong>GGally</strong>: <code>ggparcoord</code></p></li>
<li><p><strong>purrr</strong>: <code>map_dbl</code></p></li>
<li><p><strong>tidyverse</strong>: <code>mutate</code></p></li>
</ul>
</div>
</div>
</div>
<div id="preliminaries-8" class="section level2 unnumbered hasAnchor">
<h2>Preliminaries<a href="applications-of-spatial-weights.html#preliminaries-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before starting, make sure to have the latest version of R and of packages that are compiled for the matching version of R (this document was created using R 3.5.1 of 2018-07-02). Also, optionally, set a working directory, even though we will not
actually be saving any files.<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a></p>
<div id="load-packages-7" class="section level3 unnumbered hasAnchor">
<h3>Load packages<a href="applications-of-spatial-weights.html#load-packages-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, we load all the required packages using the <code>library</code> command. If you don’t have some of these in your system, make sure to install them first as well as
their dependencies.<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a> You will get an error message if something is missing. If needed, just install the missing piece and everything will work after that.</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="applications-of-spatial-weights.html#cb459-1" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb459-2"><a href="applications-of-spatial-weights.html#cb459-2" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb459-3"><a href="applications-of-spatial-weights.html#cb459-3" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb459-4"><a href="applications-of-spatial-weights.html#cb459-4" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb459-5"><a href="applications-of-spatial-weights.html#cb459-5" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb459-6"><a href="applications-of-spatial-weights.html#cb459-6" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb459-7"><a href="applications-of-spatial-weights.html#cb459-7" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb459-8"><a href="applications-of-spatial-weights.html#cb459-8" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb459-9"><a href="applications-of-spatial-weights.html#cb459-9" tabindex="-1"></a><span class="fu">library</span>(purrr)</span></code></pre></div>
</div>
<div id="geodadata-3" class="section level3 unnumbered hasAnchor">
<h3>geodaData<a href="applications-of-spatial-weights.html#geodadata-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>All of the data for the R notebooks is available in the <strong>geodaData</strong>
package. We loaded the library earlier, now to access the individual
data sets, we use the double colon notation. This works similar to
to accessing a variable with <code>$</code>, in that a drop down menu will
appear with a list of the datasets included in the package. For this
notebook, we use <code>clev_pts</code>.</p>
<p>If you choose to download the data into your working directory, you will need to go to <a href="https://geodacenter.github.io/data-and-lab//clev_sls_154_core/">Cleveland Home Sales</a> The download format is a
zipfile, so you will need to unzip it by double clicking on the file in your file
finder. From there move the resulting folder titled: nyc into your working directory
to continue. Once that is done, you can use the <strong>sf</strong> function: <code>st_read()</code> to read
the shapefile into your R environment.</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="applications-of-spatial-weights.html#cb460-1" tabindex="-1"></a>clev.points <span class="ot">&lt;-</span> geodaData<span class="sc">::</span>clev_pts</span></code></pre></div>
</div>
</div>
<div id="spatially-lagged-variables" class="section level2 unnumbered hasAnchor">
<h2>Spatially lagged variables<a href="applications-of-spatial-weights.html#spatially-lagged-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With a neighbor structure defined by the non-zero elements of the spatial weights matrix W, a spatially lagged
variable is a weighted sum or a weighted average of the neighboring values for that variable. In most commonly
used notation, the spatial lag of y is then expressed as Wy.
.</p>
<p>Formally, for observation i, the spatial lag of <span class="math inline">\(y_i\)</span>, referred to as <span class="math inline">\([Wy]_i\)</span> (the variable Wy observed for
location i) is:
<span class="math display">\[[Wy]_i = w_{i1}y_1 + w_{i2}y_2 + ... + w_{in}y_n\]</span>
or,
<span class="math display">\[[Wy]_i = \sum_{j=1}^nw_{ij}y_j\]</span>
where the weights <span class="math inline">\(w_{ij}\)</span> consist of the elements of the i-th row of the matrix W, matched up with the
corresponding elements of the vector y.</p>
<p>In other words, the spatial lag is a weighted sum of the values observed at neighboring locations, since the
non-neighbors are not included (those i for which <span class="math inline">\(w_{ij}=0\)</span>). Typically, the weights matrix is very sparse, so
that only a small number of neighbors contribute to the weighted sum. For row-standardized weights,
with<span class="math inline">\(\sum_jw_{ij} = 1\)</span>, the spatially lagged variable becomes a weighted average of the values at
neighboring observations.</p>
<p>In matrix notation, the spatial lag expression corresponds to the matrix product of the <strong>n × n</strong> spatial weights
matrix W with the <strong>n × 1</strong> vector of observations y, or <strong>W × y</strong>. The matrix W can therefore be considered to be
the spatial lag operator on the vector <strong>y</strong>.</p>
<p>In a number of applied contexts, it may be useful to include the observation at location i itself in the weights
computation. This implies that the diagonal elements of the weights matrix must be non-zero, i.e., <span class="math inline">\(w_{ii}≠0\)</span>.
Depending on the context, the diagonal elements may take on the value of one or equal a specific value (e.g., for
kernel weights where the kernel function is applied to the diagonal). We will highlight this issue in the specific
illustrations that follow.</p>
<div id="creating-a-spatially-lagged-variable" class="section level3 unnumbered hasAnchor">
<h3>Creating a spatially lagged variable<a href="applications-of-spatial-weights.html#creating-a-spatially-lagged-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this section, we will go through the four different spatial lag options covered in the Geoda workbook. These
are <strong>Spatial lag with row-standardized weights</strong>, ** Spatial lag as a sum of neighboring values<strong>,
</strong>Spatial window average<strong>, and </strong>Spatial window sum**.</p>
<div id="creating-the-weights" class="section level4 unnumbered hasAnchor">
<h4>Creating the weights<a href="applications-of-spatial-weights.html#creating-the-weights" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To start, we will need to make our weights in order to follow along with the Geoda workbook example. This will require
making a k-nearest neighbors for k = 6 with row standarized weights.</p>
<p>The process for making these weights is the same as covered in earlier notebooks. However, to summarize, we
start by getting the coordinates in a separate matrix with the base R function <code>cbind</code>, then use that with
the <strong>spdep</strong> functions <code>knn2nb</code> and <code>knearneigh</code> to compute a neighbors list. From there we convert the
neighbors list to class <strong>listw</strong> with <code>nb2listw</code>. This will result in row standardized weights. It is
important to note that we will have to work with neighbors structure in some cases to get the desired
functionality, which will require creating more than one weights object for the k-nearest neighbors weights
used in this section of the notebook.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="applications-of-spatial-weights.html#cb461-1" tabindex="-1"></a><span class="co"># getting coordinates</span></span>
<span id="cb461-2"><a href="applications-of-spatial-weights.html#cb461-2" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(clev.points<span class="sc">$</span>x,clev.points<span class="sc">$</span>y)</span>
<span id="cb461-3"><a href="applications-of-spatial-weights.html#cb461-3" tabindex="-1"></a></span>
<span id="cb461-4"><a href="applications-of-spatial-weights.html#cb461-4" tabindex="-1"></a><span class="co"># creating neighbors list</span></span>
<span id="cb461-5"><a href="applications-of-spatial-weights.html#cb461-5" tabindex="-1"></a>k6 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k =</span> <span class="dv">6</span>))</span>
<span id="cb461-6"><a href="applications-of-spatial-weights.html#cb461-6" tabindex="-1"></a></span>
<span id="cb461-7"><a href="applications-of-spatial-weights.html#cb461-7" tabindex="-1"></a><span class="co"># converting to weights structure from neighbors list</span></span>
<span id="cb461-8"><a href="applications-of-spatial-weights.html#cb461-8" tabindex="-1"></a>k6.weights1 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k6)</span>
<span id="cb461-9"><a href="applications-of-spatial-weights.html#cb461-9" tabindex="-1"></a>k6.weights1<span class="sc">$</span>weights[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667</code></pre>
</div>
<div id="spatial-lag-with-row-standardized-weights" class="section level4 unnumbered hasAnchor">
<h4>Spatial lag with row-standardized weights<a href="applications-of-spatial-weights.html#spatial-lag-with-row-standardized-weights" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The default case in Geoda is to use row-standardized weights and to leave out the diagonal element. Implementing this
will be relatively simple, as we will only need one line of code with the weights structure:
<strong>k6.weights1</strong>. To create the lag variable, the <strong>spdep</strong> function, <code>lag.listw</code> is used. The inputs require
a weights structure and a variable with the same length as the weights structure. The length should not
be a problem if the variable comes from the same dataset used to create your weights.</p>
<p>We create a new data frame of the <strong>sale_price</strong> variable and the lag variable to get a side by side
look. To get a brief look at the first few observations of both variables, we use <code>head</code>. Then to get
a nicer looking table, we use <code>kable</code> from the <strong>knitr</strong> package.</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="applications-of-spatial-weights.html#cb463-1" tabindex="-1"></a>lag1 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(k6.weights1, clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb463-2"><a href="applications-of-spatial-weights.html#cb463-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sale_price =</span> clev.points<span class="sc">$</span>sale_price, lag1)</span>
<span id="cb463-3"><a href="applications-of-spatial-weights.html#cb463-3" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">sale_price</th>
<th align="right">lag1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">235500</td>
<td align="right">79858.33</td>
</tr>
<tr class="even">
<td align="right">65000</td>
<td align="right">90608.33</td>
</tr>
<tr class="odd">
<td align="right">92000</td>
<td align="right">71041.67</td>
</tr>
<tr class="even">
<td align="right">5000</td>
<td align="right">91375.00</td>
</tr>
<tr class="odd">
<td align="right">116250</td>
<td align="right">72833.33</td>
</tr>
<tr class="even">
<td align="right">120000</td>
<td align="right">74041.67</td>
</tr>
</tbody>
</table>
<p>The values match with the example from the Geoda workbook, only difference being in that it is rounded to less
significant figures than GeoDa.</p>
<p>The lag variables are calculated in this instance, by taking an average of the neighboring values. We will
illustrate this by finding the neighboring sale price values for the first observation. To get these values,
we get the neighbor ids for the first observation by double bracket notation. We then select the sale
price values by indexing with the resulting numeric vector.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="applications-of-spatial-weights.html#cb464-1" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> k6[[<span class="dv">1</span>]]</span>
<span id="cb464-2"><a href="applications-of-spatial-weights.html#cb464-2" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> clev.points<span class="sc">$</span>sale_price[nb1]</span>
<span id="cb464-3"><a href="applications-of-spatial-weights.html#cb464-3" tabindex="-1"></a>nb1</span></code></pre></div>
<pre><code>## [1]  65000 120000 131650  81500  76000   5000</code></pre>
<p>We now verify the value for the spatial lag listed in the table. It is obtained as the average of the sales price
for the six neighbors, or (131650 + 65000 + 81500 + 76000 + 120000 + 5000)/6 = 79858.33.</p>
<p>We can quickly assess the effect of spatial averaging by comparing the descriptive statistics for the lag variable
with those of the original sale price variable.</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="applications-of-spatial-weights.html#cb466-1" tabindex="-1"></a><span class="fu">summary</span>(clev.points<span class="sc">$</span>sale_price)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1049    9000   20000   41897   48500  527409</code></pre>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="applications-of-spatial-weights.html#cb468-1" tabindex="-1"></a><span class="fu">summary</span>(lag1)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    6583   16142   26500   39818   54417  229583</code></pre>
<p>As seen above, the range for the original sale price variable is 1,049 to 527,409. The range for the
lag variable is much more compressed, being 6,583 to 229,583. The typical effect of spatial lag is a compression
of the range and variance of a variable. We can see this further when examing the standard deviation.</p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="applications-of-spatial-weights.html#cb470-1" tabindex="-1"></a><span class="fu">sd</span>(clev.points<span class="sc">$</span>sale_price)</span></code></pre></div>
<pre><code>## [1] 60654.34</code></pre>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="applications-of-spatial-weights.html#cb472-1" tabindex="-1"></a><span class="fu">sd</span>(lag1)</span></code></pre></div>
<pre><code>## [1] 36463.76</code></pre>
<p>The standard deviation for home sales gets significantly condensed from 60654.34 to 36463.76 in the creation
of the lag variable.</p>
</div>
<div id="pcp" class="section level4 unnumbered hasAnchor">
<h4>PCP<a href="applications-of-spatial-weights.html#pcp" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To get a more dramatic view of the influence of high-valued or low-valued neighbors on the spatial lag, we use
a parallel coordinates plot. This will be done using <strong>GGally</strong>, which is an R package that builds off of the
<strong>ggplot2</strong> package for some more complicated plots, ie the parallel coordinates plot and the scatter plot
matrix. We won’t go in depth about the different options this package offers in this notebook, but if interested,
check out <a href="https://www.rdocumentation.org/packages/GGally/versions/1.4.0">GGally documentation</a>.</p>
<p>To make the pcp with just the two variables, we will need to put them in a separate matrix, or data
frame. We use <code>cbind</code> to do this, as with the coordinates. From there we use <code>ggparcoord</code> from the <strong>GGally</strong>
package. The necessary inputs are the data(<strong>pcp.vars</strong>) and the scale parameter. We use `scale = “globalminmax”
to keep the same price values as our lag variable and sale price variable. The default option scales it down,
which is not what we are looking for in this case.</p>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="applications-of-spatial-weights.html#cb474-1" tabindex="-1"></a>sale.price <span class="ot">&lt;-</span> clev.points<span class="sc">$</span>sale_price</span>
<span id="cb474-2"><a href="applications-of-spatial-weights.html#cb474-2" tabindex="-1"></a>pcp.vars <span class="ot">&lt;-</span> <span class="fu">cbind</span>(sale.price,lag1)</span>
<span id="cb474-3"><a href="applications-of-spatial-weights.html#cb474-3" tabindex="-1"></a><span class="fu">ggparcoord</span>(<span class="at">data =</span> pcp.vars,<span class="at">scale =</span><span class="st">&quot;globalminmax&quot;</span>) <span class="sc">+</span></span>
<span id="cb474-4"><a href="applications-of-spatial-weights.html#cb474-4" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Parallel Coordinate Plot&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-339-1.png" width="672" /></p>
</div>
<div id="spatial-lag-as-a-sum-of-neighboring-values" class="section level4 unnumbered hasAnchor">
<h4>Spatial lag as a sum of neighboring values<a href="applications-of-spatial-weights.html#spatial-lag-as-a-sum-of-neighboring-values" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can calculate spatial lag as a sum of neighboring values by assigning
binary weights. This requires us to go back to our neighbors list, then
apply a function that will assign binary weights, then we use <code>glist =</code> in
the <code>nb2listw</code> function to explicitly assign these weights.</p>
<p>We start by applying a function that will assign a value of 1 per each neighbor. This is done with <code>lapply</code>, which we have been using to manipulate
the neighbors structure throughout the past notebooks. Basically it applies
a function across each value in the neighbors structure.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="applications-of-spatial-weights.html#cb475-1" tabindex="-1"></a>binary.weights <span class="ot">&lt;-</span> <span class="fu">lapply</span>(k6, <span class="cf">function</span>(x) <span class="dv">0</span><span class="sc">*</span>x <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb475-2"><a href="applications-of-spatial-weights.html#cb475-2" tabindex="-1"></a>k6.weights2 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k6, <span class="at">glist =</span> binary.weights, <span class="at">style =</span> <span class="st">&quot;B&quot;</span>)</span></code></pre></div>
<p>With the proper weights assigned, we can use <code>lag.listw</code> to compute a lag
variable from our weight and sale price data.</p>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="applications-of-spatial-weights.html#cb476-1" tabindex="-1"></a>lag2 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(k6.weights2, clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb476-2"><a href="applications-of-spatial-weights.html#cb476-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">lag2 =</span> lag2)</span>
<span id="cb476-3"><a href="applications-of-spatial-weights.html#cb476-3" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">sale_price</th>
<th align="right">lag1</th>
<th align="right">lag2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">235500</td>
<td align="right">79858.33</td>
<td align="right">479150</td>
</tr>
<tr class="even">
<td align="right">65000</td>
<td align="right">90608.33</td>
<td align="right">543650</td>
</tr>
<tr class="odd">
<td align="right">92000</td>
<td align="right">71041.67</td>
<td align="right">426250</td>
</tr>
<tr class="even">
<td align="right">5000</td>
<td align="right">91375.00</td>
<td align="right">548250</td>
</tr>
<tr class="odd">
<td align="right">116250</td>
<td align="right">72833.33</td>
<td align="right">437000</td>
</tr>
<tr class="even">
<td align="right">120000</td>
<td align="right">74041.67</td>
<td align="right">444250</td>
</tr>
</tbody>
</table>
</div>
<div id="spatial-window-average" class="section level4 unnumbered hasAnchor">
<h4>Spatial window average<a href="applications-of-spatial-weights.html#spatial-window-average" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The spatial window average uses row-standardized weights and includes the
diagonal element. To do this in R, we need to go back to the neighbors
structure and add the diagonal element before assigning weights. To begin
we assign <strong>k6</strong> to a new variable because we will directly alter its
structure to add the diagonal elements.</p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="applications-of-spatial-weights.html#cb477-1" tabindex="-1"></a>k6a <span class="ot">&lt;-</span> k6</span></code></pre></div>
<p>To add the diagonal element to the neighbors list, we just need <code>include.self</code>
from <strong>spdep</strong>.</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="applications-of-spatial-weights.html#cb478-1" tabindex="-1"></a><span class="fu">include.self</span>(k6a)</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 205 
## Number of nonzero links: 1435 
## Percentage nonzero weights: 3.414634 
## Average number of links: 7 
## Non-symmetric neighbours list</code></pre>
<p>Now we obtain weights with <code>nb2listw</code></p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="applications-of-spatial-weights.html#cb480-1" tabindex="-1"></a>k6.weights3 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k6a)</span></code></pre></div>
<p>Lastly, we just need to create the lag variable from our weight structure and
<strong>sale_price</strong> variable.</p>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="applications-of-spatial-weights.html#cb481-1" tabindex="-1"></a>lag3 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(k6.weights3, clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb481-2"><a href="applications-of-spatial-weights.html#cb481-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">lag3 =</span> lag3)</span>
<span id="cb481-3"><a href="applications-of-spatial-weights.html#cb481-3" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">sale_price</th>
<th align="right">lag1</th>
<th align="right">lag2</th>
<th align="right">lag3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">235500</td>
<td align="right">79858.33</td>
<td align="right">479150</td>
<td align="right">79858.33</td>
</tr>
<tr class="even">
<td align="right">65000</td>
<td align="right">90608.33</td>
<td align="right">543650</td>
<td align="right">90608.33</td>
</tr>
<tr class="odd">
<td align="right">92000</td>
<td align="right">71041.67</td>
<td align="right">426250</td>
<td align="right">71041.67</td>
</tr>
<tr class="even">
<td align="right">5000</td>
<td align="right">91375.00</td>
<td align="right">548250</td>
<td align="right">91375.00</td>
</tr>
<tr class="odd">
<td align="right">116250</td>
<td align="right">72833.33</td>
<td align="right">437000</td>
<td align="right">72833.33</td>
</tr>
<tr class="even">
<td align="right">120000</td>
<td align="right">74041.67</td>
<td align="right">444250</td>
<td align="right">74041.67</td>
</tr>
</tbody>
</table>
</div>
<div id="spatial-window-sum" class="section level4 unnumbered hasAnchor">
<h4>Spatial window sum<a href="applications-of-spatial-weights.html#spatial-window-sum" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The spatial window sum is the counter part of the window average, but
without using row-standardized weights. To do this we assign binary
weights to the neighbor structure that includes the diagonal element.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="applications-of-spatial-weights.html#cb482-1" tabindex="-1"></a>binary.weights2 <span class="ot">&lt;-</span> <span class="fu">lapply</span>(k6a, <span class="cf">function</span>(x) <span class="dv">0</span><span class="sc">*</span>x <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb482-2"><a href="applications-of-spatial-weights.html#cb482-2" tabindex="-1"></a>binary.weights2[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [[1]]
## [1] 1 1 1 1 1 1</code></pre>
<p>Again we use <code>nb2listw</code> and <code>glist =</code> to explicitly assign weight values.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="applications-of-spatial-weights.html#cb484-1" tabindex="-1"></a>k6.weights4 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k6a, <span class="at">glist =</span> binary.weights2, <span class="at">style =</span> <span class="st">&quot;B&quot;</span>)</span></code></pre></div>
<p>With our new weight structure, we can compute the lag variable with <code>lag.listw</code>.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="applications-of-spatial-weights.html#cb485-1" tabindex="-1"></a>lag4 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(k6.weights4, clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb485-2"><a href="applications-of-spatial-weights.html#cb485-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">lag4 =</span> lag4)</span>
<span id="cb485-3"><a href="applications-of-spatial-weights.html#cb485-3" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">sale_price</th>
<th align="right">lag1</th>
<th align="right">lag2</th>
<th align="right">lag3</th>
<th align="right">lag4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">235500</td>
<td align="right">79858.33</td>
<td align="right">479150</td>
<td align="right">79858.33</td>
<td align="right">479150</td>
</tr>
<tr class="even">
<td align="right">65000</td>
<td align="right">90608.33</td>
<td align="right">543650</td>
<td align="right">90608.33</td>
<td align="right">543650</td>
</tr>
<tr class="odd">
<td align="right">92000</td>
<td align="right">71041.67</td>
<td align="right">426250</td>
<td align="right">71041.67</td>
<td align="right">426250</td>
</tr>
<tr class="even">
<td align="right">5000</td>
<td align="right">91375.00</td>
<td align="right">548250</td>
<td align="right">91375.00</td>
<td align="right">548250</td>
</tr>
<tr class="odd">
<td align="right">116250</td>
<td align="right">72833.33</td>
<td align="right">437000</td>
<td align="right">72833.33</td>
<td align="right">437000</td>
</tr>
<tr class="even">
<td align="right">120000</td>
<td align="right">74041.67</td>
<td align="right">444250</td>
<td align="right">74041.67</td>
<td align="right">444250</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="spatially-lagged-variables-from-inverse-distance-weights" class="section level2 unnumbered hasAnchor">
<h2>Spatially lagged variables from inverse distance weights<a href="applications-of-spatial-weights.html#spatially-lagged-variables-from-inverse-distance-weights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="principle" class="section level3 unnumbered hasAnchor">
<h3>Principle<a href="applications-of-spatial-weights.html#principle" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The spatial lag operation can also be applied using spatial weights calculated from the inverse
distance between observations. As mentioned in our earlier discussion, the magnitude of these
weights is highly scale dependent (depends on the scale of the coordinates). An uncritical
application of a spatial lag operation with these weights can easily result in non-sensical
values. More specifically, since the resulting weights can take on very small values, the
spatial lag could end up being essentially zero.</p>
<p>Formally, the spatial lag operation amounts to a weighted average of the neighboring values,
with the inverse distance function as the weights:
<span class="math display">\[[Wy]_i = \sum_jy_j/d_{ij}^\alpha\]</span>
where in our implementation, <span class="math inline">\(\alpha\)</span> is either 1 or 2. In the latter case (a so-called gravity model
weight), the spatial lag is sometimes referred to as a potential in geo-marketing analyses. It
is a measure of how accessible location i is to opportunities located in the neighboring
locations (as defined by the weights).</p>
</div>
<div id="default-approach" class="section level3 unnumbered hasAnchor">
<h3>Default approach<a href="applications-of-spatial-weights.html#default-approach" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="inverse-distance-for-k-6-nearest-neighbors" class="section level4 unnumbered hasAnchor">
<h4>inverse distance for k = 6 nearest neighbors<a href="applications-of-spatial-weights.html#inverse-distance-for-k-6-nearest-neighbors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To calculate the inverse distances, we must first compute the distances between each neighbor.
This is done with <code>nbdists</code>.</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="applications-of-spatial-weights.html#cb486-1" tabindex="-1"></a>k6.distances <span class="ot">&lt;-</span> <span class="fu">nbdists</span>(k6,coords)</span></code></pre></div>
<p>Now we apply the function 1/x to each element of the distance structure, which gives us
the inverse distances.</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="applications-of-spatial-weights.html#cb487-1" tabindex="-1"></a>invd1a <span class="ot">&lt;-</span> <span class="fu">lapply</span>(k6.distances, <span class="cf">function</span>(x) (<span class="dv">1</span><span class="sc">/</span>x))</span>
<span id="cb487-2"><a href="applications-of-spatial-weights.html#cb487-2" tabindex="-1"></a>invd1a[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [[1]]
## [1] 0.0025963168 0.0003318873 0.0008618371 0.0005379514 0.0003959608
## [6] 0.0003074062</code></pre>
<p>Now we explicitly assign the inverse distance weight with <code>glist =</code> in the <code>nb2listw</code> function.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="applications-of-spatial-weights.html#cb489-1" tabindex="-1"></a>invd.weights <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k6,<span class="at">glist =</span> invd1a,<span class="at">style =</span> <span class="st">&quot;B&quot;</span>)</span></code></pre></div>
<p>The default case with row-standardized weights off and no diagonal elements
is put into the variable <strong>IDRSND</strong>. The lag values here are very different
from the sale price because the weight values are relatively small, the largest
being .0026</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="applications-of-spatial-weights.html#cb490-1" tabindex="-1"></a>idrsnd <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(invd.weights, clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb490-2"><a href="applications-of-spatial-weights.html#cb490-2" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(idrsnd))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">397.5210</td>
</tr>
<tr class="even">
<td align="right">805.2941</td>
</tr>
<tr class="odd">
<td align="right">359.3411</td>
</tr>
<tr class="even">
<td align="right">966.1106</td>
</tr>
<tr class="odd">
<td align="right">444.5489</td>
</tr>
<tr class="even">
<td align="right">361.3308</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="applications-of-spatial-weights.html#cb491-1" tabindex="-1"></a>idnrwd <span class="ot">&lt;-</span> clev.points<span class="sc">$</span>sale_price <span class="sc">+</span> idrsnd</span>
<span id="cb491-2"><a href="applications-of-spatial-weights.html#cb491-2" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(idnrwd))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">235897.521</td>
</tr>
<tr class="even">
<td align="right">65805.294</td>
</tr>
<tr class="odd">
<td align="right">92359.341</td>
</tr>
<tr class="even">
<td align="right">5966.111</td>
</tr>
<tr class="odd">
<td align="right">116694.549</td>
</tr>
<tr class="even">
<td align="right">120361.331</td>
</tr>
</tbody>
</table>
<p>The above would be the result for when the diagonal is included. This amounts
to the original sale price being added to the the lag value, which is the
equivalent of:
<span class="math display">\[[W_y]_i = y_i + \Sigma_j\frac{y_i}{d_{ij}^\alpha}\]</span></p>
</div>
</div>
<div id="spatial-lags-with-row-standardized-inverse-distance-weights" class="section level3 unnumbered hasAnchor">
<h3>Spatial lags with row-standardized inverse distance weights<a href="applications-of-spatial-weights.html#spatial-lags-with-row-standardized-inverse-distance-weights" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="applications-of-spatial-weights.html#cb492-1" tabindex="-1"></a>row_stand <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb492-2"><a href="applications-of-spatial-weights.html#cb492-2" tabindex="-1"></a>  row_sum <span class="ot">&lt;-</span> <span class="fu">sum</span>(x)</span>
<span id="cb492-3"><a href="applications-of-spatial-weights.html#cb492-3" tabindex="-1"></a>  scalar <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>row_sum</span>
<span id="cb492-4"><a href="applications-of-spatial-weights.html#cb492-4" tabindex="-1"></a>  x <span class="sc">*</span> scalar</span>
<span id="cb492-5"><a href="applications-of-spatial-weights.html#cb492-5" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="applications-of-spatial-weights.html#cb493-1" tabindex="-1"></a>row.standw <span class="ot">&lt;-</span> <span class="fu">lapply</span>(invd1a, row_stand)</span>
<span id="cb493-2"><a href="applications-of-spatial-weights.html#cb493-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">inverse_distance =</span> invd1a[[<span class="dv">1</span>]], <span class="at">row_stand_invd =</span> row.standw[[<span class="dv">1</span>]])</span>
<span id="cb493-3"><a href="applications-of-spatial-weights.html#cb493-3" tabindex="-1"></a><span class="fu">kable</span>(df)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">inverse_distance</th>
<th align="right">row_stand_invd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.0025963</td>
<td align="right">0.5160269</td>
</tr>
<tr class="even">
<td align="right">0.0003319</td>
<td align="right">0.0659637</td>
</tr>
<tr class="odd">
<td align="right">0.0008618</td>
<td align="right">0.1712931</td>
</tr>
<tr class="even">
<td align="right">0.0005380</td>
<td align="right">0.1069197</td>
</tr>
<tr class="odd">
<td align="right">0.0003960</td>
<td align="right">0.0786986</td>
</tr>
<tr class="even">
<td align="right">0.0003074</td>
<td align="right">0.0610980</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="applications-of-spatial-weights.html#cb494-1" tabindex="-1"></a><span class="fu">sum</span>(row.standw[[<span class="dv">1</span>]])</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="applications-of-spatial-weights.html#cb496-1" tabindex="-1"></a>invd.weights2 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k6,<span class="at">glist =</span> row.standw,<span class="at">style =</span> <span class="st">&quot;B&quot;</span>)</span>
<span id="cb496-2"><a href="applications-of-spatial-weights.html#cb496-2" tabindex="-1"></a>invd.weights2<span class="sc">$</span>weights[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 0.51602688 0.06596374 0.17129309 0.10691969 0.07869856 0.06109804</code></pre>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="applications-of-spatial-weights.html#cb498-1" tabindex="-1"></a>lag6 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(invd.weights2, clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb498-2"><a href="applications-of-spatial-weights.html#cb498-2" tabindex="-1"></a><span class="fu">head</span>(lag6)</span></code></pre></div>
<pre><code>## [1]  79008.67 159632.92  70716.60 101979.20  45949.65  65842.27</code></pre>
</div>
</div>
<div id="spatially-lagged-variables-from-kernel-weights" class="section level2 unnumbered hasAnchor">
<h2>Spatially lagged variables from kernel weights<a href="applications-of-spatial-weights.html#spatially-lagged-variables-from-kernel-weights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Spatially lagged variables can also be computed from kernel weights. However,
in this instance, only one of the options with respect to row-standardization
and diagonal weights makes sense. Since the kernel weights are the result of a
specific kernel function, they should not be altered. Also, each kernel
function results in a specific value for the diagonal element, which should not
be changed either. As a result, the only viable option to create spatially
lagged variables based on kernel weights is to have no row-standardization and
have the diagonal elements included.</p>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="applications-of-spatial-weights.html#cb500-1" tabindex="-1"></a>k6a.distances <span class="ot">&lt;-</span> <span class="fu">nbdists</span>(k6a,coords)</span></code></pre></div>
<p>Here we apply the Epanechnikov kernal weight function to the distance structure, but
calculate z as a variable bandwidth rather than the critical threshold. For the variable
bandwidth, we take the maximum distance between a location and it’s set of 6 neighbors. Then
this is the distance used to calculate the weights for the neighbors of that location.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="applications-of-spatial-weights.html#cb501-1" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(k6a.distances)){</span>
<span id="cb501-2"><a href="applications-of-spatial-weights.html#cb501-2" tabindex="-1"></a>  maxk6 <span class="ot">&lt;-</span> <span class="fu">max</span>(k6a.distances[[i]])</span>
<span id="cb501-3"><a href="applications-of-spatial-weights.html#cb501-3" tabindex="-1"></a>  bandwidth <span class="ot">&lt;-</span> maxk6</span>
<span id="cb501-4"><a href="applications-of-spatial-weights.html#cb501-4" tabindex="-1"></a>  new_row <span class="ot">&lt;-</span> .<span class="dv">75</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>(k6a.distances[[i]] <span class="sc">/</span> bandwidth)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb501-5"><a href="applications-of-spatial-weights.html#cb501-5" tabindex="-1"></a>  k6a.distances[[i]] <span class="ot">&lt;-</span> new_row</span>
<span id="cb501-6"><a href="applications-of-spatial-weights.html#cb501-6" tabindex="-1"></a>}</span>
<span id="cb501-7"><a href="applications-of-spatial-weights.html#cb501-7" tabindex="-1"></a>k6a.distances[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 0.7394859 0.1065641 0.6545807 0.5050934 0.2979544 0.0000000</code></pre>
<p>Now we create the weights structure with <code>nb2listw</code>, and directly assign the weights values
to the neighbors structure with <code>glist =</code>.</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="applications-of-spatial-weights.html#cb503-1" tabindex="-1"></a>epan.weights <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k6a,<span class="at">glist =</span> k6a.distances,<span class="at">style =</span> <span class="st">&quot;B&quot;</span>)</span>
<span id="cb503-2"><a href="applications-of-spatial-weights.html#cb503-2" tabindex="-1"></a>epan.weights<span class="sc">$</span>weights[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 0.7394859 0.1065641 0.6545807 0.5050934 0.2979544 0.0000000</code></pre>
<p>Lastly, we use <code>lag.listw</code> to create the lag variable from our Epanechnikov kernal weights, then take a
brief look at the resulting lag variable, <strong>epalag</strong>.</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="applications-of-spatial-weights.html#cb505-1" tabindex="-1"></a>epalag <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(epan.weights, clev.points<span class="sc">$</span>sale_price)</span>
<span id="cb505-2"><a href="applications-of-spatial-weights.html#cb505-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(clev.points<span class="sc">$</span>sale_price,epalag)</span>
<span id="cb505-3"><a href="applications-of-spatial-weights.html#cb505-3" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">clev.points.sale_price</th>
<th align="right">epalag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">235500</td>
<td align="right">210839.48</td>
</tr>
<tr class="even">
<td align="right">65000</td>
<td align="right">320223.68</td>
</tr>
<tr class="odd">
<td align="right">92000</td>
<td align="right">62295.77</td>
</tr>
<tr class="even">
<td align="right">5000</td>
<td align="right">272183.78</td>
</tr>
<tr class="odd">
<td align="right">116250</td>
<td align="right">189258.60</td>
</tr>
<tr class="even">
<td align="right">120000</td>
<td align="right">99958.83</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[[W_y]_i = \Sigma_jK_{ij}y_j\]</span></p>
</div>
<div id="spatial-rate-smoothing" class="section level2 unnumbered hasAnchor">
<h2>Spatial rate smoothing<a href="applications-of-spatial-weights.html#spatial-rate-smoothing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="principle-1" class="section level3 unnumbered hasAnchor">
<h3>Principle<a href="applications-of-spatial-weights.html#principle-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A spatial rate smoother is a special case of a nonparameteric rate estimator, based on
the principle of locally weighted estimation. Rather than applying a local average to
the rate itself, as in an application of a spatial window average, the weighted
average is applied separately to the numerator and denominator.</p>
<p>The spatially smoothed rate for a given location i
is then given as:</p>
<p><span class="math display">\[\pi_i = \frac{\Sigma_{j=1}^nw_{ij}O_j} {\Sigma_{j=1}^nw_{ij}P_j}\]</span></p>
<p>where <span class="math inline">\(O_j\)</span> is the event count in location j, <span class="math inline">\(P_j\)</span> is the population at risk,
and <span class="math inline">\(w_{ij}\)</span> are spatial weights (typically with <span class="math inline">\(w_{ii} = 0\)</span>, i.e. including the
diagonal)</p>
<p>Different smoothers are obtained for different spatial definitions of neighbors and/or
different weights applied to those neighbors (e.g., contiguity weights, inverse
distance weights, or kernel weights).</p>
<p>The window average is not applied to the rate itself, but it is computed separately for the
numerator and denominator. The simplest case boils down to applying the idea of a spatial
window sum to the numerator and denominator (i.e., with binary spatial weights in both, and
including the diagonal term):
<span class="math display">\[\pi_i = \frac{O_i + \Sigma_{j=1}^nO_j} {O_i +\Sigma_{j=1}^nP_j}\]</span>
<span class="math inline">\(\pi_i = \frac{O_i+\Sigma_{j=1}^J_iO_j}{O_i + \Sigma_{j=1}^J_iP_j}\)</span></p>
<p>where <span class="math inline">\(J_i\)</span> is a reference set (neighbors) for observation i. In practice, this is achieved by
using binary spatial weights for both numerator and denominator, and including the diagonal in
both terms, as in the expression above.</p>
<p>A map of spatially smoothed rates tends to emphasize broad spatial trends and is
useful for identifying general features of the data. However, it is not useful for the
analysis of spatial autocorrelation, since the smoothed rates are autocorrelated by
construction. It is also not very useful for identifying outlying observations, since
the values portrayed are really regional averages and not specific to an individual
location. By construction, the values shown for individual locations are determined by
both the events and the population sizes of adjoining spatial units, which can lead to
misleading impressions. Often, inverse distance weights are applied to both the
numerator and denominator</p>
</div>
<div id="preliminaries-9" class="section level3 unnumbered hasAnchor">
<h3>Preliminaries<a href="applications-of-spatial-weights.html#preliminaries-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We return to the rate smoothing examples using the Ohio county lung cancer data.
Therefore, we need to close the current project and load the ohlung data set.</p>
<p>Next, we need to create the spatial weights files we will use if we don’t have them
already stored in a project file. In order to make sure that some smoothing will
occur, we take a fairly wide definition of neighbors. Specifically, we will create a
second order queen contiguity, inclusive of first order neighbors, inverse distance
weights based on knn = 10 nearest neighbor weights, and Epanechnikov kernel weights,
using the same 10 nearest neighbors and with the kernel applied to the diagonal (its
value will be 0.75).</p>
<p>To proceed, we will be using procedures outlined in earlier notebooks to create the
weights. The process will be less in depth than the ones in the distance and
contiguity weight notebooks, but will be enough to make and review the process
of making the weights.</p>
<div id="geodadata-4" class="section level4 unnumbered hasAnchor">
<h4>geodaData<a href="applications-of-spatial-weights.html#geodadata-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>All of the data for the R notebooks is available in the <strong>geodaData</strong>
package. We loaded the library earlier, now to access the individual
data sets, we use the double colon notation. This works similar to
to accessing a variable with <code>$</code>, in that a drop down menu will
appear with a list of the datasets included in the package. For this
notebook, we use <code>ohio_lung</code>.</p>
<p>Otherwise, to get the data for this notebook, you will need to go to <a href="https://geodacenter.github.io/data-and-lab/ohiolung/">Ohio Lung Cancer</a> The download format is a
zipfile, so you will need to unzip it by double clicking on the file in your file
finder. From there move the resulting folder titled: nyc into your working directory
to continue. Once that is done, you can use the <strong>sf</strong> function: <code>st_read()</code> to read
the shapefile into your R environment.</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="applications-of-spatial-weights.html#cb506-1" tabindex="-1"></a>ohio_lung <span class="ot">&lt;-</span> geodaData<span class="sc">::</span>ohio_lung</span></code></pre></div>
</div>
<div id="creating-a-crude-rate" class="section level4 unnumbered hasAnchor">
<h4>Creating a Crude Rate<a href="applications-of-spatial-weights.html#creating-a-crude-rate" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In addition to the spatial weights, we also need an example for crude rates. If not
already saved in the data set, we compute the crude rate for lung cancer among white
females in 68.</p>
<p>To get the rate we make a new variable, <strong>LRATE</strong> and calculated the rate through
bivariate operation. We multiply the ratio by 10,000 to the crude rate of lung cancer
per 10,000 white women in 1968.</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="applications-of-spatial-weights.html#cb507-1" tabindex="-1"></a>ohio_lung<span class="sc">$</span>LRATE <span class="ot">&lt;-</span> ohio_lung<span class="sc">$</span>LFW68 <span class="sc">/</span> ohio_lung<span class="sc">$</span>POPFW68 <span class="sc">*</span> <span class="dv">10000</span></span></code></pre></div>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="applications-of-spatial-weights.html#cb508-1" tabindex="-1"></a><span class="fu">tm_shape</span>(ohio_lung) <span class="sc">+</span></span>
<span id="cb508-2"><a href="applications-of-spatial-weights.html#cb508-2" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;LRATE&quot;</span>,<span class="at">palette =</span> <span class="st">&quot;-RdBu&quot;</span>,<span class="at">style =</span><span class="st">&quot;sd&quot;</span>,<span class="at">title =</span> <span class="st">&quot;Standard Deviation: LRATE&quot;</span>) <span class="sc">+</span></span>
<span id="cb508-3"><a href="applications-of-spatial-weights.html#cb508-3" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span> </span>
<span id="cb508-4"><a href="applications-of-spatial-weights.html#cb508-4" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>, <span class="at">legend.outside.position =</span> <span class="st">&quot;right&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-365-1.png" width="672" /></p>
</div>
<div id="creating-the-weights-1" class="section level4 unnumbered hasAnchor">
<h4>Creating the Weights<a href="applications-of-spatial-weights.html#creating-the-weights-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="queen-contiguity-1" class="section level5 unnumbered hasAnchor">
<h5>Queen Contiguity<a href="applications-of-spatial-weights.html#queen-contiguity-1" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>To create the queen contiguity weights, we will use the <strong>spdep</strong> package and <strong>sf</strong>
package to make a neighbors list with both first and second order neighbors
included.</p>
<p>To begin we create a queen contiguity function with the corresponding pattern. We
use the <code>st_relate</code> function to accomplish this. For a more in depth explanation
of the specified pattern, check the contiguity based weights notebook.</p>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="applications-of-spatial-weights.html#cb509-1" tabindex="-1"></a>st_queen <span class="ot">&lt;-</span> <span class="cf">function</span>(a, <span class="at">b =</span> a) <span class="fu">st_relate</span>(a, b, <span class="at">pattern =</span> <span class="st">&quot;F***T****&quot;</span>)</span></code></pre></div>
<p>Here we define a function needed to convert the resulting data structure from the
<code>st_relate</code> function. Specifically from <strong>sgbp</strong> to <strong>nb</strong>. It’s fairly
straightforward, we just change the class name, transfer the attributes,
and check for observations without a neighbor.</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="applications-of-spatial-weights.html#cb510-1" tabindex="-1"></a>as.nb.sgbp <span class="ot">&lt;-</span> <span class="cf">function</span>(x, ...) {</span>
<span id="cb510-2"><a href="applications-of-spatial-weights.html#cb510-2" tabindex="-1"></a>  attrs <span class="ot">&lt;-</span> <span class="fu">attributes</span>(x)</span>
<span id="cb510-3"><a href="applications-of-spatial-weights.html#cb510-3" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">lapply</span>(x, <span class="cf">function</span>(i) { <span class="cf">if</span>(<span class="fu">length</span>(i) <span class="sc">==</span> 0L) 0L <span class="cf">else</span> i } )</span>
<span id="cb510-4"><a href="applications-of-spatial-weights.html#cb510-4" tabindex="-1"></a>  <span class="fu">attributes</span>(x) <span class="ot">&lt;-</span> attrs</span>
<span id="cb510-5"><a href="applications-of-spatial-weights.html#cb510-5" tabindex="-1"></a>  <span class="fu">class</span>(x) <span class="ot">&lt;-</span> <span class="st">&quot;nb&quot;</span></span>
<span id="cb510-6"><a href="applications-of-spatial-weights.html#cb510-6" tabindex="-1"></a>  x</span>
<span id="cb510-7"><a href="applications-of-spatial-weights.html#cb510-7" tabindex="-1"></a>}</span></code></pre></div>
<p>Now we create a comprehnsive neighbors list with both first and second order
neighbors. To start, we use the two functions we created to get a 1st order
neighbors list, then we use <code>nblag</code> to get the first and second order neighbors. The
next step is reoragnize the data structre so that first and second order neighbors
are not separated, this is done with <code>nblag_cumul</code>. With these steps, we have a
neighbors list of first and second order neighbors.</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="applications-of-spatial-weights.html#cb511-1" tabindex="-1"></a>queen.sgbp <span class="ot">&lt;-</span> <span class="fu">st_queen</span>(ohio_lung)</span>
<span id="cb511-2"><a href="applications-of-spatial-weights.html#cb511-2" tabindex="-1"></a>queen.nb <span class="ot">&lt;-</span> <span class="fu">as.nb.sgbp</span>(queen.sgbp)</span>
<span id="cb511-3"><a href="applications-of-spatial-weights.html#cb511-3" tabindex="-1"></a>second.order.queen <span class="ot">&lt;-</span> <span class="fu">nblag</span>(queen.nb, <span class="dv">2</span>)</span>
<span id="cb511-4"><a href="applications-of-spatial-weights.html#cb511-4" tabindex="-1"></a>second.order.queen.cumul <span class="ot">&lt;-</span> <span class="fu">nblag_cumul</span>(second.order.queen)</span></code></pre></div>
<p>Here we add the diagonal elements to the neighbors list because we will need them
later on in computations.</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="applications-of-spatial-weights.html#cb512-1" tabindex="-1"></a><span class="fu">include.self</span>(second.order.queen.cumul)</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 88 
## Number of nonzero links: 1376 
## Percentage nonzero weights: 17.7686 
## Average number of links: 15.63636</code></pre>
<p>Now, we just use the <code>nb2listw</code> function to convert the neighbors list to a
weights structure, which is row-standardized by default.</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="applications-of-spatial-weights.html#cb514-1" tabindex="-1"></a>queen.weights <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(second.order.queen.cumul)</span>
<span id="cb514-2"><a href="applications-of-spatial-weights.html#cb514-2" tabindex="-1"></a>queen.weights<span class="sc">$</span>weights[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>##  [1] 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1</code></pre>
</div>
<div id="k-nearest-neighbors" class="section level5 unnumbered hasAnchor">
<h5>K-nearest neighbors<a href="applications-of-spatial-weights.html#k-nearest-neighbors" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Here we will make the inverse distance weights for the 10th-nearest neighbors. To
start, we need the coordinates in a separate data structure before we can proceed
with the neighbor and distance calculations. We use the same method to extract these
values as the distance-band weights notebook.</p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="applications-of-spatial-weights.html#cb516-1" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(ohio_lung<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span>
<span id="cb516-2"><a href="applications-of-spatial-weights.html#cb516-2" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(ohio_lung<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span>
<span id="cb516-3"><a href="applications-of-spatial-weights.html#cb516-3" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span></code></pre></div>
<p>From here we just use <code>knearneigh</code> and <code>knn2nb</code> to get our neighbors structure.</p>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="applications-of-spatial-weights.html#cb517-1" tabindex="-1"></a>k10 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k =</span> <span class="dv">10</span>))</span></code></pre></div>
<p>Now we need the distances between each observation and its neighbors. Having this will
allow us to calculate the inverse later and assign these values as weights when
converting the neighbors structure to a weights structure.</p>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="applications-of-spatial-weights.html#cb518-1" tabindex="-1"></a>k10.dists <span class="ot">&lt;-</span> <span class="fu">nbdists</span>(k10,coords)</span></code></pre></div>
<p>Here we apply a function to the distances of the 10th nearest neighbors and change
the scale by an order of 10,000. The purpose of changing the scale is to get
weight values that are not approximently zero.</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb519-1"><a href="applications-of-spatial-weights.html#cb519-1" tabindex="-1"></a>invdk10 <span class="ot">&lt;-</span> <span class="fu">lapply</span>(k10.dists, <span class="cf">function</span>(x) (<span class="dv">1</span><span class="sc">/</span>(x<span class="sc">/</span><span class="dv">10000</span>)))</span>
<span id="cb519-2"><a href="applications-of-spatial-weights.html#cb519-2" tabindex="-1"></a>invdk10[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [[1]]
##  [1] 0.2537074 0.1289088 0.2415022 0.3469379 0.1935753 0.2138694 0.1299890
##  [8] 0.1415348 0.1449763 0.1291574</code></pre>
<p>With the <code>nb2listw</code> function, we can assign non-default weights to the new weights
structure by means of the <code>glist</code> argument. Here we just assign the scaled inverse
weights we created above.</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb521-1"><a href="applications-of-spatial-weights.html#cb521-1" tabindex="-1"></a>k10.weights <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k10,<span class="at">glist =</span> invdk10, <span class="at">style =</span> <span class="st">&quot;B&quot;</span>)</span>
<span id="cb521-2"><a href="applications-of-spatial-weights.html#cb521-2" tabindex="-1"></a>k10.weights<span class="sc">$</span>weights[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>##  [1] 0.2537074 0.1289088 0.2415022 0.3469379 0.1935753 0.2138694 0.1299890
##  [8] 0.1415348 0.1449763 0.1291574</code></pre>
</div>
<div id="epanechnikov-kernel" class="section level5 unnumbered hasAnchor">
<h5>Epanechnikov kernel<a href="applications-of-spatial-weights.html#epanechnikov-kernel" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>For the Epanechnikov kernal weights, things are a bit more complicated, as we need
to add in diagonal elements. This is best done with neighbors list.</p>
<p>We start with the 10-nearest neighbors and assign to a new object because we will
be altering the structure to get the resulting weights.</p>
<p>This gives us the distances between neighbors in the same structure as the neighbors
list.</p>
<div class="sourceCode" id="cb523"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb523-1"><a href="applications-of-spatial-weights.html#cb523-1" tabindex="-1"></a>k10.distances <span class="ot">&lt;-</span> <span class="fu">nbdists</span>(k10,coords)</span></code></pre></div>
<p>This four loop gives us the epanechnikov weights in the the distance data structure
that we computed above.</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="applications-of-spatial-weights.html#cb524-1" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(k10.distances)){</span>
<span id="cb524-2"><a href="applications-of-spatial-weights.html#cb524-2" tabindex="-1"></a>  maxk10 <span class="ot">&lt;-</span> <span class="fu">max</span>(k10.distances[[i]])</span>
<span id="cb524-3"><a href="applications-of-spatial-weights.html#cb524-3" tabindex="-1"></a>  bandwidth <span class="ot">&lt;-</span> maxk10</span>
<span id="cb524-4"><a href="applications-of-spatial-weights.html#cb524-4" tabindex="-1"></a>  new_row <span class="ot">&lt;-</span> .<span class="dv">75</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>(k10.distances[[i]] <span class="sc">/</span> bandwidth)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb524-5"><a href="applications-of-spatial-weights.html#cb524-5" tabindex="-1"></a>  k10.distances[[i]] <span class="ot">&lt;-</span> new_row</span>
<span id="cb524-6"><a href="applications-of-spatial-weights.html#cb524-6" tabindex="-1"></a>}</span>
<span id="cb524-7"><a href="applications-of-spatial-weights.html#cb524-7" tabindex="-1"></a>k10.distances[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>##  [1] 0.556375699 0.000000000 0.536310124 0.646456537 0.417397027 0.477523632
##  [7] 0.012413252 0.127843776 0.157031189 0.002884936</code></pre>
<p>Now we can assign our epanechnikov weight values as weights with the <code>nb2listw</code> function throught the <code>glist =</code> parameter.</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="applications-of-spatial-weights.html#cb526-1" tabindex="-1"></a>epan.weights <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(k10,<span class="at">glist =</span> k10.distances,<span class="at">style =</span> <span class="st">&quot;B&quot;</span>)</span>
<span id="cb526-2"><a href="applications-of-spatial-weights.html#cb526-2" tabindex="-1"></a>epan.weights<span class="sc">$</span>weights[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>##  [1] 0.556375699 0.000000000 0.536310124 0.646456537 0.417397027 0.477523632
##  [7] 0.012413252 0.127843776 0.157031189 0.002884936</code></pre>
</div>
</div>
</div>
<div id="simple-window-average-of-rates" class="section level3 unnumbered hasAnchor">
<h3>Simple window average of rates<a href="applications-of-spatial-weights.html#simple-window-average-of-rates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This is an illustration of how not to proceed with the spatial rate calculation.
Here we use our crude rate and create a spatial lag variable directly from the second order queen contiguity weights.</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="applications-of-spatial-weights.html#cb528-1" tabindex="-1"></a>ohio_lung<span class="sc">$</span>W_LRATE <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights,ohio_lung<span class="sc">$</span>LRATE)</span></code></pre></div>
<p>We then plot <strong>W_LRATE</strong> with a standard deviation map.</p>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="applications-of-spatial-weights.html#cb529-1" tabindex="-1"></a><span class="fu">tm_shape</span>(ohio_lung) <span class="sc">+</span></span>
<span id="cb529-2"><a href="applications-of-spatial-weights.html#cb529-2" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;W_LRATE&quot;</span>,<span class="at">palette =</span> <span class="st">&quot;-RdBu&quot;</span>,<span class="at">style =</span><span class="st">&quot;sd&quot;</span>,<span class="at">title =</span> <span class="st">&quot;Standard Deviation: W_LRATE&quot;</span>) <span class="sc">+</span></span>
<span id="cb529-3"><a href="applications-of-spatial-weights.html#cb529-3" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span> </span>
<span id="cb529-4"><a href="applications-of-spatial-weights.html#cb529-4" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>, <span class="at">legend.outside.position =</span> <span class="st">&quot;right&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-380-1.png" width="672" /></p>
<p>Characteristic of the spatial averaging, several larger groupings of similarly
classified observations appear. The pattern is quite different from that displayed for
the crude rate. For example, the upper outliers have disappeared, and there is now one
new lower outlier.</p>
</div>
<div id="spatially-smoothed-rates" class="section level3 unnumbered hasAnchor">
<h3>Spatially Smoothed Rates<a href="applications-of-spatial-weights.html#spatially-smoothed-rates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As mentioned, applying the spatial averaging directly to the crude rates is not the proper way to operate. This approach ignores the differences between the populations of
the different counties and the associated variance instability of the rates.</p>
<p>To create the spatially smoothed rate, we need to make lag variables of the
event variable and base variable, then divide them to get our rate. In GeoDa
we just select our variables and the software does it for us, in R we need
some extra steps.</p>
<p>To get this rate we create lag variables for both population and event count with
<code>lag.listw</code>. To get the rate, we then divide the event count lag variable by the
the population lag variable.</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="applications-of-spatial-weights.html#cb530-1" tabindex="-1"></a>lag_lfw68 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights,ohio_lung<span class="sc">$</span>LFW68)</span>
<span id="cb530-2"><a href="applications-of-spatial-weights.html#cb530-2" tabindex="-1"></a>lag_popfw68 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights,ohio_lung<span class="sc">$</span>POPFW68)</span>
<span id="cb530-3"><a href="applications-of-spatial-weights.html#cb530-3" tabindex="-1"></a>ohio_lung<span class="sc">$</span>R_SPAT_R <span class="ot">&lt;-</span> lag_lfw68 <span class="sc">/</span> lag_popfw68</span></code></pre></div>
<p>We map the results with <strong>tmap</strong> functions.</p>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb531-1"><a href="applications-of-spatial-weights.html#cb531-1" tabindex="-1"></a><span class="fu">tm_shape</span>(ohio_lung) <span class="sc">+</span></span>
<span id="cb531-2"><a href="applications-of-spatial-weights.html#cb531-2" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;R_SPAT_R&quot;</span>,<span class="at">palette =</span> <span class="st">&quot;-RdBu&quot;</span>,<span class="at">style =</span><span class="st">&quot;sd&quot;</span>,<span class="at">title =</span> <span class="st">&quot;SRS-Smoothed LFW68 over POPFW68&quot;</span>) <span class="sc">+</span></span>
<span id="cb531-3"><a href="applications-of-spatial-weights.html#cb531-3" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span> </span>
<span id="cb531-4"><a href="applications-of-spatial-weights.html#cb531-4" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>, <span class="at">legend.outside.position =</span> <span class="st">&quot;right&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-382-1.png" width="672" /></p>
<p>We rescale the spatial rate variable by 10,000 to make it comparable to <strong>W_LRATE</strong>. Then we add all
of the rate to a data frame with <code>data.frame</code> and take a brief side by side look with <code>head</code> and <code>kable</code>.</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="applications-of-spatial-weights.html#cb532-1" tabindex="-1"></a>ohio_lung<span class="sc">$</span>R_SPAT_RT <span class="ot">&lt;-</span> ohio_lung<span class="sc">$</span>R_SPAT_R <span class="sc">*</span> <span class="dv">10000</span></span>
<span id="cb532-2"><a href="applications-of-spatial-weights.html#cb532-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">LRATE =</span> ohio_lung<span class="sc">$</span>LRATE,<span class="at">W_LRATE =</span> ohio_lung<span class="sc">$</span>W_LRATE,<span class="at">R_SPAT_RT=</span> ohio_lung<span class="sc">$</span>R_SPAT_RT)</span>
<span id="cb532-3"><a href="applications-of-spatial-weights.html#cb532-3" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">LRATE</th>
<th align="right">W_LRATE</th>
<th align="right">R_SPAT_RT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1.2266817</td>
<td align="right">0.6859424</td>
<td align="right">0.6787945</td>
</tr>
<tr class="even">
<td align="right">0.6113217</td>
<td align="right">0.7315576</td>
<td align="right">0.9793153</td>
</tr>
<tr class="odd">
<td align="right">0.9636697</td>
<td align="right">0.9364070</td>
<td align="right">1.0274976</td>
</tr>
<tr class="even">
<td align="right">0.0000000</td>
<td align="right">0.9414058</td>
<td align="right">1.0600851</td>
</tr>
<tr class="odd">
<td align="right">1.1988872</td>
<td align="right">1.1059237</td>
<td align="right">0.9678452</td>
</tr>
<tr class="even">
<td align="right">0.0000000</td>
<td align="right">1.0709655</td>
<td align="right">1.1050227</td>
</tr>
</tbody>
</table>
<p>To get a more quantifiable comparason the table above, we can make a scatterplot with <strong>gplot2</strong> functions.
We will not go into depth on the different options here, but will create a basic scatterplot of <strong>W_LRATE</strong>
and <strong>R_SPAT_RT</strong>. <code>geom_point</code> add the points to the plot, and <code>geom_smooth(method=lm)</code> add a linear
regression line.</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb533-1"><a href="applications-of-spatial-weights.html#cb533-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>ohio_lung,<span class="fu">aes</span>(<span class="at">x=</span>W_LRATE,<span class="at">y=</span>R_SPAT_RT)) <span class="sc">+</span></span>
<span id="cb533-2"><a href="applications-of-spatial-weights.html#cb533-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb533-3"><a href="applications-of-spatial-weights.html#cb533-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm) </span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-384-1.png" width="672" /></p>
<p><code>lm</code> calculates the associated regression statistics with the scatterplot above. We then use <code>tidy</code> and
<code>kable</code> to display these statistics in a neat table.</p>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="applications-of-spatial-weights.html#cb534-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(R_SPAT_RT <span class="sc">~</span> W_LRATE,<span class="at">data =</span> ohio_lung)</span>
<span id="cb534-2"><a href="applications-of-spatial-weights.html#cb534-2" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">tidy</span>(lmfit))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.4213586</td>
<td align="right">0.0613816</td>
<td align="right">6.864573</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">W_LRATE</td>
<td align="right">0.6421174</td>
<td align="right">0.0586340</td>
<td align="right">10.951276</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<div id="inverse-distance-smoothed-rate" class="section level4 unnumbered hasAnchor">
<h4>Inverse Distance Smoothed Rate<a href="applications-of-spatial-weights.html#inverse-distance-smoothed-rate" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For the inverse distance weights, we proceed with a different approach. The <strong>k10.weights</strong> do not
include diagonal elements, so we will need to address this in our computation of the rate. We begin
with the lag variables for population and event count with our inverse distance weights. To add the diagonal
element in our rate calculation, we add the event count variable to lag event count variable and do the
same with population before dividing to compute the rate. This works because the diagonal element would be assigned 1
in the weight structure and as a result would just add the original sale proce from the location to the lag sale price,
if originally included in the weight’s structure.</p>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="applications-of-spatial-weights.html#cb535-1" tabindex="-1"></a>lag_lfw68 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(k10.weights,ohio_lung<span class="sc">$</span>LFW68)</span>
<span id="cb535-2"><a href="applications-of-spatial-weights.html#cb535-2" tabindex="-1"></a>lag_popfw68 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(k10.weights,ohio_lung<span class="sc">$</span>POPFW68)</span>
<span id="cb535-3"><a href="applications-of-spatial-weights.html#cb535-3" tabindex="-1"></a>ohio_lung<span class="sc">$</span>ID_RATE <span class="ot">&lt;-</span> (lag_lfw68 <span class="sc">+</span> ohio_lung<span class="sc">$</span>LFW68)<span class="sc">/</span> (lag_popfw68 <span class="sc">+</span> ohio_lung<span class="sc">$</span>POPFW68) <span class="sc">*</span> <span class="dv">10000</span></span></code></pre></div>
<div class="sourceCode" id="cb536"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb536-1"><a href="applications-of-spatial-weights.html#cb536-1" tabindex="-1"></a><span class="fu">tm_shape</span>(ohio_lung) <span class="sc">+</span></span>
<span id="cb536-2"><a href="applications-of-spatial-weights.html#cb536-2" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;ID_RATE&quot;</span>,<span class="at">palette =</span> <span class="st">&quot;-RdBu&quot;</span>,<span class="at">style =</span><span class="st">&quot;sd&quot;</span>,<span class="at">title =</span> <span class="st">&quot;Standard Deviation IDRATE&quot;</span>) <span class="sc">+</span></span>
<span id="cb536-3"><a href="applications-of-spatial-weights.html#cb536-3" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span> </span>
<span id="cb536-4"><a href="applications-of-spatial-weights.html#cb536-4" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>, <span class="at">legend.outside.position =</span> <span class="st">&quot;right&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-387-1.png" width="672" /></p>
</div>
<div id="kernal-smoothed-rate" class="section level4 unnumbered hasAnchor">
<h4>Kernal Smoothed Rate<a href="applications-of-spatial-weights.html#kernal-smoothed-rate" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We follow the same process for the kernal weights calculation as the inverse distance, except rescale the diagonal
element by .75 as done in epanechnikov kernal function.</p>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="applications-of-spatial-weights.html#cb537-1" tabindex="-1"></a>lag_lfw68 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(epan.weights,ohio_lung<span class="sc">$</span>LFW68)</span>
<span id="cb537-2"><a href="applications-of-spatial-weights.html#cb537-2" tabindex="-1"></a>lag_popfw68 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(epan.weights,ohio_lung<span class="sc">$</span>POPFW68)</span>
<span id="cb537-3"><a href="applications-of-spatial-weights.html#cb537-3" tabindex="-1"></a>ohio_lung<span class="sc">$</span>KERN_RATE <span class="ot">&lt;-</span> (lag_lfw68 <span class="sc">+</span> .<span class="dv">75</span> <span class="sc">*</span> ohio_lung<span class="sc">$</span>LFW68)<span class="sc">/</span> (lag_popfw68 <span class="sc">+</span> .<span class="dv">75</span> <span class="sc">*</span> ohio_lung<span class="sc">$</span>POPFW68) <span class="sc">*</span> <span class="dv">10000</span></span>
<span id="cb537-4"><a href="applications-of-spatial-weights.html#cb537-4" tabindex="-1"></a>ohio_lung<span class="sc">$</span>KERN_RATE <span class="ot">&lt;-</span> lag_lfw68 <span class="sc">/</span> lag_popfw68 <span class="sc">*</span> <span class="dv">10000</span></span></code></pre></div>
<div class="sourceCode" id="cb538"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb538-1"><a href="applications-of-spatial-weights.html#cb538-1" tabindex="-1"></a><span class="fu">tm_shape</span>(ohio_lung) <span class="sc">+</span></span>
<span id="cb538-2"><a href="applications-of-spatial-weights.html#cb538-2" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;KERN_RATE&quot;</span>,<span class="at">palette =</span> <span class="st">&quot;-RdBu&quot;</span>,<span class="at">style =</span><span class="st">&quot;sd&quot;</span>,<span class="at">title =</span> <span class="st">&quot;Standard Deviation: KERN_RATE&quot;</span>) <span class="sc">+</span></span>
<span id="cb538-3"><a href="applications-of-spatial-weights.html#cb538-3" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span> </span>
<span id="cb538-4"><a href="applications-of-spatial-weights.html#cb538-4" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>, <span class="at">legend.outside.position =</span> <span class="st">&quot;right&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-389-1.png" width="672" /></p>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="applications-of-spatial-weights.html#cb539-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">ID_RATE =</span> ohio_lung<span class="sc">$</span>ID_RATE, <span class="at">KERN_RATE =</span> ohio_lung<span class="sc">$</span>KERN_RATE)</span>
<span id="cb539-2"><a href="applications-of-spatial-weights.html#cb539-2" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">LRATE</th>
<th align="right">W_LRATE</th>
<th align="right">R_SPAT_RT</th>
<th align="right">ID_RATE</th>
<th align="right">KERN_RATE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1.2266817</td>
<td align="right">0.6859424</td>
<td align="right">0.6787945</td>
<td align="right">1.1004473</td>
<td align="right">0.4102768</td>
</tr>
<tr class="even">
<td align="right">0.6113217</td>
<td align="right">0.7315576</td>
<td align="right">0.9793153</td>
<td align="right">0.9106611</td>
<td align="right">0.9880350</td>
</tr>
<tr class="odd">
<td align="right">0.9636697</td>
<td align="right">0.9364070</td>
<td align="right">1.0274976</td>
<td align="right">1.0250171</td>
<td align="right">1.0632788</td>
</tr>
<tr class="even">
<td align="right">0.0000000</td>
<td align="right">0.9414058</td>
<td align="right">1.0600851</td>
<td align="right">0.7552625</td>
<td align="right">0.9394942</td>
</tr>
<tr class="odd">
<td align="right">1.1988872</td>
<td align="right">1.1059237</td>
<td align="right">0.9678452</td>
<td align="right">1.1197279</td>
<td align="right">0.8257277</td>
</tr>
<tr class="even">
<td align="right">0.0000000</td>
<td align="right">1.0709655</td>
<td align="right">1.1050227</td>
<td align="right">0.8583623</td>
<td align="right">1.0165777</td>
</tr>
</tbody>
</table>
<p>It is important to keep in mind that both the inverse distance and kernel weights spatially smoothed rates are based on a
particular trade-off between the value at the location and its neighbors. This trade-off depends critically on the distance
metric used in the calculations (or, on the scale in which the coordinates are expressed). There is no right answer, and a
thorough sensitivity analysis is advised.</p>
<p>For example, we can observe that the three spatially smoothed maps point to some elevated rates in
the south of the state, but the extent of the respective regions and the counties on which they are centered differ slightly.
Also, the general regional patterns are roughly the same, but there are important differences in terms of the specific
counties affected.</p>
</div>
</div>
</div>
<div id="spatial-empirical-bayes-smoothing" class="section level2 unnumbered hasAnchor">
<h2>Spatial Empirical Bayes smoothing<a href="applications-of-spatial-weights.html#spatial-empirical-bayes-smoothing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="principle-2" class="section level3 unnumbered hasAnchor">
<h3>Principle<a href="applications-of-spatial-weights.html#principle-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The second option for spatial rate smoothing is Spatial Empirical Bayes. This
operates in the same way as the standard Empirical Bayes smoother (covered in the
rate mapping Chapter), except that the reference rate is computed for a spatial
window for each individual observation, rather than taking the same overall
reference rate for all. This only works well for larger data sets, when the window
(as defined by the spatial weights) is large enough to allow for effective
smoothing.</p>
<p>Similar to the standard EB principle, a reference rate (or prior) is computed.
However, here, this rate is estimated from the spatial window surrounding a given
observation, consisting of the observation and its neighbors. The neighbors are
defined by the non-zero elements in the row of the spatial weight matrix (i.e.,
the spatial weights are treated as binary).</p>
<p>Formally, the reference mean for location i is then:</p>
<p><span class="math display">\[\mu_i = \frac{\Sigma_jw_{ij}O_j}{\Sigma_jw_{ij}P_j}\]</span></p>
<p>with <span class="math inline">\(w_{ij}\)</span> as binary spatial weights, and <span class="math inline">\(w_{ii}=1\)</span></p>
<p>The local estimate of the prior variance follows the same logic as for EB, but replacing the population and rates by their local counterparts:</p>
<p><span class="math display">\[\sigma_i^2 = \frac{\Sigma_jw_{ij}[P_j(r_i - \mu_i)^2]}{\Sigma_jw_{ij}P_j} - \frac{\mu_i}{\Sigma_jw_{ij}P_i/(k_i +1)}\]</span></p>
<p>Note that the average population in the second term pertains to all locations within
the window, therefore, this is divided by <span class="math inline">\(k_i +1\)</span>(with <span class="math inline">\(k_i\)</span> as the number of
neighbors of i). As in the case of the standard EB rate, it is quite possible (and
quite common) to obtain a negative estimate for the local variance, in which case it is
set to zero.</p>
<p>The spatial EB smoothed rate is computed as a weighted average of the crude rate and
the prior, in the same manner as for the standard EB rate</p>
<p>For reference the EB rate in this case is as denoted below:</p>
<p><span class="math display">\[w_i = \frac{\sigma_i^2}{\sigma_i^2 + \mu_i / P_i}\]</span></p>
<p><span class="math display">\[\pi_i^{EB}= w_ir_i + (1-w_i)\theta\]</span></p>
</div>
<div id="spatial-eb-rate-smoother" class="section level3 unnumbered hasAnchor">
<h3>Spatial EB rate smoother<a href="applications-of-spatial-weights.html#spatial-eb-rate-smoother" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The spatial Empirical Bayes is included in the <strong>spdep</strong> package. It even has a <code>geoda =</code> that calculates the rate in the same manner as GeoDa. To do this, we use the <code>EBlocal</code> function from <strong>spdep</strong> and input the two variables with a neighbors
list. We then set <code>geoda =</code> to be TRUE.</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="applications-of-spatial-weights.html#cb540-1" tabindex="-1"></a>eb_risk <span class="ot">&lt;-</span> <span class="fu">EBlocal</span>(ohio_lung<span class="sc">$</span>LFW68, ohio_lung<span class="sc">$</span>POPFW68, second.order.queen.cumul, <span class="at">geoda =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>With our Empirical Bayes calculation, we can now examine it with a choropleth map.
Before we proceed, we add <strong>eb_risk</strong> to the data frame. We need to select the <strong>est</strong>
not the <strong>raw</strong> to get the correct figures.</p>
<div class="sourceCode" id="cb541"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb541-1"><a href="applications-of-spatial-weights.html#cb541-1" tabindex="-1"></a>ohio_lung <span class="ot">&lt;-</span> ohio_lung <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">eb_risk =</span> eb_risk<span class="sc">$</span>est)</span>
<span id="cb541-2"><a href="applications-of-spatial-weights.html#cb541-2" tabindex="-1"></a><span class="fu">tm_shape</span>(ohio_lung) <span class="sc">+</span></span>
<span id="cb541-3"><a href="applications-of-spatial-weights.html#cb541-3" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;eb_risk&quot;</span>,<span class="at">palette =</span> <span class="st">&quot;-RdBu&quot;</span>,<span class="at">style =</span><span class="st">&quot;sd&quot;</span>,<span class="at">title =</span> <span class="st">&quot;SEBS-Smoothed LFW68 over POPFW68&quot;</span>) <span class="sc">+</span></span>
<span id="cb541-4"><a href="applications-of-spatial-weights.html#cb541-4" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span> </span>
<span id="cb541-5"><a href="applications-of-spatial-weights.html#cb541-5" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>, <span class="at">legend.outside.position =</span> <span class="st">&quot;right&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-392-1.png" width="672" /></p>
<p>We do the same for the 10-nearest neighbors:</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb542-1"><a href="applications-of-spatial-weights.html#cb542-1" tabindex="-1"></a>eb_risk_k10 <span class="ot">&lt;-</span> <span class="fu">EBlocal</span>(ohio_lung<span class="sc">$</span>LFW68, ohio_lung<span class="sc">$</span>POPFW68, k10, <span class="at">geoda =</span> <span class="cn">TRUE</span>)</span>
<span id="cb542-2"><a href="applications-of-spatial-weights.html#cb542-2" tabindex="-1"></a>ohio_lung <span class="ot">&lt;-</span> ohio_lung <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">eb_risk_k10 =</span> eb_risk_k10<span class="sc">$</span>est)</span>
<span id="cb542-3"><a href="applications-of-spatial-weights.html#cb542-3" tabindex="-1"></a><span class="fu">tm_shape</span>(ohio_lung) <span class="sc">+</span></span>
<span id="cb542-4"><a href="applications-of-spatial-weights.html#cb542-4" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;eb_risk_k10&quot;</span>,<span class="at">palette =</span> <span class="st">&quot;-RdBu&quot;</span>,<span class="at">style =</span><span class="st">&quot;sd&quot;</span>,<span class="at">title =</span> <span class="st">&quot;SEBS-Smoothed LFW68 over POPFW68&quot;</span>) <span class="sc">+</span></span>
<span id="cb542-5"><a href="applications-of-spatial-weights.html#cb542-5" tabindex="-1"></a>  <span class="fu">tm_borders</span>() <span class="sc">+</span> </span>
<span id="cb542-6"><a href="applications-of-spatial-weights.html#cb542-6" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>, <span class="at">legend.outside.position =</span> <span class="st">&quot;right&quot;</span>)</span></code></pre></div>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-393-1.png" width="672" /></p>
<p>As for the spatial rate smoothing approaches, a careful sensitivity analysis is in
order. The results depend considerably on the range used for the reference rate. The
larger the range, the more the smoothed rates will be similar to the global EB rate.
For a narrow range, the estimate of the local variance will often result in a zero
imputed value, which makes the EB approach less meaningful.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="25">
<li id="fn25"><p>Use <code>setwd(directorypath)</code> to specify the working directory.<a href="applications-of-spatial-weights.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>Use
<code>install.packages(packagename)</code>.<a href="applications-of-spatial-weights.html#fnref26" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="spatial-weights-as-distance-functions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="global-spatial-autocorrelation-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/spatialanalysis/handsonspatialdata/edit/master/09-applications-of-spatial-weights.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
