<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Global Spatial Autocorrelation 2 | Hands-On Spatial Data Science with R</title>
  <meta name="description" content="Chapter 11 Global Spatial Autocorrelation 2 | Hands-On Spatial Data Science with R" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Global Spatial Autocorrelation 2 | Hands-On Spatial Data Science with R" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="spatialanalysis/handsonspatialdata" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Global Spatial Autocorrelation 2 | Hands-On Spatial Data Science with R" />
  
  
  

<meta name="author" content="Luc Anselin, Grant Morrison, Angela Li, Karina Acosta" />


<meta name="date" content="2023-10-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="global-spatial-autocorrelation-1.html"/>
<link rel="next" href="local-spatial-autocorrelation-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.2.0/leaflet.js"></script>
<script src="libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.2.0/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i>Disclaimer</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#using-this-book"><i class="fa fa-check"></i>Using This Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#who-this-book-is-for"><i class="fa fa-check"></i>Who This Book Is For</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html"><i class="fa fa-check"></i><b>1</b> Spatial Data Handling</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#introduction-1"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#objectives"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#preliminaries"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#loading-packages"><i class="fa fa-check"></i>Loading packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#obtaining-data-from-the-chicago-open-data-portal"><i class="fa fa-check"></i>Obtaining data from the Chicago Open Data portal</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#selecting-observations-for-a-given-time-period"><i class="fa fa-check"></i>Selecting Observations for a Given Time Period</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-observations-for-the-desired-time-period"><i class="fa fa-check"></i>Extracting observations for the desired time period</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#selecting-the-variables-for-the-final-table"><i class="fa fa-check"></i>Selecting the variables for the final table</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-point-layer"><i class="fa fa-check"></i>Creating a Point Layer</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-point-layer-from-coordinates-in-a-table---principle"><i class="fa fa-check"></i>Creating a point layer from coordinates in a table - principle</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-spatial-points-object"><i class="fa fa-check"></i>Creating a spatial points object</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#abandoned-vehicles-by-community-area"><i class="fa fa-check"></i>Abandoned Vehicles by Community Area</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#community-area-boundary-file"><i class="fa fa-check"></i>Community Area boundary file</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#spatial-join"><i class="fa fa-check"></i>Spatial join</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#counts-by-community-area"><i class="fa fa-check"></i>Counts by community area</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#mapping-the-vehicle-counts"><i class="fa fa-check"></i>Mapping the vehicle counts</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#community-area-population-data"><i class="fa fa-check"></i>Community Area Population Data</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-a-pdf-file"><i class="fa fa-check"></i>Extracting a pdf file</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#parsing-the-pdf-file"><i class="fa fa-check"></i>Parsing the pdf file</a></li>
<li class="chapter" data-level="1.0.1" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-the-population-values"><i class="fa fa-check"></i><b>1.0.1</b> Extracting the population values</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-data-frame-with-population-values"><i class="fa fa-check"></i>Creating a data frame with population values</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#mapping-community-area-abandoned-vehicles-per-capita"><i class="fa fa-check"></i>Mapping Community Area Abandoned Vehicles Per Capita</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#computing-abandoned-vehicles-per-capita"><i class="fa fa-check"></i>Computing abandoned vehicles per capita</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#final-choropleth-map"><i class="fa fa-check"></i>Final choropleth map</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html"><i class="fa fa-check"></i><b>2</b> Exploratory Data Analysis 1</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#introduction-2"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#objectives-1"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#preliminaries-1"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#load-packages"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#obtaining-the-data"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#analyzing-the-distribution-of-a-single-variable"><i class="fa fa-check"></i>Analyzing the Distribution of a Single Variable</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#a-quick-introduction-to-ggplot"><i class="fa fa-check"></i>A quick introduction to <strong>ggplot</strong></a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#bivariate-analysis-the-scatter-plot"><i class="fa fa-check"></i>Bivariate Analysis: The Scatter Plot</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#smoothing-the-scatter-plot"><i class="fa fa-check"></i>Smoothing the scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#spatial-heterogeneity"><i class="fa fa-check"></i>Spatial heterogeneity</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#structural-breaks-in-the-scatter-plot"><i class="fa fa-check"></i>Structural breaks in the scatter plot</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#chow-test"><i class="fa fa-check"></i>Chow test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html"><i class="fa fa-check"></i><b>3</b> Exploratory Data Analysis 2</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#introduction-3"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#objectives-2"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#preliminaries-2"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#load-packages-1"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#obtaining-the-data-1"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#scatter-plot-matrix"><i class="fa fa-check"></i>Scatter Plot Matrix</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#basic-scatter-plot-matrix"><i class="fa fa-check"></i>Basic scatter plot matrix</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#scatter-plot-matrix-with-smoothing"><i class="fa fa-check"></i>Scatter plot matrix with smoothing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#three-variables-bubble-chart-and-3d-scatter-plot"><i class="fa fa-check"></i>Three Variables: Bubble Chart and 3D Scatter Plot</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#bubble-chart"><i class="fa fa-check"></i>Bubble chart</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#d-scatter-plot"><i class="fa fa-check"></i>3D Scatter Plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#true-multivariate-eda-parallel-coordinate-plot-and-conditional-plots"><i class="fa fa-check"></i>True Multivariate EDA: Parallel Coordinate Plot and Conditional Plots</a>
<ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#parallel-coordinate-plot-pcp"><i class="fa fa-check"></i>Parallel Coordinate Plot (PCP)</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#conditional-plots"><i class="fa fa-check"></i>Conditional Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="basic-mapping.html"><a href="basic-mapping.html"><i class="fa fa-check"></i><b>4</b> Basic Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#introduction-4"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#objectives-3"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#preliminaries-3"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#load-packages-2"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#obtaining-the-data-2"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#basic-choropleth-mapping"><i class="fa fa-check"></i>Basic Choropleth Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#default-settings-1"><i class="fa fa-check"></i>Default settings</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#color-palette"><i class="fa fa-check"></i>Color palette</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#legend"><i class="fa fa-check"></i>Legend</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#title"><i class="fa fa-check"></i>Title</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#border-options"><i class="fa fa-check"></i>Border options</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#interactive-base-map"><i class="fa fa-check"></i>Interactive base map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#saving-a-map-as-a-file"><i class="fa fa-check"></i>Saving a map as a file</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#shape-centers"><i class="fa fa-check"></i>Shape centers</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#common-map-classifications"><i class="fa fa-check"></i>Common Map Classifications</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#quantile-map"><i class="fa fa-check"></i>Quantile map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#natural-breaks-map"><i class="fa fa-check"></i>Natural breaks map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#equal-intervals-map"><i class="fa fa-check"></i>Equal intervals map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#custom-breaks"><i class="fa fa-check"></i>Custom breaks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#extreme-value-maps"><i class="fa fa-check"></i>Extreme Value Maps</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#percentile-map"><i class="fa fa-check"></i>Percentile map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#box-map"><i class="fa fa-check"></i>Box map</a></li>
<li class="chapter" data-level="4.0.1" data-path="basic-mapping.html"><a href="basic-mapping.html#standard-deviation-map"><i class="fa fa-check"></i><b>4.0.1</b> Standard deviation map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#mapping-categorical-variables"><i class="fa fa-check"></i>Mapping Categorical Variables</a>
<ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#unique-value-map"><i class="fa fa-check"></i>Unique value map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#co-location-map"><i class="fa fa-check"></i>Co-location map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#conditional-map"><i class="fa fa-check"></i>Conditional Map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#cartogram"><i class="fa fa-check"></i>Cartogram</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rate-mapping.html"><a href="rate-mapping.html"><i class="fa fa-check"></i><b>5</b> Rate Mapping</a>
<ul>
<li class="chapter" data-level="" data-path="rate-mapping.html"><a href="rate-mapping.html#introduction-5"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="rate-mapping.html"><a href="rate-mapping.html#objectives-4"><i class="fa fa-check"></i><b>5.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="5.1" data-path="rate-mapping.html"><a href="rate-mapping.html#preliminaries-4"><i class="fa fa-check"></i><b>5.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="rate-mapping.html"><a href="rate-mapping.html#load-packages-3"><i class="fa fa-check"></i><b>5.1.1</b> Load packages</a></li>
<li class="chapter" data-level="5.1.2" data-path="rate-mapping.html"><a href="rate-mapping.html#geodadata"><i class="fa fa-check"></i><b>5.1.2</b> geodaData</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="rate-mapping.html"><a href="rate-mapping.html#choropleth-map-for-rates"><i class="fa fa-check"></i><b>5.2</b> Choropleth Map for Rates</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="rate-mapping.html"><a href="rate-mapping.html#spatially-extensive-and-intensive-variables"><i class="fa fa-check"></i><b>5.2.1</b> Spatially extensive and intensive variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="rate-mapping.html"><a href="rate-mapping.html#raw-rate-map"><i class="fa fa-check"></i><b>5.2.2</b> Raw rate map</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="rate-mapping.html"><a href="rate-mapping.html#excess-risk"><i class="fa fa-check"></i><b>5.3</b> Excess risk</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="rate-mapping.html"><a href="rate-mapping.html#relative-risk"><i class="fa fa-check"></i><b>5.3.1</b> Relative risk</a></li>
<li class="chapter" data-level="5.3.2" data-path="rate-mapping.html"><a href="rate-mapping.html#excess-risk-map"><i class="fa fa-check"></i><b>5.3.2</b> Excess risk map</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="rate-mapping.html"><a href="rate-mapping.html#empirical-bayes-smoothed-rate-map"><i class="fa fa-check"></i><b>5.4</b> Empirical Bayes Smoothed Rate Map</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="rate-mapping.html"><a href="rate-mapping.html#borrowing-strength"><i class="fa fa-check"></i><b>5.4.1</b> Borrowing strength</a></li>
<li class="chapter" data-level="5.4.2" data-path="rate-mapping.html"><a href="rate-mapping.html#bayes-law"><i class="fa fa-check"></i><b>5.4.2</b> Bayes law</a></li>
<li class="chapter" data-level="5.4.3" data-path="rate-mapping.html"><a href="rate-mapping.html#the-poisson-gamma-model"><i class="fa fa-check"></i><b>5.4.3</b> The Poisson-Gamma model</a></li>
<li class="chapter" data-level="5.4.4" data-path="rate-mapping.html"><a href="rate-mapping.html#the-empirical-bayes-approach"><i class="fa fa-check"></i><b>5.4.4</b> The Empirical Bayes approach</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="rate-mapping.html"><a href="rate-mapping.html#eb-rate-map"><i class="fa fa-check"></i><b>5.5</b> EB rate map</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html"><i class="fa fa-check"></i><b>6</b> Contiguity-Based Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#introduction-6"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#objectives-5"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#preliminaries-5"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#load-packages-4"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#geodadata-1"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#contiguity-weights"><i class="fa fa-check"></i>Contiguity Weights</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#rook-contiguity"><i class="fa fa-check"></i>Rook Contiguity</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#queen-contiguity"><i class="fa fa-check"></i>Queen Contiguity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#higher-order-contiguity"><i class="fa fa-check"></i>Higher Order Contiguity</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#visualizing-contiguity-neighbors"><i class="fa fa-check"></i>Visualizing Contiguity Neighbors</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#connectivity-graph"><i class="fa fa-check"></i>Connectivity Graph</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#connectivity-histogram"><i class="fa fa-check"></i>Connectivity Histogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#saving-neighbors"><i class="fa fa-check"></i>Saving Neighbors</a>
<ul>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#oldstyle"><i class="fa fa-check"></i>Oldstyle</a></li>
<li class="chapter" data-level="" data-path="contiguity-based-spatial-weights.html"><a href="contiguity-based-spatial-weights.html#geoda-header-format"><i class="fa fa-check"></i>GeoDA Header Format</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html"><i class="fa fa-check"></i><b>7</b> Distance-Based Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#introduction-7"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#objectives-6"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#preliminaries-6"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#load-packages-5"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#geodadata-2"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#visualizing-point-data"><i class="fa fa-check"></i>Visualizing point data</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#distance-band-weights"><i class="fa fa-check"></i>Distance-Band Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#concepts"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#creating-distance-band-weights"><i class="fa fa-check"></i>Creating distance-band weights</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#weights-characteristics"><i class="fa fa-check"></i>Weights characteristics</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#isolates"><i class="fa fa-check"></i>Isolates</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#k-nearest-neighbor-weights"><i class="fa fa-check"></i>K-Nearest Neighbor Weights</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#concept"><i class="fa fa-check"></i>Concept</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#creating-knn-weights"><i class="fa fa-check"></i>Creating KNN Weights</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#properties-of-knn-weights"><i class="fa fa-check"></i>Properties of KNN weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#generalizing-the-concept-of-contiguity"><i class="fa fa-check"></i>Generalizing the Concept of Contiguity</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#contiguity-based-weights-for-points"><i class="fa fa-check"></i>Contiguity-based weights for points</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#contiguity-weights-for-thiessen-polygons"><i class="fa fa-check"></i>Contiguity weights for Thiessen polygons</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#distance-based-weights-for-polygons"><i class="fa fa-check"></i>Distance-based weights for polygons</a>
<ul>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#getting-the-data"><i class="fa fa-check"></i>Getting the data</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-the-centroids"><i class="fa fa-check"></i>Computing the centroids</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-the-critical-threshold"><i class="fa fa-check"></i>Computing the critical threshold</a></li>
<li class="chapter" data-level="" data-path="distance-based-spatial-weights.html"><a href="distance-based-spatial-weights.html#computing-distance-band-neighbors"><i class="fa fa-check"></i>Computing distance-band neighbors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html"><i class="fa fa-check"></i><b>8</b> Spatial Weights as Distance Functions</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#introduction-8"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#objectives-7"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#preliminaries-7"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#load-packages-6"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#obtaining-the-data-from-the-geoda-website"><i class="fa fa-check"></i>Obtaining the Data from the GeoDa website</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#inverse-distance-weights"><i class="fa fa-check"></i>Inverse Distance Weights</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#concepts-1"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="8.0.1" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-inverse-distance-functions-for-distance-bands"><i class="fa fa-check"></i><b>8.0.1</b> Creating inverse distance functions for distance bands</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-inverse-distance-functions-for-k-nearest-neighbors"><i class="fa fa-check"></i>Creating inverse distance functions for k-nearest neighbors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#kernal-weights"><i class="fa fa-check"></i>Kernal Weights</a>
<ul>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#concepts-2"><i class="fa fa-check"></i>Concepts</a></li>
<li class="chapter" data-level="" data-path="spatial-weights-as-distance-functions.html"><a href="spatial-weights-as-distance-functions.html#creating-kernal-weights"><i class="fa fa-check"></i>Creating Kernal weights</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html"><i class="fa fa-check"></i><b>9</b> Applications of Spatial Weights</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#introduction-9"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#objectives-8"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#preliminaries-8"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#load-packages-7"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#geodadata-3"><i class="fa fa-check"></i>geodaData</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables"><i class="fa fa-check"></i>Spatially lagged variables</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#creating-a-spatially-lagged-variable"><i class="fa fa-check"></i>Creating a spatially lagged variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables-from-inverse-distance-weights"><i class="fa fa-check"></i>Spatially lagged variables from inverse distance weights</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#default-approach"><i class="fa fa-check"></i>Default approach</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-lags-with-row-standardized-inverse-distance-weights"><i class="fa fa-check"></i>Spatial lags with row-standardized inverse distance weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-lagged-variables-from-kernel-weights"><i class="fa fa-check"></i>Spatially lagged variables from kernel weights</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-rate-smoothing"><i class="fa fa-check"></i>Spatial rate smoothing</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle-1"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#preliminaries-9"><i class="fa fa-check"></i>Preliminaries</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#simple-window-average-of-rates"><i class="fa fa-check"></i>Simple window average of rates</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatially-smoothed-rates"><i class="fa fa-check"></i>Spatially Smoothed Rates</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-empirical-bayes-smoothing"><i class="fa fa-check"></i>Spatial Empirical Bayes smoothing</a>
<ul>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#principle-2"><i class="fa fa-check"></i>Principle</a></li>
<li class="chapter" data-level="" data-path="applications-of-spatial-weights.html"><a href="applications-of-spatial-weights.html#spatial-eb-rate-smoother"><i class="fa fa-check"></i>Spatial EB rate smoother</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html"><i class="fa fa-check"></i><b>10</b> Global Spatial Autocorrelation 1</a>
<ul>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#introduction-10"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="10.0.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#objectives-9"><i class="fa fa-check"></i><b>10.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="10.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#preliminaries-10"><i class="fa fa-check"></i><b>10.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#load-packages-8"><i class="fa fa-check"></i><b>10.1.1</b> Load packages</a></li>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#geodadata-website"><i class="fa fa-check"></i>geodaData website</a></li>
<li class="chapter" data-level="10.1.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#making-the-weights"><i class="fa fa-check"></i><b>10.1.2</b> Making the weights</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#the-moran-scatter-plot"><i class="fa fa-check"></i><b>10.2</b> The Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#concept-1"><i class="fa fa-check"></i><b>10.2.1</b> Concept</a></li>
<li class="chapter" data-level="10.2.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#creating-a-moran-scatter-plot"><i class="fa fa-check"></i><b>10.2.2</b> Creating a Moran scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#spatial-correlogram"><i class="fa fa-check"></i><b>10.3</b> Spatial Correlogram</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#concept-2"><i class="fa fa-check"></i><b>10.3.1</b> Concept</a></li>
<li class="chapter" data-level="10.3.2" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#creating-a-spatial-correlogram"><i class="fa fa-check"></i><b>10.3.2</b> Creating a spatial correlogram</a></li>
<li class="chapter" data-level="10.3.3" data-path="global-spatial-autocorrelation-1.html"><a href="global-spatial-autocorrelation-1.html#interpretation-1"><i class="fa fa-check"></i><b>10.3.3</b> Interpretation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html"><i class="fa fa-check"></i><b>11</b> Global Spatial Autocorrelation 2</a>
<ul>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#introduction-11"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="11.0.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#objectives-10"><i class="fa fa-check"></i><b>11.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="11.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#preliminaries-11"><i class="fa fa-check"></i><b>11.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#load-packages-9"><i class="fa fa-check"></i><b>11.1.1</b> Load packages</a></li>
<li class="chapter" data-level="" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#obtaining-the-data-from-the-geoda-website-1"><i class="fa fa-check"></i>Obtaining the Data from the GeoDa website</a></li>
<li class="chapter" data-level="11.1.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#creating-the-weights-2"><i class="fa fa-check"></i><b>11.1.2</b> Creating the weights</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#bivariate-spatial-correlation---a-word-of-caution"><i class="fa fa-check"></i><b>11.2</b> Bivariate spatial correlation - a Word of Caution</a></li>
<li class="chapter" data-level="11.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#bivariate-moran-scatter-plot"><i class="fa fa-check"></i><b>11.3</b> Bivariate Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-3"><i class="fa fa-check"></i><b>11.3.1</b> Concept</a></li>
<li class="chapter" data-level="11.3.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#creating-a-bivariate-moran-scatter-plot"><i class="fa fa-check"></i><b>11.3.2</b> Creating a bivariate Moran scatter plot</a></li>
<li class="chapter" data-level="11.3.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#a-closer-look-at-bivariate-spatial-correlation"><i class="fa fa-check"></i><b>11.3.3</b> A closer look at bivariate spatial correlation</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#differential-moran-scatter-plot"><i class="fa fa-check"></i><b>11.4</b> Differential Moran Scatter Plot</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-4"><i class="fa fa-check"></i><b>11.4.1</b> Concept</a></li>
<li class="chapter" data-level="11.4.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#implementation"><i class="fa fa-check"></i><b>11.4.2</b> Implementation</a></li>
<li class="chapter" data-level="11.4.3" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#options"><i class="fa fa-check"></i><b>11.4.3</b> Options</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#moran-scatter-plot-for-eb-rates"><i class="fa fa-check"></i><b>11.5</b> Moran Scatter Plot for EB Rates</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#concept-5"><i class="fa fa-check"></i><b>11.5.1</b> Concept</a></li>
<li class="chapter" data-level="11.5.2" data-path="global-spatial-autocorrelation-2.html"><a href="global-spatial-autocorrelation-2.html#implementation-1"><i class="fa fa-check"></i><b>11.5.2</b> Implementation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html"><i class="fa fa-check"></i><b>12</b> Local Spatial Autocorrelation 1</a>
<ul>
<li class="chapter" data-level="" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#introduction-12"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#objectives-11"><i class="fa fa-check"></i><b>12.0.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="12.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#preliminaries-12"><i class="fa fa-check"></i><b>12.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#load-packages-10"><i class="fa fa-check"></i><b>12.1.1</b> Load packages</a></li>
<li class="chapter" data-level="12.1.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#spatmap"><i class="fa fa-check"></i><b>12.1.2</b> spatmap</a></li>
<li class="chapter" data-level="12.1.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#geodadata-5"><i class="fa fa-check"></i><b>12.1.3</b> geodaData</a></li>
<li class="chapter" data-level="12.1.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#univariate-analysis"><i class="fa fa-check"></i><b>12.1.4</b> Univariate analysis</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-moran"><i class="fa fa-check"></i><b>12.2</b> Local Moran</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-3"><i class="fa fa-check"></i><b>12.2.1</b> Principle</a></li>
<li class="chapter" data-level="12.2.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-2"><i class="fa fa-check"></i><b>12.2.2</b> Implementation</a></li>
<li class="chapter" data-level="12.2.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#randomization-options"><i class="fa fa-check"></i><b>12.2.3</b> Randomization Options</a></li>
<li class="chapter" data-level="12.2.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#significance"><i class="fa fa-check"></i><b>12.2.4</b> Significance</a></li>
<li class="chapter" data-level="12.2.5" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#interpretation-of-clusters"><i class="fa fa-check"></i><b>12.2.5</b> Interpretation of clusters</a></li>
<li class="chapter" data-level="12.2.6" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#conditional-local-cluster-maps"><i class="fa fa-check"></i><b>12.2.6</b> Conditional local cluster maps</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-geary"><i class="fa fa-check"></i><b>12.3</b> Local Geary</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-4"><i class="fa fa-check"></i><b>12.3.1</b> Principle</a></li>
<li class="chapter" data-level="12.3.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-3"><i class="fa fa-check"></i><b>12.3.2</b> Implementation</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#getis-ord-statistics"><i class="fa fa-check"></i><b>12.4</b> Getis-Ord Statistics</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-5"><i class="fa fa-check"></i><b>12.4.1</b> Principle</a></li>
<li class="chapter" data-level="12.4.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-4"><i class="fa fa-check"></i><b>12.4.2</b> Implementation</a></li>
<li class="chapter" data-level="12.4.3" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#interpretation-and-significance-1"><i class="fa fa-check"></i><b>12.4.3</b> Interpretation and significance</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#local-join-count-statistic"><i class="fa fa-check"></i><b>12.5</b> Local Join Count Statistic</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#principle-6"><i class="fa fa-check"></i><b>12.5.1</b> Principle</a></li>
<li class="chapter" data-level="12.5.2" data-path="local-spatial-autocorrelation-1.html"><a href="local-spatial-autocorrelation-1.html#implementation-5"><i class="fa fa-check"></i><b>12.5.2</b> Implementation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>13</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Hands-On Spatial Data Science with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="global-spatial-autocorrelation-2" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Chapter 11</span> Global Spatial Autocorrelation 2<a href="global-spatial-autocorrelation-2.html#global-spatial-autocorrelation-2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-11" class="section level2 unnumbered hasAnchor">
<h2>Introduction<a href="global-spatial-autocorrelation-2.html#introduction-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This notebook cover the functionality of the <a href="https://geodacenter.github.io/workbook/5b_global_adv/lab5b.html">Global Spatial Autocorrelation 2</a> section of the GeoDa workbook. We refer to that document for details on the methodology, references, etc. The goal of these notes is to approximate as closely as possible the operations carried out using GeoDa by means of a range of R packages.</p>
<p>The notes are written with R beginners in mind, more seasoned R users can probably skip most of the comments
on data structures and other R particulars. Also, as always in R, there are typically several ways to achieve a specific objective, so what is shown here is just one way that works, but there often are others (that may even be more elegant, work faster, or scale better).</p>
<p>For this notebook, we use Cleveland house price data. Our goal in this lab is show how to assign spatial weights based on different distance functions.</p>
<div id="objectives-10" class="section level3 hasAnchor" number="11.0.1">
<h3><span class="header-section-number">11.0.1</span> Objectives<a href="global-spatial-autocorrelation-2.html#objectives-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After completing the notebook, you should know how to carry out the following tasks:</p>
<ul>
<li><p>Visualize bivariate spatial correlation</p></li>
<li><p>Assess different aspects of bivariate spatial correlation</p></li>
<li><p>Visualize bivariate spatial correlation among time-differenced values</p></li>
<li><p>Correct Moran’s I for the variance instability in rates</p></li>
</ul>
<div id="r-packages-used-10" class="section level4 hasAnchor" number="11.0.1.1">
<h4><span class="header-section-number">11.0.1.1</span> R Packages used<a href="global-spatial-autocorrelation-2.html#r-packages-used-10" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p><strong>sf</strong>: To read in the shapefile and make queen contiguity weights</p></li>
<li><p><strong>spdep</strong>: To create spatial weights structure from neighbors structure.</p></li>
<li><p><strong>ggplot2</strong>: To make customized plots such as a bivariate Moran’s I scatter plot</p></li>
<li><p><strong>robustHD</strong>: To compute standarized scores for variables and lag variables. in construction of a Moran’s I scatterplot</p></li>
</ul>
</div>
<div id="r-commands-used-10" class="section level4 hasAnchor" number="11.0.1.2">
<h4><span class="header-section-number">11.0.1.2</span> R Commands used<a href="global-spatial-autocorrelation-2.html#r-commands-used-10" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Below follows a list of the commands used in this notebook. For further details
and a comprehensive list of options, please consult the
<a href="https://www.rdocumentation.org">R documentation</a>.</p>
<ul>
<li><p><strong>Base R</strong>: <code>install.packages</code>, <code>library</code>, <code>setwd</code>, <code>summary</code>, <code>attributes</code>, <code>lapply</code>, <code>class</code>, <code>length</code>, <code>lm</code></p></li>
<li><p><strong>sf</strong>: <code>st_read</code>, <code>st_relate</code>, <code>st_crs</code>, <code>st_transform</code></p></li>
<li><p><strong>spdep</strong>: <code>nb2listw</code>, <code>lag.listw</code></p></li>
<li><p><strong>ggplot2</strong>: <code>ggplot</code>, <code>geom_smooth</code>, <code>geom_point</code>, <code>xlim</code>, <code>ylim</code>, <code>geom_hline</code>, <code>geom_vline</code>,
<code>ggtitle</code></p></li>
<li><p><strong>robustHD</strong>: <code>standardized</code></p></li>
</ul>
</div>
</div>
</div>
<div id="preliminaries-11" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> Preliminaries<a href="global-spatial-autocorrelation-2.html#preliminaries-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before starting, make sure to have the latest version of R and of packages that are compiled for the matching version of R (this document was created using R 3.5.1 of 2018-07-02). Also, optionally, set a working directory, even though we will not
actually be saving any files.<a href="#fn29" class="footnote-ref" id="fnref29"><sup>29</sup></a></p>
<div id="load-packages-9" class="section level3 hasAnchor" number="11.1.1">
<h3><span class="header-section-number">11.1.1</span> Load packages<a href="global-spatial-autocorrelation-2.html#load-packages-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, we load all the required packages using the <code>library</code> command. If you don’t have some of these in your system, make sure to install them first as well as
their dependencies.<a href="#fn30" class="footnote-ref" id="fnref30"><sup>30</sup></a> You will get an error message if something is missing. If needed, just install the missing piece and everything will work after that.</p>
<div class="sourceCode" id="cb783"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb783-1"><a href="global-spatial-autocorrelation-2.html#cb783-1" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb783-2"><a href="global-spatial-autocorrelation-2.html#cb783-2" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb783-3"><a href="global-spatial-autocorrelation-2.html#cb783-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb783-4"><a href="global-spatial-autocorrelation-2.html#cb783-4" tabindex="-1"></a><span class="fu">library</span>(robustHD)</span></code></pre></div>
</div>
<div id="obtaining-the-data-from-the-geoda-website-1" class="section level3 unnumbered hasAnchor">
<h3>Obtaining the Data from the GeoDa website<a href="global-spatial-autocorrelation-2.html#obtaining-the-data-from-the-geoda-website-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To get the data for this notebook, you will and to go to <a href="https://geodacenter.github.io/data-and-lab/natregimes/">US County Homocide Data</a> The download format is a
zipfile, so you will need to unzip it by double clicking on the file in your file
finder. From there move the resulting folder titled: nyc into your working directory
to continue. Once that is done, you can use the <strong>sf</strong> function: <code>st_read()</code> to read
the shapefile into your R environment.</p>
<div class="sourceCode" id="cb784"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb784-1"><a href="global-spatial-autocorrelation-2.html#cb784-1" tabindex="-1"></a>counties <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&quot;natregimes/natregimes.shp&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `natregimes&#39; from data source 
##   `/Users/xun/github/handsonspatialdata/natregimes/natregimes.shp&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 3085 features and 73 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -124.7314 ymin: 24.95597 xmax: -66.96985 ymax: 49.37173
## Geodetic CRS:  WGS 84</code></pre>
</div>
<div id="creating-the-weights-2" class="section level3 hasAnchor" number="11.1.2">
<h3><span class="header-section-number">11.1.2</span> Creating the weights<a href="global-spatial-autocorrelation-2.html#creating-the-weights-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>sf</strong> neighbor functions assume that coordinates for the data are planar. Since
The current projection is that for latitude and longitude, it is best to tranform
the coordinates to a planar projection for accuracy. To check the current projection,
we use <code>st_crs</code>. To transform the projection, we use <code>st_transform</code> and the epsg
number of our desired projection. For more indepth information on this, please check
out the Spatial Data Handling notebook.</p>
<div class="sourceCode" id="cb786"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb786-1"><a href="global-spatial-autocorrelation-2.html#cb786-1" tabindex="-1"></a><span class="fu">st_crs</span>(counties)</span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: WGS 84 
##   wkt:
## GEOGCRS[&quot;WGS 84&quot;,
##     DATUM[&quot;World Geodetic System 1984&quot;,
##         ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##             LENGTHUNIT[&quot;metre&quot;,1]]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##     CS[ellipsoidal,2],
##         AXIS[&quot;latitude&quot;,north,
##             ORDER[1],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         AXIS[&quot;longitude&quot;,east,
##             ORDER[2],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##     ID[&quot;EPSG&quot;,4326]]</code></pre>
<div class="sourceCode" id="cb788"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb788-1"><a href="global-spatial-autocorrelation-2.html#cb788-1" tabindex="-1"></a>counties <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(counties, <span class="at">crs =</span> <span class="st">&quot;ESRI:102003&quot;</span>)</span></code></pre></div>
<p>To start we create a function for queen contiguity, which is just <code>st_relate</code> with
the specified pattern for queen contiguity which is <code>F***T****</code></p>
<div class="sourceCode" id="cb789"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb789-1"><a href="global-spatial-autocorrelation-2.html#cb789-1" tabindex="-1"></a>st_queen <span class="ot">&lt;-</span> <span class="cf">function</span>(a, <span class="at">b =</span> a) <span class="fu">st_relate</span>(a, b, <span class="at">pattern =</span> <span class="st">&quot;F***T****&quot;</span>)</span></code></pre></div>
<p>We apply the queen contiguity function to the voronoi polygons and see that the class
of the output is <strong>sgbp</strong>. This structure is close to the <strong>nb</strong> structure, but has
a few difference that we will need to correct to use the rest of <strong>spdep</strong> functionality.</p>
<div class="sourceCode" id="cb790"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb790-1"><a href="global-spatial-autocorrelation-2.html#cb790-1" tabindex="-1"></a>queen.sgbp <span class="ot">&lt;-</span> <span class="fu">st_queen</span>(counties)</span>
<span id="cb790-2"><a href="global-spatial-autocorrelation-2.html#cb790-2" tabindex="-1"></a><span class="fu">class</span>(queen.sgbp)</span></code></pre></div>
<pre><code>## [1] &quot;sgbp&quot; &quot;list&quot;</code></pre>
<p>This function converts type <strong>sgbp</strong> to <strong>nb</strong>. It is covered in more depth in the
Contiguity Based Weight notebook. In short, it explicitly changes the name of the
class and deals with the observations that have no neighbors.</p>
<div class="sourceCode" id="cb792"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb792-1"><a href="global-spatial-autocorrelation-2.html#cb792-1" tabindex="-1"></a>as.nb.sgbp <span class="ot">&lt;-</span> <span class="cf">function</span>(x, ...) {</span>
<span id="cb792-2"><a href="global-spatial-autocorrelation-2.html#cb792-2" tabindex="-1"></a>  attrs <span class="ot">&lt;-</span> <span class="fu">attributes</span>(x)</span>
<span id="cb792-3"><a href="global-spatial-autocorrelation-2.html#cb792-3" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">lapply</span>(x, <span class="cf">function</span>(i) { <span class="cf">if</span>(<span class="fu">length</span>(i) <span class="sc">==</span> 0L) 0L <span class="cf">else</span> i } )</span>
<span id="cb792-4"><a href="global-spatial-autocorrelation-2.html#cb792-4" tabindex="-1"></a>  <span class="fu">attributes</span>(x) <span class="ot">&lt;-</span> attrs</span>
<span id="cb792-5"><a href="global-spatial-autocorrelation-2.html#cb792-5" tabindex="-1"></a>  <span class="fu">class</span>(x) <span class="ot">&lt;-</span> <span class="st">&quot;nb&quot;</span></span>
<span id="cb792-6"><a href="global-spatial-autocorrelation-2.html#cb792-6" tabindex="-1"></a>  x</span>
<span id="cb792-7"><a href="global-spatial-autocorrelation-2.html#cb792-7" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb793"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb793-1"><a href="global-spatial-autocorrelation-2.html#cb793-1" tabindex="-1"></a>queen.nb <span class="ot">&lt;-</span> <span class="fu">as.nb.sgbp</span>(queen.sgbp)</span></code></pre></div>
<p>To go from neighbors object to weights object, we use <code>nb2listw</code>, with default parameters, we will
get row standardized weights.</p>
<div class="sourceCode" id="cb794"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb794-1"><a href="global-spatial-autocorrelation-2.html#cb794-1" tabindex="-1"></a>queen.weights <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(queen.nb)</span></code></pre></div>
</div>
</div>
<div id="bivariate-spatial-correlation---a-word-of-caution" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">11.2</span> Bivariate spatial correlation - a Word of Caution<a href="global-spatial-autocorrelation-2.html#bivariate-spatial-correlation---a-word-of-caution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The concept of bivariate spatial correlation is complex and often misinterpreted.
It is typically considered to the correlation between one variable and the spatial
lag of another variable, as originally implemented in the precursor of GeoDa.
However this does not take into account the inherent correlation between the
two variables. More precisely, the bivariate spatial correlation
is between <span class="math inline">\(x_i\)</span> and <span class="math inline">\(\Sigma_jw_{ij}y_j\)</span>, but does not take into account the correlation
between <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span>, i.e. between two variables at the same location.</p>
<p>As a result, this statistic is often interpreted incorrectly, as it may overestimate
the spatial aspect of the correlation that instead may be due mostly to in-place correlation.</p>
<p>Below, we provide a more in-depth assessment of the different aspects of bivariate spatial and
non-spatial association, but first we turn to the original concept of a bivariate Moran scatter
plot.</p>
</div>
<div id="bivariate-moran-scatter-plot" class="section level2 hasAnchor" number="11.3">
<h2><span class="header-section-number">11.3</span> Bivariate Moran Scatter Plot<a href="global-spatial-autocorrelation-2.html#bivariate-moran-scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="concept-3" class="section level3 hasAnchor" number="11.3.1">
<h3><span class="header-section-number">11.3.1</span> Concept<a href="global-spatial-autocorrelation-2.html#concept-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In its initial conceptualization, as mentioned above, a bivariate Moran scatter plot extends the idea
of a Moran scatter plot with a variable on the x-axis and its spatial lag on a y-axis to a bivariate
context. The fundamental difference is that in the bivariate case the spatial lag pertains to a
different variable. In essence, this notion of bivariate spatial correlation measures the degree to
which the value for a given variable at a location is correlated with its neighbors for a different
variable.</p>
<p>As in the univariate Moran scatter plot, the interest is in the slope of the linear fit. This yields a
Moran’s I-like statistic as:</p>
<p><span class="math display">\[I_B=\frac{\Sigma_i(\Sigma_jw_{ij}*x_i)}{\Sigma_ix_i^2}\]</span></p>
<p>or, the slope of a regression of Wy on x.</p>
<p>As before, all variables are expressed in standardized form, such that their means are zero and their
variance one. In addition, the spatial weights are row-standardized.</p>
<p>Note that, unlike in the univariate autocorrelation case, the regression of x on Wy also yields an
unbiased estimate of the slope, providing an alternative perspective on bivariate spatial correlation.</p>
<p>A special case of bivariate spatial autocorrelation is when the variable is measured at two points in
time, say <span class="math inline">\(z_{i,t}\)</span> and <span class="math inline">\(z_{i,t-1}\)</span>. The statistic then pertains to the extent to which the value
obsereved at a location at a given time, is correlated with its value at neighboring locations at a
different point in time.</p>
<p>The natural interpretation of this concept is to relate <span class="math inline">\(z_{i,t}\)</span> to <span class="math inline">\(\Sigma_jw_{ij}z_{j,t-1}\)</span>,
i.e. the correlation between a value at t and its neighbors in a previous time period:</p>
<p><span class="math display">\[I_T=\frac{\Sigma_i(\Sigma_jw_{ij}z_{j,t-1}*z_{i,t})}{\Sigma_iz_{i,t}^2}\]</span>
i.e., the effect neighbors in t-1 on the present value.</p>
<p>Alternatively, and maybe less intuitively, one can relate the value at a previous time period <span class="math inline">\(z_{t-1}\)</span>
to its neighbors in the future, <span class="math inline">\(\Sigma_jw_{ij}z_t\)</span> as:</p>
<p><span class="math display">\[I_T=\frac{\Sigma_i(\Sigma_jw_{ij}z_{j,t}*z_{i,t-1)}}{\Sigma_iz_{i,t-1}^2}\]</span>
i.e., the effect of a location at t-1 on its neighbors in the future.</p>
<p>While formally correct, this may not be a proper interpretation of the dynamics involved. In fact, the
notion of spatial correlation pertains to the effect of neighbors on a central location, not the other
way around. While the Moran scatter plot seems to reverse this logic, this is purely a formalism,
without any consequences in the univariate case. However, when relating the slope in the scatter plot
to the dynamics of a process, this should be interpreted with caution.</p>
<p>A possible source of confusion is that the proper regression specification for a dynamic process would
be as:</p>
<p><span class="math display">\[z_{i,t}=\beta_1\Sigma_jw_{ij}z_{j,t-1} +u_i\]</span>
with <span class="math inline">\(u_i\)</span> as the usual error term, and not as:</p>
<p><span class="math display">\[z_{i,t-1}= \beta_2\Sigma_jw_{ij}z_{j,t} + u_i\]</span></p>
<p>which would have the future predicting the past. This contrasts with the linear regression
specification used (purely formally) to estimate the bivariate Moran’s I, for example:</p>
<p><span class="math display">\[\Sigma_jw_{ij}z_{j,t-1} = \beta_3z_{i,t} + u_i\]</span></p>
<p>In terms of the interpretation of a dynamic process, only <span class="math inline">\(\beta_1\)</span> has intuitive appeal. However,
in terms of measuring the degree of spatial correlation between past neighbors and a current value,
as measured by a Moran’s I coefficient, <span class="math inline">\(\beta_3\)</span> is the correct interpretation.</p>
<p>As mentioned earlier, a fundamental difference with the univariate case is that the spatially lagged
variable is no longer endogenous, so both specifications can be estimated by means of ordinary least
squares.</p>
<p>In the univariate case, only the specification with the spatially lagged variable on the left hand side
yields a valid estimate. As a result, for the univariate Moran’s I, there is no ambiguity about which
variables should be on the x-axis and y-axis.</p>
<p>Inference is again based on a permutation approach, but with an important difference. Since the
interest focuses on the bivariate spatial association, the values for x are fixed at their locations,
and only the values for y are randomly permuted. In the usual manner, this yields a reference
distribution for the statistic under the null hypothesis that the spatial arrangement of the y
values is random. As mentioned, it is important to keep in mind that since the focus is on the
correlation between the x value at i and the y values at the neighboring locations, the correlation
between x and y at location i is ignored.</p>
</div>
<div id="creating-a-bivariate-moran-scatter-plot" class="section level3 hasAnchor" number="11.3.2">
<h3><span class="header-section-number">11.3.2</span> Creating a bivariate Moran scatter plot<a href="global-spatial-autocorrelation-2.html#creating-a-bivariate-moran-scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To create the bivariate Moran scatterplot, we will need to standardize the variables beofre proceeding. This
is simply, putting the variables in terms of z scores. To do this, we use <code>standardize</code> from the
<strong>robustHD</strong> package.</p>
<div class="sourceCode" id="cb795"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb795-1"><a href="global-spatial-autocorrelation-2.html#cb795-1" tabindex="-1"></a>counties<span class="sc">$</span>hr80st <span class="ot">&lt;-</span> <span class="fu">standardize</span>(counties<span class="sc">$</span>HR80)</span>
<span id="cb795-2"><a href="global-spatial-autocorrelation-2.html#cb795-2" tabindex="-1"></a>counties<span class="sc">$</span>hr90st <span class="ot">&lt;-</span> <span class="fu">standardize</span>(counties<span class="sc">$</span>HR90)</span></code></pre></div>
<p>Now that we have standardized the variables, we can create the lag variable for homocide rates in 1980.
This is done with <code>lag.listw</code> from <strong>spdep</strong>. For more a more indepth coverage of this function , please see
the Application of Spatial Weights notebook.</p>
<div class="sourceCode" id="cb796"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb796-1"><a href="global-spatial-autocorrelation-2.html#cb796-1" tabindex="-1"></a>counties<span class="sc">$</span>whr80st <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights,counties<span class="sc">$</span>hr80st)</span></code></pre></div>
<p>In constructing the majority of our plots, we use <strong>ggplot2</strong> because it makes aesthically pleasing and functional
plots. The purpose of this tutorial is not to teach <strong>ggplot2</strong>, but to use it in creqating specializzed plots
such as the bivariate Moran plot. For indepth coverage of basic <strong>ggplot2</strong> functionality please see the
Exploratory Data Analysis notebooks or <a href="https://ggplot2.tidyverse.org/reference/index.html">ggplot2 documentation</a>.</p>
<p>To make the bivariate Moran, we make a scattplot of the lag variable for 1980 homocide rates vs the homocide
rate for 1990. In GeoDa the lag variable and standardization are done automatically and all you have to do is
select the desired variables. The custom specifications use for this plot are the dashed lines at the x and y
axis and the simple regression line. <code>geom_vline</code> and <code>geom_hline</code>.</p>
<div class="sourceCode" id="cb797"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb797-1"><a href="global-spatial-autocorrelation-2.html#cb797-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> counties, <span class="fu">aes</span>(<span class="at">x=</span>hr90st,<span class="at">y=</span>whr80st)) <span class="sc">+</span></span>
<span id="cb797-2"><a href="global-spatial-autocorrelation-2.html#cb797-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb797-3"><a href="global-spatial-autocorrelation-2.html#cb797-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb797-4"><a href="global-spatial-autocorrelation-2.html#cb797-4" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb797-5"><a href="global-spatial-autocorrelation-2.html#cb797-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb797-6"><a href="global-spatial-autocorrelation-2.html#cb797-6" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">12</span>,<span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb797-7"><a href="global-spatial-autocorrelation-2.html#cb797-7" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="sc">-</span><span class="dv">12</span>,<span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb797-8"><a href="global-spatial-autocorrelation-2.html#cb797-8" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Bivariate Moran&#39;s I, hr(90) and lagged hr(80) &quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-451-1.png" width="672" /></p>
<p>To get the summary statistics and bivariate Moran’s I statistic, we will run a rgeression separate from the plot.
For this regression, we use the same variables has the bivariate Moran plot in the base R <code>lm</code> function.
To view the results, we use the <code>summary</code> command. The Moran’s I statistic is the slope of the regression
line, which is the coefficient of <strong>hr90st</strong> in the <code>summary</code> results</p>
<div class="sourceCode" id="cb799"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb799-1"><a href="global-spatial-autocorrelation-2.html#cb799-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(whr80st <span class="sc">~</span> hr90st, <span class="at">data =</span> counties)</span>
<span id="cb799-2"><a href="global-spatial-autocorrelation-2.html#cb799-2" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = whr80st ~ hr90st, data = counties)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.9290 -0.4171 -0.1024  0.3595  2.6279 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.004734   0.010694   0.443    0.658    
## hr90st      0.359668   0.010696  33.628   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.594 on 3083 degrees of freedom
## Multiple R-squared:  0.2684, Adjusted R-squared:  0.2681 
## F-statistic:  1131 on 1 and 3083 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="a-closer-look-at-bivariate-spatial-correlation" class="section level3 hasAnchor" number="11.3.3">
<h3><span class="header-section-number">11.3.3</span> A closer look at bivariate spatial correlation<a href="global-spatial-autocorrelation-2.html#a-closer-look-at-bivariate-spatial-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In contrast to the univariate Moran scatter plot, where the interpretation of the linear fit
is unequivocably Moran’s I, there is no such clarity in the bivariate case. In addition to the
interpretation offered above, which is a traditional Moran’s I-like coefficient, there are at
least four additional perspectives that are relevant. We consider each in turn.</p>
<div id="serial-temporal-correlation" class="section level4 hasAnchor" number="11.3.3.1">
<h4><span class="header-section-number">11.3.3.1</span> Serial (temporal) correlation<a href="global-spatial-autocorrelation-2.html#serial-temporal-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To examine the temporal correlation of homocide rates, we plot the standardized variable for each time period.
This gives us a sense of the temporal autocorrelation of homocide rates for a lag order of 1.</p>
<div class="sourceCode" id="cb801"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb801-1"><a href="global-spatial-autocorrelation-2.html#cb801-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> counties, <span class="fu">aes</span>(<span class="at">x =</span> hr80st, <span class="at">y =</span> hr90st)) <span class="sc">+</span></span>
<span id="cb801-2"><a href="global-spatial-autocorrelation-2.html#cb801-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb801-3"><a href="global-spatial-autocorrelation-2.html#cb801-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb801-4"><a href="global-spatial-autocorrelation-2.html#cb801-4" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb801-5"><a href="global-spatial-autocorrelation-2.html#cb801-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span><span class="dv">2</span>) </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-453-1.png" width="672" /></p>
<p>Again we us the <code>lm</code> function and <code>summary</code> function to get a sense of the relationship
between the variables. With a highly significant slope of .552, strong temporal correlation
is suggested.</p>
<div class="sourceCode" id="cb803"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb803-1"><a href="global-spatial-autocorrelation-2.html#cb803-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(hr90st <span class="sc">~</span> hr80st, <span class="at">data =</span> counties)</span>
<span id="cb803-2"><a href="global-spatial-autocorrelation-2.html#cb803-2" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hr90st ~ hr80st, data = counties)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.8479 -0.3701 -0.1609  0.2806 10.3772 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 3.661e-15  1.501e-02    0.00        1    
## hr80st      5.526e-01  1.501e-02   36.82   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8336 on 3083 degrees of freedom
## Multiple R-squared:  0.3054, Adjusted R-squared:  0.3052 
## F-statistic:  1356 on 1 and 3083 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="serial-temporal-correlation-between-spatial-lags" class="section level4 hasAnchor" number="11.3.3.2">
<h4><span class="header-section-number">11.3.3.2</span> Serial (temporal) correlation between spatial lags<a href="global-spatial-autocorrelation-2.html#serial-temporal-correlation-between-spatial-lags" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Next we run a regression of the spatial lags of homocide rates for both time periods.
This will be a regression of <span class="math inline">\(\Sigma_jw_{ij}y_{j,t}\)</span> on <span class="math inline">\(\Sigma_jw_{ij}y_{j,t-1}\)</span>.
To begin, wewill need to create the lag variable for 1990.</p>
<div class="sourceCode" id="cb805"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb805-1"><a href="global-spatial-autocorrelation-2.html#cb805-1" tabindex="-1"></a>counties<span class="sc">$</span>whr90st <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights, counties<span class="sc">$</span>hr90st)</span></code></pre></div>
<p>To make this plot, we just plot the lag variable for 1990 against the one for 1980.</p>
<div class="sourceCode" id="cb806"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb806-1"><a href="global-spatial-autocorrelation-2.html#cb806-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> counties, <span class="fu">aes</span>(<span class="at">x=</span> whr80st, <span class="at">y =</span> whr90st)) <span class="sc">+</span> </span>
<span id="cb806-2"><a href="global-spatial-autocorrelation-2.html#cb806-2" tabindex="-1"></a>  <span class="fu">geom_point</span>()  <span class="sc">+</span></span>
<span id="cb806-3"><a href="global-spatial-autocorrelation-2.html#cb806-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb806-4"><a href="global-spatial-autocorrelation-2.html#cb806-4" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb806-5"><a href="global-spatial-autocorrelation-2.html#cb806-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span><span class="dv">2</span>) </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-456-1.png" width="672" /></p>
<p>Again the slope is highly signiificcant with a positive slope of .801, even strong than the actual
variable’s temporal correlation.</p>
<div class="sourceCode" id="cb808"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb808-1"><a href="global-spatial-autocorrelation-2.html#cb808-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(whr90st <span class="sc">~</span> whr80st, <span class="at">data =</span> counties)</span>
<span id="cb808-2"><a href="global-spatial-autocorrelation-2.html#cb808-2" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = whr90st ~ whr80st, data = counties)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.73241 -0.20479 -0.03393  0.16637  2.13011 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.0005499  0.0074544  -0.074    0.941    
## whr80st      0.8014254  0.0107383  74.633   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.414 on 3083 degrees of freedom
## Multiple R-squared:  0.6437, Adjusted R-squared:  0.6436 
## F-statistic:  5570 on 1 and 3083 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="space-time-regression" class="section level4 hasAnchor" number="11.3.3.3">
<h4><span class="header-section-number">11.3.3.3</span> Space-time regression<a href="global-spatial-autocorrelation-2.html#space-time-regression" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In this case we have already computed the variables need to construct the plot, so we
can start with <strong>ggplot2</strong>. The regression here is <span class="math inline">\(y_{i,t}\)</span> on <span class="math inline">\(\Sigma_jw_{ij}y_{j,t-1}\)</span></p>
<div class="sourceCode" id="cb810"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb810-1"><a href="global-spatial-autocorrelation-2.html#cb810-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> counties, <span class="fu">aes</span>(<span class="at">x=</span> whr80st, <span class="at">y =</span> hr90st)) <span class="sc">+</span> </span>
<span id="cb810-2"><a href="global-spatial-autocorrelation-2.html#cb810-2" tabindex="-1"></a>  <span class="fu">geom_point</span>()  <span class="sc">+</span></span>
<span id="cb810-3"><a href="global-spatial-autocorrelation-2.html#cb810-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb810-4"><a href="global-spatial-autocorrelation-2.html#cb810-4" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb810-5"><a href="global-spatial-autocorrelation-2.html#cb810-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span><span class="dv">2</span>) </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-458-1.png" width="672" /></p>
<p>Now we run the <code>lm</code> function to get the regression statistics.</p>
<div class="sourceCode" id="cb812"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb812-1"><a href="global-spatial-autocorrelation-2.html#cb812-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(hr90st <span class="sc">~</span> whr80st, <span class="at">data =</span> counties)</span>
<span id="cb812-2"><a href="global-spatial-autocorrelation-2.html#cb812-2" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hr90st ~ whr80st, data = counties)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.3519 -0.4569 -0.1702  0.2711 10.1136 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.003532   0.015403  -0.229    0.819    
## whr80st      0.746141   0.022188  33.628   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8555 on 3083 degrees of freedom
## Multiple R-squared:  0.2684, Adjusted R-squared:  0.2681 
## F-statistic:  1131 on 1 and 3083 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This yields a highly signifcant slope of .746</p>
</div>
<div id="serial-and-space-time-regression" class="section level4 hasAnchor" number="11.3.3.4">
<h4><span class="header-section-number">11.3.3.4</span> Serial and space-time regression<a href="global-spatial-autocorrelation-2.html#serial-and-space-time-regression" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Finally, we can include both in-situ correlation and space-time correlation in a
regression specification of <span class="math inline">\(y_{i,t}\)</span> i.s <strong>hr90st</strong> on both <span class="math inline">\(x_{i,t-1}\)</span> (ie, <strong>hr80st</strong>)
and <span class="math inline">\(\Sigma_jw_{ij}x_{j,t-1}\)</span>(ie <strong>whr80st</strong>)</p>
<div class="sourceCode" id="cb814"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb814-1"><a href="global-spatial-autocorrelation-2.html#cb814-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(hr90st <span class="sc">~</span> whr80st <span class="sc">+</span> hr80st, <span class="at">data =</span> counties)</span>
<span id="cb814-2"><a href="global-spatial-autocorrelation-2.html#cb814-2" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hr90st ~ whr80st + hr80st, data = counties)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.2802 -0.3807 -0.1202  0.2574 10.3821 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.002093   0.014282  -0.147    0.883    
## whr80st      0.442224   0.024628  17.956   &lt;2e-16 ***
## hr80st       0.383861   0.017099  22.450   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.7932 on 3082 degrees of freedom
## Multiple R-squared:  0.3712, Adjusted R-squared:  0.3708 
## F-statistic: 909.7 on 2 and 3082 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In the regression, both effects are highly significant, with a coefficient of 0.384 for
the in-situ effect, and 0.442 for the space-time effect.</p>
<p>Needless to say, focusing the analysis solely on the bivariate Moran scatter plot
provides only a limited perspective on the complexity of space-time (or, in general,
bivariate) spatial and space-time associations.</p>
</div>
</div>
</div>
<div id="differential-moran-scatter-plot" class="section level2 hasAnchor" number="11.4">
<h2><span class="header-section-number">11.4</span> Differential Moran Scatter Plot<a href="global-spatial-autocorrelation-2.html#differential-moran-scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="concept-4" class="section level3 hasAnchor" number="11.4.1">
<h3><span class="header-section-number">11.4.1</span> Concept<a href="global-spatial-autocorrelation-2.html#concept-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An alternative to the bivariate spatial correlation between a variable at one point in time
and its neighbors at a previous (or, in general, any different) point in time is to control
for the locational fixed effects by diffencing the variable. More precisely, we apply the
computation of the spatial autocorrelation statistic to the variable <span class="math inline">\(y_{i,t} - y_{i,t-1}\)</span>.</p>
<p>This takes care of any temporal correlation that may be the result of a fixed effect(i.e.
a set of variables determining the value of <span class="math inline">\(y_i\)</span> that remain unchanging over time).
Specifically if <span class="math inline">\(\mu_i\)</span> were a fixed effect associated with location i, we could express
the value at each location for time t as the sum of some intinsic value and the fixed
effect, $y_{i,t} = y_{i,t}^* + _i $, where <span class="math inline">\(\mu_i\)</span> is unchanged over time (hence, fixed).
The presence of <span class="math inline">\(\mu\)</span> induces a temporal correlation between <span class="math inline">\(y_{i,t}\)</span> and <span class="math inline">\(y_{i,t-1}\)</span>,
above and beyond the correlation between <span class="math inline">\(y_{i,t}^*\)</span> and <span class="math inline">\(y_{i,t-1}^*\)</span>. Taking the
difference eliminates the fixed effect and ensures that any remainin correlation is
solely due to <span class="math inline">\(y^*\)</span>.</p>
<p>A differential Moran’s I is then the slope in a regression of the spatial lag of the
difference i.e. <span class="math inline">\(\Sigma_jw_{ij}(y_{j,t} - y_{j,t-1})\)</span> on the difference <span class="math inline">\(y_{i,t} - y_{i,t-1}\)</span>.</p>
<p>All the caveats and different interpretations that apply to the generic bivariate case are
also relevant here.</p>
</div>
<div id="implementation" class="section level3 hasAnchor" number="11.4.2">
<h3><span class="header-section-number">11.4.2</span> Implementation<a href="global-spatial-autocorrelation-2.html#implementation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Same as the other sections, we must first calculate and standardize the variables
before proceeding to construct the plot. In GeoDa this process is done automatically,
but here we will need a few extra steps. First we calcualte the standardized score of
the difference between the variable, NOT the difference between the standardized
score of each variable. To do this, we just use <code>standardize</code> on the difference
between <strong>HR80</strong> and <strong>HR90</strong>. Then we calcualte the lag variable with <code>lag.listw</code>
on the standardized difference variable.</p>
<div class="sourceCode" id="cb816"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb816-1"><a href="global-spatial-autocorrelation-2.html#cb816-1" tabindex="-1"></a>counties<span class="sc">$</span>hr_diff_st <span class="ot">&lt;-</span> <span class="fu">standardize</span>(counties<span class="sc">$</span>HR90 <span class="sc">-</span> counties<span class="sc">$</span>HR80)</span>
<span id="cb816-2"><a href="global-spatial-autocorrelation-2.html#cb816-2" tabindex="-1"></a>counties<span class="sc">$</span>hr_diff_lag <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights, counties<span class="sc">$</span>hr_diff_st)</span></code></pre></div>
<p>To construct the plot, we use the same functions as earlier, but just replace the
variables. In this case, we use the ones calcualted above for the standardized
difference then the lag of the standardized difference.</p>
<div class="sourceCode" id="cb817"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb817-1"><a href="global-spatial-autocorrelation-2.html#cb817-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> counties, <span class="fu">aes</span>(<span class="at">x =</span> hr_diff_st, <span class="at">y =</span> hr_diff_lag)) <span class="sc">+</span></span>
<span id="cb817-2"><a href="global-spatial-autocorrelation-2.html#cb817-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb817-3"><a href="global-spatial-autocorrelation-2.html#cb817-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb817-4"><a href="global-spatial-autocorrelation-2.html#cb817-4" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb817-5"><a href="global-spatial-autocorrelation-2.html#cb817-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span><span class="dv">2</span>) </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-462-1.png" width="672" /></p>
<div class="sourceCode" id="cb819"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb819-1"><a href="global-spatial-autocorrelation-2.html#cb819-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(hr_diff_lag<span class="sc">~</span>hr_diff_st, <span class="at">data =</span> counties)</span>
<span id="cb819-2"><a href="global-spatial-autocorrelation-2.html#cb819-2" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hr_diff_lag ~ hr_diff_st, data = counties)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.23658 -0.21238  0.03382  0.22281  2.45484 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.001690   0.008258  -0.205    0.838    
## hr_diff_st   0.052007   0.008260   6.297 3.47e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4587 on 3083 degrees of freedom
## Multiple R-squared:  0.0127, Adjusted R-squared:  0.01238 
## F-statistic: 39.65 on 1 and 3083 DF,  p-value: 3.474e-10</code></pre>
<p>The slope is about .052, which is much smaller than in magnitude than the other measures
used thus far.</p>
</div>
<div id="options" class="section level3 hasAnchor" number="11.4.3">
<h3><span class="header-section-number">11.4.3</span> Options<a href="global-spatial-autocorrelation-2.html#options" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
</div>
<div id="moran-scatter-plot-for-eb-rates" class="section level2 hasAnchor" number="11.5">
<h2><span class="header-section-number">11.5</span> Moran Scatter Plot for EB Rates<a href="global-spatial-autocorrelation-2.html#moran-scatter-plot-for-eb-rates" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="concept-5" class="section level3 hasAnchor" number="11.5.1">
<h3><span class="header-section-number">11.5.1</span> Concept<a href="global-spatial-autocorrelation-2.html#concept-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An Empirical Bayes (EB) standardization was suggested by Assunção and Reis (1999) as a
means to correct Moran’s I spatial autocorrelation test statistic for varying population
densities across observational units, when the variable of interest is a rate or
proportion. This standardization borrows ideas from the Bayesian shrinkage estimator
outlined in discussion of Empirical Bayes smoothing.</p>
<p>This approach is different from EB smoothing in that the spatial autocorrelation is not
computed for a smoothed version of the original rate, but for a transformed standardized
random variable. In other words, the crude rate is turned into a new variable that has a
mean of zero and unit variance, thus avoiding problems with variance instability. The mean
and variance used in the transformation are computed for each individual observation,
thereby properly accounting for the instability in variance.</p>
<p>The technical aspects are given in detail in Assunção and Reis (1999) and in the review by
Anselin, Lozano-Gracia, and Koschinky (2006), but we briefly touch upon some salient
issues here. The point of departure is the crude rate, say <span class="math inline">\(r_i = O_i/P_i\)</span>, where
<span class="math inline">\(O_i\)</span> is the count of events at location i and <span class="math inline">\(P_i\)</span> is the corresponding population
at risk.</p>
<p>The rationale behind the Assuncao-Reis approach is to standardize each <span class="math inline">\(r_i\)</span> as</p>
<p><span class="math display">\[z_i = \frac{r_i - \beta}{\sqrt{\alpha + (\beta/P_i)}}\]</span></p>
<p>using an estimated mean <span class="math inline">\(\beta\)</span> and standard error <span class="math inline">\(\sqrt{\alpha + (\beta/P_i)}\)</span>.
The parameter <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> are related to the prior distribution for the risk,
which is detailed in the notebook on rate mapping.</p>
<p>In practice, the prior parameters are estimated by means of the so-called method of
moments (e.g., Marshall 1991), yielding the following expressions:</p>
<p><span class="math display">\[\beta=O/P\]</span></p>
<p>With O as the total event count <span class="math inline">\((\Sigma_iO_i)\)</span>, and P as the total population count
<span class="math inline">\((\Sigma_iP_i)\)</span>, and</p>
<p><span class="math display">\[\alpha = [\Sigma_iP_i(r_i - \beta)^2]/P - \beta/(P/n)\]</span></p>
<p>with n as the total number of observations (in other words, P/n is the average population)</p>
<p>One problem with the method of moments estimator is that the expression for <span class="math inline">\(\alpha\)</span>
could yield a negative result. In that case, its value is typically set to zero, i.e.
<span class="math inline">\(\alpha = 0\)</span>. However, Assuncao and Reis(1999), the value for <span class="math inline">\(\alpha\)</span> is set to zero
when the resulting estimate for variance is negative, that is, <span class="math inline">\(\alpha + \beta/P_i &lt;0\)</span>.
Slight differences in the standardized variates may result depending on the convention
used. In GeoDa, when the variance estimate is negative, the original raw rate is used.</p>
</div>
<div id="implementation-1" class="section level3 hasAnchor" number="11.5.2">
<h3><span class="header-section-number">11.5.2</span> Implementation<a href="global-spatial-autocorrelation-2.html#implementation-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To calculate the empirical bayes rates, we will use basic R operations. We start
by calculating the initial variables.</p>
<div class="sourceCode" id="cb821"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb821-1"><a href="global-spatial-autocorrelation-2.html#cb821-1" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">sum</span>(counties<span class="sc">$</span>HC60) <span class="sc">/</span> <span class="fu">sum</span>(counties<span class="sc">$</span>PO60)</span>
<span id="cb821-2"><a href="global-spatial-autocorrelation-2.html#cb821-2" tabindex="-1"></a>r_i <span class="ot">&lt;-</span> counties<span class="sc">$</span>HC60 <span class="sc">/</span> counties<span class="sc">$</span>PO60</span>
<span id="cb821-3"><a href="global-spatial-autocorrelation-2.html#cb821-3" tabindex="-1"></a>P_i <span class="ot">&lt;-</span> counties<span class="sc">$</span>PO60</span>
<span id="cb821-4"><a href="global-spatial-autocorrelation-2.html#cb821-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(r_i)</span>
<span id="cb821-5"><a href="global-spatial-autocorrelation-2.html#cb821-5" tabindex="-1"></a>P <span class="ot">&lt;-</span> <span class="fu">sum</span>(counties<span class="sc">$</span>PO60)</span></code></pre></div>
<p>With the parameters from above, we can calculate <span class="math inline">\(\alpha\)</span>, by the formula specified
in the concept section.</p>
<div class="sourceCode" id="cb822"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb822-1"><a href="global-spatial-autocorrelation-2.html#cb822-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fu">sum</span>(P_i <span class="sc">*</span> (r_i <span class="sc">-</span> beta)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> P <span class="sc">-</span> beta<span class="sc">/</span>(P<span class="sc">/</span>n)</span></code></pre></div>
<p>With <span class="math inline">\(\alpha\)</span>, we can get the standard error used to later calculate the standardized
values.</p>
<div class="sourceCode" id="cb823"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb823-1"><a href="global-spatial-autocorrelation-2.html#cb823-1" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(alpha <span class="sc">+</span> beta<span class="sc">/</span>P_i)</span></code></pre></div>
<p>Now the standardized values are just the crude rate minus <span class="math inline">\(\beta\)</span> and divided by
the standard error.</p>
<div class="sourceCode" id="cb824"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb824-1"><a href="global-spatial-autocorrelation-2.html#cb824-1" tabindex="-1"></a>z_i <span class="ot">&lt;-</span> (r_i <span class="sc">-</span> beta) <span class="sc">/</span> se</span></code></pre></div>
<p>With our standardized values, we can make the lag variable to constuct our
empirical bayes Moran plot. We use <code>lag.listw</code> as before to make the spatial lag
varible.</p>
<div class="sourceCode" id="cb825"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb825-1"><a href="global-spatial-autocorrelation-2.html#cb825-1" tabindex="-1"></a>counties<span class="sc">$</span>hc60_po60 <span class="ot">&lt;-</span> z_i</span>
<span id="cb825-2"><a href="global-spatial-autocorrelation-2.html#cb825-2" tabindex="-1"></a>counties<span class="sc">$</span>lag_hc60_po60 <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(queen.weights, z_i)</span></code></pre></div>
<p>Now with the same <strong>ggplot2</strong> functions as earlier we plot the smoothed rate
variable against the lag smoothed rate variable.</p>
<div class="sourceCode" id="cb826"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb826-1"><a href="global-spatial-autocorrelation-2.html#cb826-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> counties, <span class="fu">aes</span>(<span class="at">x =</span> hc60_po60, <span class="at">y =</span> lag_hc60_po60)) <span class="sc">+</span></span>
<span id="cb826-2"><a href="global-spatial-autocorrelation-2.html#cb826-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb826-3"><a href="global-spatial-autocorrelation-2.html#cb826-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb826-4"><a href="global-spatial-autocorrelation-2.html#cb826-4" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb826-5"><a href="global-spatial-autocorrelation-2.html#cb826-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span><span class="dv">2</span>) </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-469-1.png" width="672" /></p>
<p>To get the regression statistics, we run <code>lm</code> and then examine the summary with
<code>summary</code>.</p>
<div class="sourceCode" id="cb828"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb828-1"><a href="global-spatial-autocorrelation-2.html#cb828-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">lm</span>(lag_hc60_po60 <span class="sc">~</span> hc60_po60, <span class="at">data =</span> counties)</span>
<span id="cb828-2"><a href="global-spatial-autocorrelation-2.html#cb828-2" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lag_hc60_po60 ~ hc60_po60, data = counties)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.05433 -0.34093 -0.09708  0.27749  2.89081 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.001913   0.009724  -0.197    0.844    
## hc60_po60    0.518303   0.010598  48.906   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.54 on 3083 degrees of freedom
## Multiple R-squared:  0.4369, Adjusted R-squared:  0.4367 
## F-statistic:  2392 on 1 and 3083 DF,  p-value: &lt; 2.2e-16</code></pre>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="29">
<li id="fn29"><p>Use <code>setwd(directorypath)</code> to specify the working directory.<a href="global-spatial-autocorrelation-2.html#fnref29" class="footnote-back">↩︎</a></p></li>
<li id="fn30"><p>Use
<code>install.packages(packagename)</code>.<a href="global-spatial-autocorrelation-2.html#fnref30" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="global-spatial-autocorrelation-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="local-spatial-autocorrelation-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/spatialanalysis/handsonspatialdata/edit/master/11-global-spatial-autocorrelation2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
