<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Spatial Data Handling | Hands-On Spatial Data Science with R</title>
  <meta name="description" content="Chapter 1 Spatial Data Handling | Hands-On Spatial Data Science with R" />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Spatial Data Handling | Hands-On Spatial Data Science with R" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="spatialanalysis/handsonspatialdata" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Spatial Data Handling | Hands-On Spatial Data Science with R" />
  
  
  

<meta name="author" content="Luc Anselin, Grant Morrison, Angela Li" />


<meta name="date" content="2019-10-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html">
<link rel="next" href="exploratory-data-analysis-1.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.46.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.46.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i>Disclaimer</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#using-this-book"><i class="fa fa-check"></i>Using This Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#who-this-book-is-for"><i class="fa fa-check"></i>Who This Book Is For</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html"><i class="fa fa-check"></i><b>1</b> Spatial Data Handling</a><ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#introduction-1"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#objectives"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#preliminaries"><i class="fa fa-check"></i>Preliminaries</a><ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#loading-packages"><i class="fa fa-check"></i>Loading packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#obtaining-data-from-the-chicago-open-data-portal"><i class="fa fa-check"></i>Obtaining data from the Chicago Open Data portal</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#selecting-observations-for-a-given-time-period"><i class="fa fa-check"></i>Selecting Observations for a Given Time Period</a><ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-observations-for-the-desired-time-period"><i class="fa fa-check"></i>Extracting observations for the desired time period</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#selecting-the-variables-for-the-final-table"><i class="fa fa-check"></i>Selecting the variables for the final table</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-point-layer"><i class="fa fa-check"></i>Creating a Point Layer</a><ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-point-layer-from-coordinates-in-a-table---principle"><i class="fa fa-check"></i>Creating a point layer from coordinates in a table - principle</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-spatial-points-object"><i class="fa fa-check"></i>Creating a spatial points object</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#abandoned-vehicles-by-community-area"><i class="fa fa-check"></i>Abandoned Vehicles by Community Area</a><ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#community-area-boundary-file"><i class="fa fa-check"></i>Community Area boundary file</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#spatial-join"><i class="fa fa-check"></i>Spatial join</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#counts-by-community-area"><i class="fa fa-check"></i>Counts by community area</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#mapping-the-vehicle-counts"><i class="fa fa-check"></i>Mapping the vehicle counts</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#community-area-population-data"><i class="fa fa-check"></i>Community Area Population Data</a><ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-a-pdf-file"><i class="fa fa-check"></i>Extracting a pdf file</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#parsing-the-pdf-file"><i class="fa fa-check"></i>Parsing the pdf file</a></li>
<li class="chapter" data-level="1.0.1" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#extracting-the-population-values"><i class="fa fa-check"></i><b>1.0.1</b> Extracting the population values</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#creating-a-data-frame-with-population-values"><i class="fa fa-check"></i>Creating a data frame with population values</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#mapping-community-area-abandoned-vehicles-per-capita"><i class="fa fa-check"></i>Mapping Community Area Abandoned Vehicles Per Capita</a><ul>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#computing-abandoned-vehicles-per-capita"><i class="fa fa-check"></i>Computing abandoned vehicles per capita</a></li>
<li class="chapter" data-level="" data-path="spatial-data-handling.html"><a href="spatial-data-handling.html#final-choropleth-map"><i class="fa fa-check"></i>Final choropleth map</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html"><i class="fa fa-check"></i><b>2</b> Exploratory Data Analysis 1</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#introduction-2"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#objectives-1"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#preliminaries-1"><i class="fa fa-check"></i>Preliminaries</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#load-packages"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#obtaining-the-data"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#analyzing-the-distribution-of-a-single-variable"><i class="fa fa-check"></i>Analyzing the Distribution of a Single Variable</a><ul>
<li><a href="exploratory-data-analysis-1.html#a-quick-introduction-to-ggplot">A quick introduction to <strong>ggplot</strong></a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#bivariate-analysis-the-scatter-plot"><i class="fa fa-check"></i>Bivariate Analysis: The Scatter Plot</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#smoothing-the-scatter-plot"><i class="fa fa-check"></i>Smoothing the scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#spatial-heterogeneity"><i class="fa fa-check"></i>Spatial heterogeneity</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#structural-breaks-in-the-scatter-plot"><i class="fa fa-check"></i>Structural breaks in the scatter plot</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-1.html"><a href="exploratory-data-analysis-1.html#chow-test"><i class="fa fa-check"></i>Chow test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html"><i class="fa fa-check"></i><b>3</b> Exploratory Data Analysis 2</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#introduction-3"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#objectives-2"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#preliminaries-2"><i class="fa fa-check"></i>Preliminaries</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#load-packages-1"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#obtaining-the-data-1"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#scatter-plot-matrix"><i class="fa fa-check"></i>Scatter Plot Matrix</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#basic-scatter-plot-matrix"><i class="fa fa-check"></i>Basic scatter plot matrix</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#scatter-plot-matrix-with-smoothing"><i class="fa fa-check"></i>Scatter plot matrix with smoothing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#three-variables-bubble-chart-and-3d-scatter-plot"><i class="fa fa-check"></i>Three Variables: Bubble Chart and 3D Scatter Plot</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#bubble-chart"><i class="fa fa-check"></i>Bubble chart</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#d-scatter-plot"><i class="fa fa-check"></i>3D Scatter Plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#true-multivariate-eda-parallel-coordinate-plot-and-conditional-plots"><i class="fa fa-check"></i>True Multivariate EDA: Parallel Coordinate Plot and Conditional Plots</a><ul>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#parallel-coordinate-plot-pcp"><i class="fa fa-check"></i>Parallel Coordinate Plot (PCP)</a></li>
<li class="chapter" data-level="" data-path="exploratory-data-analysis-2.html"><a href="exploratory-data-analysis-2.html#conditional-plots"><i class="fa fa-check"></i>Conditional Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="basic-mapping.html"><a href="basic-mapping.html"><i class="fa fa-check"></i><b>4</b> Basic Mapping</a><ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#introduction-4"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#objectives-3"><i class="fa fa-check"></i>Objectives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#preliminaries-3"><i class="fa fa-check"></i>Preliminaries</a><ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#load-packages-2"><i class="fa fa-check"></i>Load packages</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#obtaining-the-data-2"><i class="fa fa-check"></i>Obtaining the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#basic-choropleth-mapping"><i class="fa fa-check"></i>Basic Choropleth Mapping</a><ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#default-settings-1"><i class="fa fa-check"></i>Default settings</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#color-palette"><i class="fa fa-check"></i>Color palette</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#legend"><i class="fa fa-check"></i>Legend</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#title"><i class="fa fa-check"></i>Title</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#border-options"><i class="fa fa-check"></i>Border options</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#interactive-base-map"><i class="fa fa-check"></i>Interactive base map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#saving-a-map-as-a-file"><i class="fa fa-check"></i>Saving a map as a file</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#shape-centers"><i class="fa fa-check"></i>Shape centers</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#common-map-classifications"><i class="fa fa-check"></i>Common Map Classifications</a><ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#quantile-map"><i class="fa fa-check"></i>Quantile map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#natural-breaks-map"><i class="fa fa-check"></i>Natural breaks map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#equal-intervals-map"><i class="fa fa-check"></i>Equal intervals map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#custom-breaks"><i class="fa fa-check"></i>Custom breaks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#extreme-value-maps"><i class="fa fa-check"></i>Extreme Value Maps</a><ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#percentile-map"><i class="fa fa-check"></i>Percentile map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#box-map"><i class="fa fa-check"></i>Box map</a></li>
<li class="chapter" data-level="4.0.1" data-path="basic-mapping.html"><a href="basic-mapping.html#standard-deviation-map"><i class="fa fa-check"></i><b>4.0.1</b> Standard deviation map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#mapping-categorical-variables"><i class="fa fa-check"></i>Mapping Categorical Variables</a><ul>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#unique-value-map"><i class="fa fa-check"></i>Unique value map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#co-location-map"><i class="fa fa-check"></i>Co-location map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#conditional-map"><i class="fa fa-check"></i>Conditional Map</a></li>
<li class="chapter" data-level="" data-path="basic-mapping.html"><a href="basic-mapping.html#cartogram"><i class="fa fa-check"></i>Cartogram</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Hands-On Spatial Data Science with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="spatial-data-handling" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Spatial Data Handling</h1>
<div id="introduction-1" class="section level2 unnumbered">
<h2>Introduction</h2>
<p>This R notebook covers the functionality of the <a href="http://geodacenter.github.io/workbook/1_datascience/lab1.html">Spatial Data Handling</a> section of the GeoDa workbook. We refer to that document for details on the methodology, references, etc. The goal of these notes is to approximate as closely as possible the operations carried out using GeoDa by means of a range of R packages.</p>
<p>The notes are written with R beginners in mind, more seasoned R users can probably skip most of the comments
on data structures and other R particulars. Also, as always in R, there are typically several ways to achieve a specific objective, so what is shown here is just one way that works, but there often are others (that may even be more elegant, work faster, or scale better).</p>
<p>In this lab, we will use the City of Chicago open data portal to download data on abandoned vehicles. Our end goal is to create a choropleth map with abandoned vehicles per capita for Chicago community areas. Before we can create the maps, we will need to download the information, select observations, aggregate data, join different files and carry out variable transformations in order to obtain a so-called “spatially intensive” variable for mapping (i.e., not just a count of abandoned vehicles, but a per capita ratio).</p>
<div id="objectives" class="section level3 unnumbered">
<h3>Objectives</h3>
<p>After completing the notebook, you should know how to carry out the following tasks:</p>
<ul>
<li><p>Download data from any Socrata-driven open data portal, such as the
<a href="https://data.cityofchicago.org">City of Chicago open data portal</a></p></li>
<li><p>Filtering a data frame for specific entries</p></li>
<li><p>Selecting and renaming columns</p></li>
<li><p>Creating a simple features spatial object</p></li>
<li><p>Checking and adding/adjusting projection information</p></li>
<li><p>Dealing with missing data</p></li>
<li><p>Spatial join</p></li>
<li><p>Spatial aggregation</p></li>
<li><p>Parsing a pdf file</p></li>
<li><p>Merging data sets</p></li>
<li><p>Creating new variables</p></li>
<li><p>Basic choropleth mapping</p></li>
</ul>
<div id="r-packages-used" class="section level4 unnumbered">
<h4>R Packages used</h4>
<ul>
<li><p><strong>RSocrata</strong>: to read data directly from a Socrata powered open data portal, such as the Chicago open data portal</p></li>
<li><p><strong>tidyverse</strong> (includes <strong>dplyr</strong>): to manipulate data frames, such as filtering data, selecting columns, and creating new variables</p></li>
<li><p><strong>lubridate</strong>: to select information out of the <em>date</em> format when filtering the data</p></li>
<li><p><strong>sf</strong>: to create and manipulate simple features spatial objects, to read in the boundary file, and perform point in polygon on the data set to fill in missing community area information</p></li>
<li><p><strong>pdftools</strong>: to read and parse a pdf for chicago community area population information</p></li>
<li><p><strong>tmap</strong>: to make nice looking choropleth maps</p></li>
</ul>
</div>
<div id="r-commands-used" class="section level4 unnumbered">
<h4>R Commands used</h4>
<p>Below follows a list of the commands used in this notebook. For further details
and a comprehensive list of options, please consult the
<a href="https://www.rdocumentation.org">R documentation</a>.</p>
<ul>
<li><p><strong>base R</strong>: <code>setwd</code>, <code>install.packages</code>, <code>library</code>, <code>head</code>, <code>dim</code>, <code>class</code>, <code>as.Date</code>, <code>names</code>, <code>!is.na</code>, <code>is.numeric</code>, <code>as.integer</code>, <code>is.integer</code>, <code>length</code>, <code>strsplit</code>, <code>unlist</code>, <code>for</code>, <code>vector</code>, <code>substr</code>, <code>gsub</code>, <code>as.numeric</code>, <code>data.frame</code></p></li>
<li><p><strong>RSocrata</strong>: <code>read.socrata</code></p></li>
<li><p><strong>tidyverse</strong>: <code>filter</code>, <code>%&gt;%</code> (pipe), <code>select</code> (with renaming), <code>count</code>, <code>rename</code>, <code>mutate</code></p></li>
<li><p><strong>lubridate</strong>: <code>year</code>, <code>month</code></p></li>
<li><p><strong>sf</strong>: <code>st_as_sf</code>, <code>plot</code>, <code>st_crs</code>, <code>read_sf</code>, <code>st_transform</code>, <code>st_join</code>, <code>st_geometry</code>, <code>st_write</code></p></li>
<li><p><strong>pdftools</strong>: <code>pdf_text</code></p></li>
<li><p><strong>tmap</strong>: <code>tm_shape</code>, <code>tm_polygons</code></p></li>
</ul>
</div>
</div>
</div>
<div id="preliminaries" class="section level2 unnumbered">
<h2>Preliminaries</h2>
<p>Before starting, make sure to have the latest version of R and of packages that are compiled for the matching version of R (this document was created using R 3.5.1 of 2018-07-02). Also, optionally, set a working directory, even though we will not
actually be saving any files.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div id="loading-packages" class="section level3 unnumbered">
<h3>Loading packages</h3>
<p>First, we load all the required packages using the <code>library</code> command. If you don’t have some of these in your system, make sure to install them first as well as
their dependencies.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> You will get an error message if something is missing. If needed, just install the missing piece and everything will work after that.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggplot2&#39;:
##   method         from 
##   [.quosures     rlang
##   c.quosures     rlang
##   print.quosures rlang</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;rvest&#39;:
##   method            from
##   read_xml.response xml2</code></pre>
<pre><code>## ── Attaching packages ─────────────────</code></pre>
<pre><code>## ✔ ggplot2 3.1.1     ✔ purrr   0.3.2
## ✔ tibble  2.1.1     ✔ dplyr   0.8.3
## ✔ tidyr   1.0.0     ✔ stringr 1.4.0
## ✔ readr   1.3.1     ✔ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ──────────────────────────
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lubridate)</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     date</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(sf)</code></pre>
<pre><code>## Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tmap)
<span class="kw">library</span>(pdftools)
<span class="kw">library</span>(RSocrata)</code></pre>
</div>
</div>
<div id="obtaining-data-from-the-chicago-open-data-portal" class="section level2 unnumbered">
<h2>Obtaining data from the Chicago Open Data portal</h2>
<p>We will use the specialized <strong>RSocrata</strong> package to download the file with 311 calls about abandoned vehicles from the <a href="https://data.cityofchicago.org">City of Chicago open data portal</a>. A list of different types of 311 nuisance calls is given by selecting the button for
<a href="https://data.cityofchicago.org/browse?category=Service%20Requests">Service Requests</a>.
The abandoned vehicles data are contained in the entry for
<a href="https://data.cityofchicago.org/Service-Requests/311-Service-Requests-Abandoned-Vehicles/3c9v-pnva">311 Service Requests - Abandoned Vehicles</a>.</p>
<p>Select the <strong>API</strong> button and copy the <strong>API Endpoint</strong> from the interface. This is the
target file that we will download using the <code>read.socrata</code> function from the
<strong>RSocrata</strong> package. Note, this is a large file, so it may take a while to download.</p>
<p>First, we set the target file name to pass to the <code>read.socrata</code> function. Copy the
API Endpoint and paste the file path, as shown below.</p>
<pre class="sourceCode r"><code class="sourceCode r">socrata.file &lt;-<span class="st"> &quot;https://data.cityofchicago.org/resource/suj7-cg3j.csv&quot;</span></code></pre>
<p>Next, download the file using <code>read.socrata</code>. This will turn the data into an R data frame. After the download is completed, we use the <code>head</code> command to get a sense of the contents of the data frame.</p>
<pre class="sourceCode r"><code class="sourceCode r">vehicle.data &lt;-<span class="st"> </span><span class="kw">read.socrata</span>(socrata.file)</code></pre>
<pre><code>## Warning: partial match of &#39;header&#39; to &#39;headers&#39;

## Warning: partial match of &#39;header&#39; to &#39;headers&#39;

## Warning: partial match of &#39;header&#39; to &#39;headers&#39;

## Warning: partial match of &#39;header&#39; to &#39;headers&#39;

## Warning: partial match of &#39;header&#39; to &#39;headers&#39;

## Warning: partial match of &#39;header&#39; to &#39;headers&#39;

## Warning: partial match of &#39;header&#39; to &#39;headers&#39;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(vehicle.data)</code></pre>
<pre><code>##   creation_date          status completion_date service_request_number
## 1    2011-01-01 Completed - Dup      2011-01-07            11-00002779
## 2    2011-01-01 Completed - Dup      2011-01-20            11-00003001
## 3    2011-01-01 Completed - Dup      2011-01-21            11-00003309
## 4    2011-01-01 Completed - Dup      2011-01-21            11-00003316
## 5    2011-01-01       Completed      2011-01-05            11-00001976
## 6    2011-01-01       Completed      2011-01-05            11-00002291
##       type_of_service_request
## 1 Abandoned Vehicle Complaint
## 2 Abandoned Vehicle Complaint
## 3 Abandoned Vehicle Complaint
## 4 Abandoned Vehicle Complaint
## 5 Abandoned Vehicle Complaint
## 6 Abandoned Vehicle Complaint
##                                         license_plate vehicle_make_model
## 1 REAR PLATE STARTS W/848 AND FRONT PLATE STARTS W/ K              Isuzu
## 2                                             9381880             Toyota
## 3                                          MI S CS860      Jeep/Cherokee
## 4                                           MI SCS860                   
## 5                                             H924236               Ford
## 6                         810 LYB    WISCONSIN PLATES            Mercury
##   vehicle_color current_activity most_recent_action
## 1           Red                                    
## 2        Silver                                    
## 3          Gold                                    
## 4          Gold                                    
## 5         White                                    
## 6         Green                                    
##   how_many_days_has_the_vehicle_been_reported_as_parked_
## 1                                                     24
## 2                                                     NA
## 3                                                     NA
## 4                                                     NA
## 5                                                     60
## 6                                                     NA
##         street_address zip_code x_coordinate y_coordinate ward
## 1   5629 N KEDVALE AVE    60646      1147717      1937054   39
## 2  2053 N KILBOURN AVE    60639      1146056      1913269   31
## 3      736 W BUENA AVE    60613      1170576      1928214   46
## 4      736 W BUENA AVE    60613      1170576      1928214   46
## 5  6059 S KOMENSKY AVE    60629      1150408      1864110   13
## 6 4651 S WASHTENAW AVE    60632      1159150      1873712   12
##   police_district community_area ssa latitude longitude
## 1              17             13  NA 41.98368 -87.73197
## 2              25             20  NA 41.91859 -87.73868
## 3              23              3  NA 41.95861 -87.64888
## 4              23              3  NA 41.95861 -87.64888
## 5               8             65   3 41.78237 -87.72394
## 6               9             58  NA 41.80864 -87.69163
##                                       location location_address
## 1 POINT (41.983680361597564 -87.7319663736746)             &lt;NA&gt;
## 2 POINT (41.91858774162382 -87.73868431751842)             &lt;NA&gt;
## 3 POINT (41.95860696269331 -87.64887590959788)             &lt;NA&gt;
## 4 POINT (41.95860696269331 -87.64887590959788)             &lt;NA&gt;
## 5 POINT (41.78237428405976 -87.72394038021173)             &lt;NA&gt;
## 6 POINT (41.80863500843091 -87.69162625248853)             &lt;NA&gt;
##   location_city location_state location_zip
## 1          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 2          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 3          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 4          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 5          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 6          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;</code></pre>
<p>A quick glance at the table reveals quite a bit of missing information, something
we will have to deal with. We also check the dimension of this data frame using the
<code>dim</code> command:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(vehicle.data)</code></pre>
<pre><code>## [1] 238426     26</code></pre>
<p>The table has 203,657 observations on 26 variables (the number of observations shown
may be slightly different as the table is constantly updated).</p>
<p>In RStudio, the type of the variable in each column is listed under its name. For example, under <strong>creation_date</strong>, we see <strong>S3: POSIXct</strong>. You can also find out the same information by applying a <code>class</code> command to the variable
<strong>vehicle.data$creation_date</strong>, as in</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(vehicle.data<span class="op">$</span>creation_date)</code></pre>
<pre><code>## [1] &quot;POSIXct&quot; &quot;POSIXt&quot;</code></pre>
<p>The result again yields <strong>POSIXct</strong>, which is a common format used for <em>dates</em>.</p>
<p>Note that <strong>RSocrata</strong> is able to tell the date format from a simple string. In contrast, if we had downloaded the file manually as a csv (comma separated value) file, this would not be the case (see the GeoDa example). In that instance, we would have to convert the <strong>creation_date</strong> to a date format explicitly using <code>as.Date</code>.</p>
</div>
<div id="selecting-observations-for-a-given-time-period" class="section level2 unnumbered">
<h2>Selecting Observations for a Given Time Period</h2>
<p>As in the GeoDa example, we are not using all the data, but will analyze the abandoned vehicle locations for a given time period, i.e., the month of September 2016.</p>
<div id="extracting-observations-for-the-desired-time-period" class="section level3 unnumbered">
<h3>Extracting observations for the desired time period</h3>
<p>To extract the observations for the selected year (2016) and month (9), we will use the <code>year</code> and <code>month</code> functions from the <strong>lubridate</strong> package. We will embed these expressions in a <code>filter</code> command (from <strong>tidyverse</strong>) to select the rows/observations that match the specified criterion. We will also use the pipe command <code>%&gt;%</code> to move the original data frame through the different filter stages and assign the end result to <strong>vehicle.sept16</strong>.</p>
<p>We again check the contents with a <code>head</code> command.</p>
<pre class="sourceCode r"><code class="sourceCode r">vehicle.sept16 &lt;-<span class="st"> </span>vehicle.data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">year</span>(creation_date) <span class="op">==</span><span class="st"> </span><span class="dv">2016</span>) <span class="op">%&gt;%</span>
<span class="st">                  </span><span class="kw">filter</span>(<span class="kw">month</span>(creation_date) <span class="op">==</span><span class="st"> </span><span class="dv">9</span>)
<span class="kw">head</span>(vehicle.sept16)</code></pre>
<pre><code>##   creation_date          status completion_date service_request_number
## 1    2016-09-01 Completed - Dup      2016-09-01            16-06192603
## 2    2016-09-01 Completed - Dup      2016-09-01            16-06192662
## 3    2016-09-01 Completed - Dup      2016-09-01            16-06193608
## 4    2016-09-01 Completed - Dup      2016-09-01            16-06194284
## 5    2016-09-01 Completed - Dup      2016-09-01            16-06194594
## 6    2016-09-01 Completed - Dup      2016-09-01            16-06197569
##       type_of_service_request license_plate vehicle_make_model
## 1 Abandoned Vehicle Complaint       UNKNOWN          Chevrolet
## 2 Abandoned Vehicle Complaint       UNKNOWN                   
## 3 Abandoned Vehicle Complaint        UKNOWN                   
## 4 Abandoned Vehicle Complaint     NO PLATES               Ford
## 5 Abandoned Vehicle Complaint                                 
## 6 Abandoned Vehicle Complaint                                 
##   vehicle_color current_activity most_recent_action
## 1         White    FVI - Outcome  Create Work Order
## 2         Green    FVI - Outcome  Create Work Order
## 3          Gray    FVI - Outcome  Create Work Order
## 4          Blue    FVI - Outcome  Create Work Order
## 5                  FVI - Outcome  Create Work Order
## 6                  FVI - Outcome  Create Work Order
##   how_many_days_has_the_vehicle_been_reported_as_parked_
## 1                                                     14
## 2                                                     40
## 3                                                      7
## 4                                                     30
## 5                                                     NA
## 6                                                     NA
##          street_address zip_code x_coordinate y_coordinate ward
## 1        3710 W IOWA ST    60651      1151452      1905748   27
## 2   5240 S MAYFIELD AVE    60638      1137921      1869254   14
## 3     8000 S ALBANY AVE    60652      1157102      1851405   18
## 4  8654 W CATHERINE AVE    60656      1117638      1934535   41
## 5 4315 N MONTICELLO AVE    60618      1151283      1928434   35
## 6   2241 N MULLIGAN AVE    60639      1133710      1914324   36
##   police_district community_area ssa latitude longitude
## 1              11             23  NA 41.89736 -87.71933
## 2               8             56  NA 41.79688 -87.76990
## 3               8             70  NA 41.74792 -87.70005
## 4              16             76  NA 41.97694 -87.84349
## 5              17             16  NA 41.95972 -87.71907
## 6              25             19  NA 41.92154 -87.78402
##                                        location location_address
## 1  POINT (41.89736153676566 -87.71933325878982)             &lt;NA&gt;
## 2 POINT (41.796881421903066 -87.76989633815052)             &lt;NA&gt;
## 3  POINT (41.74792366108626 -87.70004701460941)             &lt;NA&gt;
## 4   POINT (41.97694235046974 -87.8434945723464)             &lt;NA&gt;
## 5  POINT (41.95972327912134 -87.71906810908936)             &lt;NA&gt;
## 6  POINT (41.92154133910697 -87.78401648793171)             &lt;NA&gt;
##   location_city location_state location_zip
## 1          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 2          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 3          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 4          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 5          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;
## 6          &lt;NA&gt;           &lt;NA&gt;         &lt;NA&gt;</code></pre>
<p>and the dimension:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(vehicle.sept16)</code></pre>
<pre><code>## [1] 2637   26</code></pre>
<p>The filtered table now only has 2,637 observations.</p>
</div>
<div id="selecting-the-variables-for-the-final-table" class="section level3 unnumbered">
<h3>Selecting the variables for the final table</h3>
<p>The current data frame contains 26 variables. Several of these are not really of interest to us, since we basically want the locations of the events. We will use
the <code>select</code> command from <strong>tidyverse</strong> to pick out the columns that we want to keep. In addition, we will use the rename option in <code>select</code> to give new variable names. While this is not absolutely necessary at this stage (<strong>RSocrata</strong> has turned
any <em>weird</em> variable names into proper R names), we may later want to save the
data as a point shape file. The data associated with a shape file are store in a
separate dBase file, and dBase only allows 10 characters for variable names.</p>
<p>So, in order to save ourselves some work later on, we will rename the selected
variables to strings that do not exceed 10 characters.</p>
<p>First, we check the variable names using the <code>names</code> command.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(vehicle.sept16)</code></pre>
<pre><code>##  [1] &quot;creation_date&quot;                                         
##  [2] &quot;status&quot;                                                
##  [3] &quot;completion_date&quot;                                       
##  [4] &quot;service_request_number&quot;                                
##  [5] &quot;type_of_service_request&quot;                               
##  [6] &quot;license_plate&quot;                                         
##  [7] &quot;vehicle_make_model&quot;                                    
##  [8] &quot;vehicle_color&quot;                                         
##  [9] &quot;current_activity&quot;                                      
## [10] &quot;most_recent_action&quot;                                    
## [11] &quot;how_many_days_has_the_vehicle_been_reported_as_parked_&quot;
## [12] &quot;street_address&quot;                                        
## [13] &quot;zip_code&quot;                                              
## [14] &quot;x_coordinate&quot;                                          
## [15] &quot;y_coordinate&quot;                                          
## [16] &quot;ward&quot;                                                  
## [17] &quot;police_district&quot;                                       
## [18] &quot;community_area&quot;                                        
## [19] &quot;ssa&quot;                                                   
## [20] &quot;latitude&quot;                                              
## [21] &quot;longitude&quot;                                             
## [22] &quot;location&quot;                                              
## [23] &quot;location_address&quot;                                      
## [24] &quot;location_city&quot;                                         
## [25] &quot;location_state&quot;                                        
## [26] &quot;location_zip&quot;</code></pre>
<p>To keep things simple, we will only keep <strong>community_area</strong>, <strong>latitude</strong> and
<strong>longitude</strong>, and turn them into <strong>comm</strong>, <strong>lat</strong> and <strong>lon</strong>. The new data set is <strong>vehicles.final</strong>. Note that to rename a variable, the new name is listed first, on the left hand side of the equal sign, and the old name is on the right hand side.
We check the result with the <code>head</code> command.</p>
<pre class="sourceCode r"><code class="sourceCode r">vehicles.final &lt;-<span class="st"> </span>vehicle.sept16 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="dt">comm =</span> community_area, 
                          <span class="dt">lat =</span> latitude, <span class="dt">lon =</span> longitude)
<span class="kw">head</span>(vehicles.final)</code></pre>
<pre><code>##   comm      lat       lon
## 1   23 41.89736 -87.71933
## 2   56 41.79688 -87.76990
## 3   70 41.74792 -87.70005
## 4   76 41.97694 -87.84349
## 5   16 41.95972 -87.71907
## 6   19 41.92154 -87.78402</code></pre>
</div>
</div>
<div id="creating-a-point-layer" class="section level2 unnumbered">
<h2>Creating a Point Layer</h2>
<p>So far, we have only dealt with a regular data frame, without taking advantage of any spatial features. However, the data frame contains fields with coordinates and R can turn these into an explicit spatial points layer that can be saved in a range of GIS formats. To accomplish this, we will use the (new) simple features or <strong>sf</strong> package functionality, which improves upon the older <strong>sp</strong>.</p>
<p>We will first use the <strong>lat</strong> and <strong>lon</strong> columns in the data frame to create a
spatial points object. Note that <strong>lon</strong> is the x-coordinate and <strong>lat</strong> is the y-coordinate.</p>
<div id="creating-a-point-layer-from-coordinates-in-a-table---principle" class="section level3 unnumbered">
<h3>Creating a point layer from coordinates in a table - principle</h3>
<p>In <strong>sf</strong>, a simple features object is constructed by combining a <em>geometry</em> with the actual data (in a data frame). However, this is simplified for <em>point objects</em> when the data frame contains the coordinates as variables. This is the case in our example, where we have latitude and longitude. We also have x and y, but since we are not sure what projection these coordinates correspond with, they are not useful at this stage.</p>
<p>The advantage of lat-lon is that they are decimal degrees, and thus unprojected.
However, we can provide the information on the datum, typically WGS84 (the standard
used in most applications for decimal degrees) by passing the coordinate reference
system argument (<code>crs</code>) set to the <strong>EPSG</strong> code 4326. After that, we can
use the built-in projection transformation functionality in <strong>sf</strong> to turn the points into any projection we want.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<div id="missing-coordinates" class="section level4 unnumbered">
<h4>Missing coordinates</h4>
<p>In order to create a points layer, we need coordinates for every observation. However,
as we can see from the <code>head</code> command above, there are (at least) two observations that do not have lat-lon information. Before we can proceed, we need to remove these from the data frame.</p>
<p>We again use a <code>filter</code> command, but now combine it with the <code>!is.na</code> expression,
i.e., is not missing (na). We take a little short cut by assuming that if one of lat or lon is missing, the other one will be missing as well (although to keep it completely general, we would need to check each variable separately). We assign the result
to the <strong>vehicle.coord</strong> data frame.</p>
<pre class="sourceCode r"><code class="sourceCode r">vehicle.coord &lt;-<span class="st"> </span>vehicles.final <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span>(<span class="kw">is.na</span>(lat)))
<span class="kw">dim</span>(vehicle.coord)</code></pre>
<pre><code>## [1] 2635    3</code></pre>
<p>As it turns out, the two rows we noticed above were the only two with missing coordinates (the number of rows went from 2,637 to 2,635).</p>
</div>
</div>
<div id="creating-a-spatial-points-object" class="section level3 unnumbered">
<h3>Creating a spatial points object</h3>
<p>The <strong>sf</strong> package turns a non-spatial object like a data frame into a
simple features spatial object by means of the <code>st_as_sf</code> function. This function can take a large number of arguments, but for now we will only use a few:</p>
<ul>
<li><p>the name of the data frame, i.e., vehicle.coord</p></li>
<li><p><code>coords</code>: the variable names for x and y (given in parentheses)</p></li>
<li><p><code>crs</code>: the coordinate reference system, here using the EPSG code of 4326</p></li>
<li><p><code>agr</code>: the so-called attibute-geometry-relationship which specifies how the attribute information (the data) relate to the geometry (the points); in our
example, we will use “constant”</p></li>
</ul>
<p>In our example, we create <strong>vehicle.points</strong> and check its class.</p>
<pre class="sourceCode r"><code class="sourceCode r">vehicle.points =<span class="st"> </span><span class="kw">st_as_sf</span>(vehicle.coord, <span class="dt">coords =</span> <span class="kw">c</span>(<span class="st">&quot;lon&quot;</span>, <span class="st">&quot;lat&quot;</span>), <span class="dt">crs =</span> <span class="dv">4326</span>, <span class="dt">agr =</span> <span class="st">&quot;constant&quot;</span>)
<span class="kw">class</span>(vehicle.points)</code></pre>
<pre><code>## [1] &quot;sf&quot;         &quot;data.frame&quot;</code></pre>
<p>Even though it is not that informative at this stage, we can also make a quick <code>plot</code>.
Later, we will see how we can refine these plots using the <strong>tmap</strong> package.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(vehicle.points)</code></pre>
<pre><code>## Warning in seq.default(0.5 * cutoff.tails[1], 1 - 0.5 * cutoff.tails[2], :
## partial argument match of &#39;length&#39; to &#39;length.out&#39;</code></pre>
<pre><code>## Warning in plot.default(1, 1, t = &quot;n&quot;, ylim = ylim, xlim = xlim, axes =
## FALSE, : partial argument match of &#39;t&#39; to &#39;type&#39;</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>We can also do a quick check of the projection information using the
<code>st_crs</code> command.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_crs</span>(vehicle.points)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<p>The <strong>proj4string</strong> is a slightly more informative description than the simple EPSG code and confirms the data are not projected (longlat) using the WGS84 datum for the decimal degree coordinates.</p>
</div>
</div>
<div id="abandoned-vehicles-by-community-area" class="section level2 unnumbered">
<h2>Abandoned Vehicles by Community Area</h2>
<p>At this point, we will go about things in a slightly different way from how
they are illustrated in the GeoDa workbook example. As it turns out, some of the points have missing community area information, which is a critical element to compute the number of abandoned cars at that scale. In GeoDa, we used a visual approach to obtain the missing information. Here, we will exploit some of the GIS functionality in <strong>sf</strong> to carry out a <strong>spatial join</strong>. This boils down to identifying which points belong to each community area (a so-called <em>point in polygon query</em>) and assigning the corresponding community area identifier to each point.</p>
<p>We proceed in three steps. First, we create a simple features spatial polygon object with the boundaries of the community areas, which we download from the Chicago Open Data portal. Next,
we carry out a spatial join between our points object and the polygon object to assign a community area code to each point. Finally, we compute the point count by community area.</p>
<div id="community-area-boundary-file" class="section level3 unnumbered">
<h3>Community Area boundary file</h3>
<p>We resort to the City of Chicago open data portal for the boundary file of
the community areas.
From the opening screen, select the button for
<a href="https://data.cityofchicago.org/browse?category=Facilities+%26+Geographic%20Boundaries">Facilities &amp; Geo Boundaries</a>. This yields a list of different boundary files for a range of geographic areal units. The one for the community areas is
<a href="https://data.cityofchicago.org/Facilities-Geographic-Boundaries/Boundaries-Community-Areas-current-/cauq-8yn6">Boundaries - Community Areas (current)</a>. This brings up an overview map of the geography of the community areas of Chicago. Of course, we could simply select one of the export buttons to download the files, but we want to do this programmatically. As it turns out, <strong>sf</strong> can read a <strong>geojson</strong> formatted file directly from the web, and we will exploit that functionality.</p>
<p>First, we need the name for the file. We can check the Socrata API file name, but that contains a <strong>json</strong> file, and we want a specific <strong>geojson</strong> file. As it turns out, the latter is simply the same file name, but with the <strong>geojson</strong> file extension. We set our
variable <strong>comm.file</strong> to this URL and then use <code>sf_read</code> to load the boundary information into <strong>chicago.comm</strong>. As before, we can do a quick check of the class using the <code>class</code> command.</p>
<pre class="sourceCode r"><code class="sourceCode r">comm.file &lt;-<span class="st"> &quot;https://data.cityofchicago.org/resource/igwz-8jzy.geojson&quot;</span>
chicago.comm &lt;-<span class="st"> </span><span class="kw">read_sf</span>(comm.file)
<span class="kw">class</span>(chicago.comm)</code></pre>
<pre><code>## [1] &quot;sf&quot;         &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre>
<p>In addition, we check the projection information using <code>st_crs</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_crs</span>(chicago.comm)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 4326 
##   proj4string: &quot;+proj=longlat +datum=WGS84 +no_defs&quot;</code></pre>
<p>Again, the layer is unprojected in decimal degrees. Also, a quick <code>plot</code>. Note that,
by default, <strong>sf</strong> draws a choropleth map for each variable included in the data frame. Since we won’t be using <strong>sf</strong> for mapping, we ignore that aspect for now.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(chicago.comm)</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>We also use <code>head</code> to check on the types of the variables.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(chicago.comm)</code></pre>
<pre><code>## Simple feature collection with 6 features and 9 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -87.7069 ymin: 41.79448 xmax: -87.58001 ymax: 41.99076
## epsg (SRID):    4326
## proj4string:    +proj=longlat +datum=WGS84 +no_defs
## # A tibble: 6 x 10
##   community area  shape_area perimeter area_num_1 area_numbe comarea_id
##   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;     
## 1 DOUGLAS   0     46004621.… 0         35         35         0         
## 2 OAKLAND   0     16913961.… 0         36         36         0         
## 3 FULLER P… 0     19916704.… 0         37         37         0         
## 4 GRAND BO… 0     48492503.… 0         38         38         0         
## 5 KENWOOD   0     29071741.… 0         39         39         0         
## 6 LINCOLN … 0     71352328.… 0         4          4          0         
## # … with 3 more variables: comarea &lt;chr&gt;, shape_len &lt;chr&gt;,
## #   geometry &lt;MULTIPOLYGON [°]&gt;</code></pre>
<div id="changing-projections" class="section level4 unnumbered">
<h4>Changing projections</h4>
<p>Before moving on to the spatial join operation, we will convert both the community area boundaries and the vehicle points to the same projection, using the <code>st_transform</code>
command. We assign the UTM (Universal Tranverse Mercator) zone 16N, which the the proper one for Chicago, with an EPSG code of 32616. After the projection transformation, we
check the result using <code>st_crs</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">chicago.comm &lt;-<span class="st"> </span><span class="kw">st_transform</span>(chicago.comm,<span class="dv">32616</span>)
<span class="kw">st_crs</span>(chicago.comm)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 32616 
##   proj4string: &quot;+proj=utm +zone=16 +datum=WGS84 +units=m +no_defs&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">vehicle.points &lt;-<span class="st"> </span><span class="kw">st_transform</span>(vehicle.points,<span class="dv">32616</span>)
<span class="kw">st_crs</span>(vehicle.points)</code></pre>
<pre><code>## Coordinate Reference System:
##   EPSG: 32616 
##   proj4string: &quot;+proj=utm +zone=16 +datum=WGS84 +units=m +no_defs&quot;</code></pre>
</div>
</div>
<div id="spatial-join" class="section level3 unnumbered">
<h3>Spatial join</h3>
<p>In essence, the spatial join operation finds the polygon to which each point belongs. Several points belong to the same polygon, so this is a many-to-one join. Instead of joining all the features of the polygon layer, we specify just <strong>area_num_1</strong>, which is the community area indicator. The command is <code>st_join</code> to which we pass the point layer as the first sf object, and the polygon layer as the second sf object (with only one column designated). We assign the result to the new spatial object <strong>comm.pts</strong>. We check the contents of the new object using a <code>head</code> command.</p>
<pre class="sourceCode r"><code class="sourceCode r">comm.pts &lt;-<span class="st"> </span><span class="kw">st_join</span>(vehicle.points,chicago.comm[<span class="st">&quot;area_num_1&quot;</span>])
<span class="kw">head</span>(comm.pts)</code></pre>
<pre><code>## Simple feature collection with 6 features and 2 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: 430118.3 ymin: 4622026 xmax: 441795.4 ymax: 4647560
## epsg (SRID):    32616
## proj4string:    +proj=utm +zone=16 +datum=WGS84 +units=m +no_defs
##   comm area_num_1                 geometry
## 1   23         23 POINT (440330.7 4638631)
## 2   56         56 POINT (436036.4 4627511)
## 3   70         70 POINT (441795.4 4622026)
## 4   76         76 POINT (430118.3 4647560)
## 5   16         16 POINT (440410.8 4645554)
## 6   19         19 POINT (434989.7 4641362)</code></pre>
<p>As we can see, the community area in <strong>comm</strong> matches the entry in <strong>area_num_1</strong>. However, there is one more issue to deal with. Upon closer examination, we find that the <strong>area_num_1</strong> variable is not numeric using the <code>is.numeric</code> check.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.numeric</span>(comm.pts<span class="op">$</span>area_num_<span class="dv">1</span>)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>So, we proceed to turn this variable into a numeric format using <code>as.integer</code> and
then do a quick check by means of <code>is.integer</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">comm.pts<span class="op">$</span>area_num_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">as.integer</span>(comm.pts<span class="op">$</span>area_num_<span class="dv">1</span>)
<span class="kw">is.integer</span>(comm.pts<span class="op">$</span>area_num_<span class="dv">1</span>)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>The same problem occurs in the <strong>chicago.comm</strong> data set, which can cause trouble later on when we will join it with other data. Therefore, we turn it into an integer
as well.</p>
<pre class="sourceCode r"><code class="sourceCode r">chicago.comm<span class="op">$</span>area_num_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">as.integer</span>(chicago.comm<span class="op">$</span>area_num_<span class="dv">1</span>)</code></pre>
</div>
<div id="counts-by-community-area" class="section level3 unnumbered">
<h3>Counts by community area</h3>
<p>We now need to count the number of points in each polygon. We proceed in two steps. First, we illustrate how we can move back from the simple features spatial points object to a simple data frame by stripping the geometry column. This is accomplished by setting <code>st_geometry</code> to <strong>NULL</strong>. We check the class of the new object to make sure it is no longer a simple feature.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_geometry</span>(comm.pts) &lt;-<span class="st"> </span><span class="ot">NULL</span>
<span class="kw">class</span>(comm.pts)</code></pre>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>We next take advantage of the <strong>tidyverse</strong> <code>count</code> function to create a new data frame with the identifier of the community area and the number of points contained in each community area.</p>
<pre class="sourceCode r"><code class="sourceCode r">veh.cnts &lt;-<span class="st"> </span>comm.pts <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(area_num_<span class="dv">1</span>)
<span class="kw">head</span>(veh.cnts)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   area_num_1     n
##        &lt;int&gt; &lt;int&gt;
## 1          1    67
## 2          2    89
## 3          3    21
## 4          4    32
## 5          5    18
## 6          6    19</code></pre>
<p>The new data frame has two fields: the original identifier <strong>area_num_1</strong> and the
count as <strong>n</strong>. We can change the variable names for the count to something more meaningful by means of the <strong>tidyverse</strong> <code>rename</code> command and turn it from <strong>n</strong> to <strong>AGG.COUNT</strong> (to use the same variable as in the GeoDa workbook). Similarly, we also shorten <strong>area_num_1</strong> to <strong>comm</strong>. Again, the new name is on the LHS of the equal sign and the old name on the RHS.</p>
<pre class="sourceCode r"><code class="sourceCode r">veh.cnts &lt;-<span class="st"> </span>veh.cnts <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rename</span>(<span class="dt">comm =</span> area_num_<span class="dv">1</span>, <span class="dt">AGG.COUNT =</span> n)
<span class="kw">head</span>(veh.cnts)</code></pre>
<pre><code>## # A tibble: 6 x 2
##    comm AGG.COUNT
##   &lt;int&gt;     &lt;int&gt;
## 1     1        67
## 2     2        89
## 3     3        21
## 4     4        32
## 5     5        18
## 6     6        19</code></pre>
</div>
<div id="mapping-the-vehicle-counts" class="section level3 unnumbered">
<h3>Mapping the vehicle counts</h3>
<p>At this point, we have a polygon layer with the community area boundaries and some identifiers (<strong>chicago.comm</strong>) and a data frame with the community identifier and the aggregate vehicle count (<strong>veh.cnts</strong>). In order to map the vehicle counts by community area, we need to <code>join</code> the two tables. We use the <code>left_join</code> command and use
<strong>area_num_1</strong> as the key for the first table (the community area boundaries),
and <strong>comm</strong> as the key for the second table (the vehicle counts). Since we assured
that both variables are now integers, the join will work (if one were a character and the other integer, there would be an error message). Note how in the command below, the two keys can have different
variable names (but they must have the same values), which is made explicit in the <code>by</code> statement.</p>
<pre class="sourceCode r"><code class="sourceCode r">chicago.comm &lt;-<span class="st"> </span><span class="kw">left_join</span>(chicago.comm,veh.cnts, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;area_num_1&quot;</span> =<span class="st"> &quot;comm&quot;</span>))</code></pre>
<p>We can double check that the vehicle counts were added using the <code>head</code> command.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(chicago.comm)</code></pre>
<pre><code>## Simple feature collection with 6 features and 10 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 441440.4 ymin: 4627153 xmax: 451817.1 ymax: 4648971
## epsg (SRID):    32616
## proj4string:    +proj=utm +zone=16 +datum=WGS84 +units=m +no_defs
## # A tibble: 6 x 11
##   community area  shape_area perimeter area_num_1 area_numbe comarea_id
##   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;     
## 1 DOUGLAS   0     46004621.… 0                 35 35         0         
## 2 OAKLAND   0     16913961.… 0                 36 36         0         
## 3 FULLER P… 0     19916704.… 0                 37 37         0         
## 4 GRAND BO… 0     48492503.… 0                 38 38         0         
## 5 KENWOOD   0     29071741.… 0                 39 39         0         
## 6 LINCOLN … 0     71352328.… 0                  4 4          0         
## # … with 4 more variables: comarea &lt;chr&gt;, shape_len &lt;chr&gt;,
## #   geometry &lt;MULTIPOLYGON [m]&gt;, AGG.COUNT &lt;int&gt;</code></pre>
<div id="basic-choropleth-map" class="section level4 unnumbered">
<h4>Basic choropleth map</h4>
<p>As we saw earlier, we can construct rudimentary maps using the <code>plot</code> command
in <strong>sf</strong>, but for further control, we will use the <strong>tmap</strong> package. This uses
a logic similar to Wilkinson’s <em>grammar of graphics</em>, which is also the basis for the
structure of the plot commands in the <strong>ggplot</strong> package.</p>
<p>We leave a detailed treatment of <strong>tmap</strong> for a future lab and just use the basic
defaults in this example. The commands are layered and always start by specifying a
layer using the <code>tm_shape</code> command. In our example, this is <strong>chicago.comm</strong>.
Next (after the plus sign) follow one of more drawing commands that cover a wide
range of geographic shapes. Here, we will just use <code>tm_polygons</code> and specify
<strong>AGG.COUNT</strong> as the variable to determine the classification. We leave everything to the default and obtain a map that illustrates the spatial distribution of the
abandoned vehicle counts by community area.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tm_shape</span>(chicago.comm) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_polygons</span>(<span class="st">&quot;AGG.COUNT&quot;</span>)</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>However, this map can be highly misleading since it pertains to a so-called
<em>spatially extensive</em> variable, such as a count. Even if every area had the
same risk of having abandoned vehicles, larger community areas would have
higher counts. In other words, since the count is directly related to the
size of the area, it does not provide a proper indication of the risk.</p>
<p>Instead, we should map a <em>spatially intensive</em> variable, which is corrected
for the size of the unit. For example, this can be achieved by expressing the
variable as a density (counts per area), or as some other ratio, such as
the counts per capita. In order to calculate this ratio, we first need to
obtain the population for each community area.</p>
</div>
</div>
</div>
<div id="community-area-population-data" class="section level2 unnumbered">
<h2>Community Area Population Data</h2>
<p>The Chicago Community Area 2010 population is contained in a pdf file, available
from the <a href="http://www.cityofchicago.org/city/en/depts/dcd/supp_info/community_area_2000and2010censuspopulationcomparisons.html">City of Chicago web site</a>.</p>
<p>This link is to a pdf file that contains a table with the neighborhood ID, the neighborhood name, the populations
for 2010 and 2000, the difference between the two years and the percentage difference. The full path to the pdf file is
<a href="https://www.cityofchicago.org/content/dam/city/depts/zlup/Zoning_Main_Page/Publications/Census_2010_Community_Area_Profiles/Census_2010_and_2000_CA_Populations.pdf" class="uri">https://www.cityofchicago.org/content/dam/city/depts/zlup/Zoning_Main_Page/Publications/Census_2010_Community_Area_Profiles/Census_2010_and_2000_CA_Populations.pdf</a></p>
<div id="extracting-a-pdf-file" class="section level3 unnumbered">
<h3>Extracting a pdf file</h3>
<p>A pdf file is difficult to handle as a source of data, since it doesn’t contain tags like an html file.
We will use the <strong>pdftools</strong> package that allows us to turn the contents of a pdf file into a list of long character strings.</p>
<p>The resulting data structure is somewhat complex and not necessarily easy to parse. However, in our case, the table has such a simple structure that we can extract the population values by doing some sleuthing on which columns
contain those values. This will illustrate the power of the various parsing and text extraction functions available in R.</p>
<p>We use the <code>pdf_text</code> function from <strong>pdftools</strong> to turn the pdf file into a list of character strings, one
for each page. We specify the URL of the file as the input source.</p>
<pre class="sourceCode r"><code class="sourceCode r">pdf.file &lt;-<span class="st"> &quot;https://www.cityofchicago.org/content/dam/city/depts/zlup/Zoning_Main_Page/Publications/Census_2010_Community_Area_Profiles/Census_2010_and_2000_CA_Populations.pdf&quot;</span>
pop.dat &lt;-<span class="st"> </span><span class="kw">pdf_text</span>(pdf.file)
<span class="kw">class</span>(pop.dat)</code></pre>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>We check the length of the data object using the <code>length</code> command and find that indeed it has only two elements (one for each page).</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(pop.dat)</code></pre>
<pre><code>## [1] 2</code></pre>
</div>
<div id="parsing-the-pdf-file" class="section level3 unnumbered">
<h3>Parsing the pdf file</h3>
<p>The <strong>pop.dat</strong> object has two entries, one for each page. Each entry is a single string. So, when you check the length of each item, it may be surprising that its <strong>length</strong> is only 1. That is because the underlying structure is unknown, it is simply a collection of characters contained in the string. For example, the first element, <strong>pop.dat[[1]]</strong>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(pop.dat[[<span class="dv">1</span>]])</code></pre>
<pre><code>## [1] 1</code></pre>
<p>We will parse this file by first turning each element into a separate list and then extracting the parts we are interested in.</p>
<p>First, to illustrate in detail what is going on, we will go through each step one by one, but then,
in order to reach some level of efficiency, we turn it
into a loop over the two elements, <code>for (i in 1:2)</code>.</p>
<p>We start by initializing a vector (<strong>nnlist</strong>) with an empty character, and confirm that it is indeed initialized.</p>
<pre class="sourceCode r"><code class="sourceCode r">nnlist &lt;-<span class="st"> &quot;&quot;</span>
nnlist</code></pre>
<pre><code>## [1] &quot;&quot;</code></pre>
<p>Next, we create a list of strings, one for each line in the table, by using the
<code>strsplit</code> operation. This splits
the long string into a list of one string for each line, by using the return character <strong>\n</strong> as the separator (the value for the <code>split</code> argument).</p>
<p>The resulting list, <strong>ppage</strong>, contains a list of 44 elements, matching the contents of the first page of the pdf file.</p>
<pre class="sourceCode r"><code class="sourceCode r">ppage &lt;-<span class="st"> </span><span class="kw">strsplit</span>(pop.dat[[<span class="dv">1</span>]],<span class="dt">split=</span><span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)
ppage[[<span class="dv">1</span>]]</code></pre>
<pre><code>##  [1] &quot;                          CITY OF CHICAGO&quot;                               
##  [2] &quot;                        CENSUS 2010 AND 2000&quot;                            
##  [3] &quot;                                             Population&quot;                 
##  [4] &quot;Num      Community Area     2010        2,000      Difference Percentage&quot;
##  [5] &quot; 1  Rogers Park              54,991     63,484        -8,493    -13.4%&quot;  
##  [6] &quot; 2  West Ridge               71,942     73,199        -1,257     -1.7%&quot;  
##  [7] &quot; 3  Uptown                   56,362     63,551        -7,189    -11.3%&quot;  
##  [8] &quot; 4  Lincoln Square           39,493     44,574        -5,081    -11.4%&quot;  
##  [9] &quot; 5  North Center             31,867     31,895          -28      -0.1%&quot;  
## [10] &quot; 6  Lake View                94,368     94,817         -449      -0.5%&quot;  
## [11] &quot; 7  Lincoln Park             64,116     64,320         -204      -0.3%&quot;  
## [12] &quot; 8  Near North Side          80,484     72,811        7,673      10.5%&quot;  
## [13] &quot; 9  Edison Park              11,187     11,259          -72      -0.6%&quot;  
## [14] &quot; 10 Norwood Park             37,023     37,669         -646      -1.7%&quot;  
## [15] &quot; 11 Jefferson Park           25,448     25,859         -411      -1.6%&quot;  
## [16] &quot; 12 Forest Glen              18,508     18,165         343       1.9%&quot;   
## [17] &quot; 13 North Park               17,931     18,514         -583      -3.1%&quot;  
## [18] &quot; 14 Albany Park              51,542     57,655        -6,113    -10.6%&quot;  
## [19] &quot; 15 Portage Park             64,124     65,340        -1,216     -1.9%&quot;  
## [20] &quot; 16 Irving Park              53,359     58,643        -5,284     -9.0%&quot;  
## [21] &quot; 17 Dunning                  41,932     42,164         -232      -0.6%&quot;  
## [22] &quot; 18 Montclare                13,426     12,646         780       6.2%&quot;   
## [23] &quot; 19 Belmont Cragin           78,743     78,144         599       0.8%&quot;   
## [24] &quot; 20 Hermosa                  25,010     26,908        -1,898     -7.1%&quot;  
## [25] &quot; 21 Avondale                 39,262     43,083        -3,821     -8.9%&quot;  
## [26] &quot; 22 Logan Square             73,595     82,715        -9,120    -11.0%&quot;  
## [27] &quot; 23 Humboldt Park            56,323     65,836        -9,513    -14.4%&quot;  
## [28] &quot; 24 West Town                81,432     87,435        -6,003     -6.9%&quot;  
## [29] &quot; 25 Austin                   98,514    117,527       -19,013    -16.2%&quot;  
## [30] &quot; 26 West Garfield Park       18,001     23,019        -5,018    -21.8%&quot;  
## [31] &quot; 27 East Garfield Park       20,567     20,881         -314      -1.5%&quot;  
## [32] &quot; 28 Near West Side           54,881     46,419        8,462      18.2%&quot;  
## [33] &quot; 29 North Lawndale           35,912     41,768        -5,856    -14.0%&quot;  
## [34] &quot; 30 South Lawndale           79,288     91,071       -11,783    -12.9%&quot;  
## [35] &quot; 31 Lower West Side          35,769     44,031        -8,262    -18.8%&quot;  
## [36] &quot; 32 Loop                     29,283     16,388        12,895     78.7%&quot;  
## [37] &quot; 33 Near South Side          21,390     9,509         11,881    124.9%&quot;  
## [38] &quot; 34 Armour Square            13,391     12,032        1,359      11.3%&quot;  
## [39] &quot; 35 Douglas                  18,238     26,470        -8,232    -31.1%&quot;  
## [40] &quot; 36 Oakland                    5,918    6,110          -192      -3.1%&quot;  
## [41] &quot; 37 Fuller Park                2,876    3,420          -544     -15.9%&quot;  
## [42] &quot; 38 Grand Boulevard          21,929     28,006        -6,077    -21.7%&quot;  
## [43] &quot; 39 Kenwood                  17,841     18,363         -522      -2.8%&quot;  
## [44] &quot; 40 Washington Park          11,717     14,146        -2,429    -17.2%&quot;</code></pre>
<p>Each element is one long string, corresponding to a table row. We remove the first four lines (using the - operation on the list elements 1 through 4). These first rows appear on each page, so we are safe to repeat this procedure for the second page (string) as well.</p>
<pre class="sourceCode r"><code class="sourceCode r">nni &lt;-<span class="st"> </span>ppage[[<span class="dv">1</span>]]
nni &lt;-<span class="st"> </span>nni[<span class="op">-</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)]
nni</code></pre>
<pre><code>##  [1] &quot; 1  Rogers Park              54,991     63,484        -8,493    -13.4%&quot;
##  [2] &quot; 2  West Ridge               71,942     73,199        -1,257     -1.7%&quot;
##  [3] &quot; 3  Uptown                   56,362     63,551        -7,189    -11.3%&quot;
##  [4] &quot; 4  Lincoln Square           39,493     44,574        -5,081    -11.4%&quot;
##  [5] &quot; 5  North Center             31,867     31,895          -28      -0.1%&quot;
##  [6] &quot; 6  Lake View                94,368     94,817         -449      -0.5%&quot;
##  [7] &quot; 7  Lincoln Park             64,116     64,320         -204      -0.3%&quot;
##  [8] &quot; 8  Near North Side          80,484     72,811        7,673      10.5%&quot;
##  [9] &quot; 9  Edison Park              11,187     11,259          -72      -0.6%&quot;
## [10] &quot; 10 Norwood Park             37,023     37,669         -646      -1.7%&quot;
## [11] &quot; 11 Jefferson Park           25,448     25,859         -411      -1.6%&quot;
## [12] &quot; 12 Forest Glen              18,508     18,165         343       1.9%&quot; 
## [13] &quot; 13 North Park               17,931     18,514         -583      -3.1%&quot;
## [14] &quot; 14 Albany Park              51,542     57,655        -6,113    -10.6%&quot;
## [15] &quot; 15 Portage Park             64,124     65,340        -1,216     -1.9%&quot;
## [16] &quot; 16 Irving Park              53,359     58,643        -5,284     -9.0%&quot;
## [17] &quot; 17 Dunning                  41,932     42,164         -232      -0.6%&quot;
## [18] &quot; 18 Montclare                13,426     12,646         780       6.2%&quot; 
## [19] &quot; 19 Belmont Cragin           78,743     78,144         599       0.8%&quot; 
## [20] &quot; 20 Hermosa                  25,010     26,908        -1,898     -7.1%&quot;
## [21] &quot; 21 Avondale                 39,262     43,083        -3,821     -8.9%&quot;
## [22] &quot; 22 Logan Square             73,595     82,715        -9,120    -11.0%&quot;
## [23] &quot; 23 Humboldt Park            56,323     65,836        -9,513    -14.4%&quot;
## [24] &quot; 24 West Town                81,432     87,435        -6,003     -6.9%&quot;
## [25] &quot; 25 Austin                   98,514    117,527       -19,013    -16.2%&quot;
## [26] &quot; 26 West Garfield Park       18,001     23,019        -5,018    -21.8%&quot;
## [27] &quot; 27 East Garfield Park       20,567     20,881         -314      -1.5%&quot;
## [28] &quot; 28 Near West Side           54,881     46,419        8,462      18.2%&quot;
## [29] &quot; 29 North Lawndale           35,912     41,768        -5,856    -14.0%&quot;
## [30] &quot; 30 South Lawndale           79,288     91,071       -11,783    -12.9%&quot;
## [31] &quot; 31 Lower West Side          35,769     44,031        -8,262    -18.8%&quot;
## [32] &quot; 32 Loop                     29,283     16,388        12,895     78.7%&quot;
## [33] &quot; 33 Near South Side          21,390     9,509         11,881    124.9%&quot;
## [34] &quot; 34 Armour Square            13,391     12,032        1,359      11.3%&quot;
## [35] &quot; 35 Douglas                  18,238     26,470        -8,232    -31.1%&quot;
## [36] &quot; 36 Oakland                    5,918    6,110          -192      -3.1%&quot;
## [37] &quot; 37 Fuller Park                2,876    3,420          -544     -15.9%&quot;
## [38] &quot; 38 Grand Boulevard          21,929     28,006        -6,077    -21.7%&quot;
## [39] &quot; 39 Kenwood                  17,841     18,363         -522      -2.8%&quot;
## [40] &quot; 40 Washington Park          11,717     14,146        -2,429    -17.2%&quot;</code></pre>
<p>To streamline the resulting data structure for further operations, we turn it into a simple
vector by means of <code>unlist</code>. This then allows us to concatenate the result to the current <strong>nnlist</strong> vector (initially, this contains just a single element
with an empty character, after the first step it contains the empty character and the first page).</p>
<pre class="sourceCode r"><code class="sourceCode r">nnu &lt;-<span class="st"> </span><span class="kw">unlist</span>(nni)
nnlist &lt;-<span class="st"> </span><span class="kw">c</span>(nnlist,nnu)
nnlist</code></pre>
<pre><code>##  [1] &quot;&quot;                                                                      
##  [2] &quot; 1  Rogers Park              54,991     63,484        -8,493    -13.4%&quot;
##  [3] &quot; 2  West Ridge               71,942     73,199        -1,257     -1.7%&quot;
##  [4] &quot; 3  Uptown                   56,362     63,551        -7,189    -11.3%&quot;
##  [5] &quot; 4  Lincoln Square           39,493     44,574        -5,081    -11.4%&quot;
##  [6] &quot; 5  North Center             31,867     31,895          -28      -0.1%&quot;
##  [7] &quot; 6  Lake View                94,368     94,817         -449      -0.5%&quot;
##  [8] &quot; 7  Lincoln Park             64,116     64,320         -204      -0.3%&quot;
##  [9] &quot; 8  Near North Side          80,484     72,811        7,673      10.5%&quot;
## [10] &quot; 9  Edison Park              11,187     11,259          -72      -0.6%&quot;
## [11] &quot; 10 Norwood Park             37,023     37,669         -646      -1.7%&quot;
## [12] &quot; 11 Jefferson Park           25,448     25,859         -411      -1.6%&quot;
## [13] &quot; 12 Forest Glen              18,508     18,165         343       1.9%&quot; 
## [14] &quot; 13 North Park               17,931     18,514         -583      -3.1%&quot;
## [15] &quot; 14 Albany Park              51,542     57,655        -6,113    -10.6%&quot;
## [16] &quot; 15 Portage Park             64,124     65,340        -1,216     -1.9%&quot;
## [17] &quot; 16 Irving Park              53,359     58,643        -5,284     -9.0%&quot;
## [18] &quot; 17 Dunning                  41,932     42,164         -232      -0.6%&quot;
## [19] &quot; 18 Montclare                13,426     12,646         780       6.2%&quot; 
## [20] &quot; 19 Belmont Cragin           78,743     78,144         599       0.8%&quot; 
## [21] &quot; 20 Hermosa                  25,010     26,908        -1,898     -7.1%&quot;
## [22] &quot; 21 Avondale                 39,262     43,083        -3,821     -8.9%&quot;
## [23] &quot; 22 Logan Square             73,595     82,715        -9,120    -11.0%&quot;
## [24] &quot; 23 Humboldt Park            56,323     65,836        -9,513    -14.4%&quot;
## [25] &quot; 24 West Town                81,432     87,435        -6,003     -6.9%&quot;
## [26] &quot; 25 Austin                   98,514    117,527       -19,013    -16.2%&quot;
## [27] &quot; 26 West Garfield Park       18,001     23,019        -5,018    -21.8%&quot;
## [28] &quot; 27 East Garfield Park       20,567     20,881         -314      -1.5%&quot;
## [29] &quot; 28 Near West Side           54,881     46,419        8,462      18.2%&quot;
## [30] &quot; 29 North Lawndale           35,912     41,768        -5,856    -14.0%&quot;
## [31] &quot; 30 South Lawndale           79,288     91,071       -11,783    -12.9%&quot;
## [32] &quot; 31 Lower West Side          35,769     44,031        -8,262    -18.8%&quot;
## [33] &quot; 32 Loop                     29,283     16,388        12,895     78.7%&quot;
## [34] &quot; 33 Near South Side          21,390     9,509         11,881    124.9%&quot;
## [35] &quot; 34 Armour Square            13,391     12,032        1,359      11.3%&quot;
## [36] &quot; 35 Douglas                  18,238     26,470        -8,232    -31.1%&quot;
## [37] &quot; 36 Oakland                    5,918    6,110          -192      -3.1%&quot;
## [38] &quot; 37 Fuller Park                2,876    3,420          -544     -15.9%&quot;
## [39] &quot; 38 Grand Boulevard          21,929     28,006        -6,077    -21.7%&quot;
## [40] &quot; 39 Kenwood                  17,841     18,363         -522      -2.8%&quot;
## [41] &quot; 40 Washington Park          11,717     14,146        -2,429    -17.2%&quot;</code></pre>
<p>We now repeat this operation for <strong>pop.dat[[2]]</strong>. More efficiently, we implement it as a loop, replacing <strong>i</strong> in turn by 1 and 2. This yields:</p>
<pre class="sourceCode r"><code class="sourceCode r">nnlist &lt;-<span class="st"> &quot;&quot;</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) {
  ppage &lt;-<span class="st"> </span><span class="kw">strsplit</span>(pop.dat[[i]],<span class="dt">split=</span><span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)
  nni &lt;-<span class="st"> </span>ppage[[<span class="dv">1</span>]]
  nni &lt;-<span class="st"> </span>nni[<span class="op">-</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)]
  nnu &lt;-<span class="st"> </span><span class="kw">unlist</span>(nni)
  nnlist &lt;-<span class="st"> </span><span class="kw">c</span>(nnlist,nnu)
}</code></pre>
<p>At the end of the loop, we check the contents of the vector <strong>nnlist</strong>.</p>
<pre class="sourceCode r"><code class="sourceCode r">nnlist</code></pre>
<pre><code>##  [1] &quot;&quot;                                                                          
##  [2] &quot; 1  Rogers Park              54,991     63,484        -8,493    -13.4%&quot;    
##  [3] &quot; 2  West Ridge               71,942     73,199        -1,257     -1.7%&quot;    
##  [4] &quot; 3  Uptown                   56,362     63,551        -7,189    -11.3%&quot;    
##  [5] &quot; 4  Lincoln Square           39,493     44,574        -5,081    -11.4%&quot;    
##  [6] &quot; 5  North Center             31,867     31,895          -28      -0.1%&quot;    
##  [7] &quot; 6  Lake View                94,368     94,817         -449      -0.5%&quot;    
##  [8] &quot; 7  Lincoln Park             64,116     64,320         -204      -0.3%&quot;    
##  [9] &quot; 8  Near North Side          80,484     72,811        7,673      10.5%&quot;    
## [10] &quot; 9  Edison Park              11,187     11,259          -72      -0.6%&quot;    
## [11] &quot; 10 Norwood Park             37,023     37,669         -646      -1.7%&quot;    
## [12] &quot; 11 Jefferson Park           25,448     25,859         -411      -1.6%&quot;    
## [13] &quot; 12 Forest Glen              18,508     18,165         343       1.9%&quot;     
## [14] &quot; 13 North Park               17,931     18,514         -583      -3.1%&quot;    
## [15] &quot; 14 Albany Park              51,542     57,655        -6,113    -10.6%&quot;    
## [16] &quot; 15 Portage Park             64,124     65,340        -1,216     -1.9%&quot;    
## [17] &quot; 16 Irving Park              53,359     58,643        -5,284     -9.0%&quot;    
## [18] &quot; 17 Dunning                  41,932     42,164         -232      -0.6%&quot;    
## [19] &quot; 18 Montclare                13,426     12,646         780       6.2%&quot;     
## [20] &quot; 19 Belmont Cragin           78,743     78,144         599       0.8%&quot;     
## [21] &quot; 20 Hermosa                  25,010     26,908        -1,898     -7.1%&quot;    
## [22] &quot; 21 Avondale                 39,262     43,083        -3,821     -8.9%&quot;    
## [23] &quot; 22 Logan Square             73,595     82,715        -9,120    -11.0%&quot;    
## [24] &quot; 23 Humboldt Park            56,323     65,836        -9,513    -14.4%&quot;    
## [25] &quot; 24 West Town                81,432     87,435        -6,003     -6.9%&quot;    
## [26] &quot; 25 Austin                   98,514    117,527       -19,013    -16.2%&quot;    
## [27] &quot; 26 West Garfield Park       18,001     23,019        -5,018    -21.8%&quot;    
## [28] &quot; 27 East Garfield Park       20,567     20,881         -314      -1.5%&quot;    
## [29] &quot; 28 Near West Side           54,881     46,419        8,462      18.2%&quot;    
## [30] &quot; 29 North Lawndale           35,912     41,768        -5,856    -14.0%&quot;    
## [31] &quot; 30 South Lawndale           79,288     91,071       -11,783    -12.9%&quot;    
## [32] &quot; 31 Lower West Side          35,769     44,031        -8,262    -18.8%&quot;    
## [33] &quot; 32 Loop                     29,283     16,388        12,895     78.7%&quot;    
## [34] &quot; 33 Near South Side          21,390     9,509         11,881    124.9%&quot;    
## [35] &quot; 34 Armour Square            13,391     12,032        1,359      11.3%&quot;    
## [36] &quot; 35 Douglas                  18,238     26,470        -8,232    -31.1%&quot;    
## [37] &quot; 36 Oakland                    5,918    6,110          -192      -3.1%&quot;    
## [38] &quot; 37 Fuller Park                2,876    3,420          -544     -15.9%&quot;    
## [39] &quot; 38 Grand Boulevard          21,929     28,006        -6,077    -21.7%&quot;    
## [40] &quot; 39 Kenwood                  17,841     18,363         -522      -2.8%&quot;    
## [41] &quot; 40 Washington Park          11,717     14,146        -2,429    -17.2%&quot;    
## [42] &quot; 41 Hyde Park                    25,681     29,920         -4,239   -14.2%&quot;
## [43] &quot; 42 Woodlawn                     25,983     27,086         -1,103    -4.1%&quot;
## [44] &quot; 43 South Shore                  49,767     61,556        -11,789   -19.2%&quot;
## [45] &quot; 44 Chatham                      31,028     37,275         -6,247   -16.8%&quot;
## [46] &quot; 45 Avalon Park                  10,185     11,147          -962     -8.6%&quot;
## [47] &quot; 46 South Chicago                31,198     38,596         -7,398   -19.2%&quot;
## [48] &quot; 47 Burnside                      2,916     3,294           -378    -11.5%&quot;
## [49] &quot; 48 Calumet Heights              13,812     15,974         -2,162   -13.5%&quot;
## [50] &quot; 49 Roseland                     44,619     52,723         -8,104   -15.4%&quot;
## [51] &quot; 50 Pullman                       7,325     8,921          -1,596   -17.9%&quot;
## [52] &quot; 51 South Deering                15,109     16,990         -1,881   -11.1%&quot;
## [53] &quot; 52 East Side                    23,042     23,653          -611     -2.6%&quot;
## [54] &quot; 53 West Pullman                 29,651     36,649         -6,998   -19.1%&quot;
## [55] &quot; 54 Riverdale                     6,482     9,809          -3,327   -33.9%&quot;
## [56] &quot; 55 Hegewisch                     9,426     9,781           -355     -3.6%&quot;
## [57] &quot; 56 Garfield Ridge               34,513     36,101         -1,588    -4.4%&quot;
## [58] &quot; 57 Archer Heights               13,393     12,644          749      5.9%&quot; 
## [59] &quot; 58 Brighton Park                45,368     44,912          456      1.0%&quot; 
## [60] &quot; 59 McKinley Park                15,612     15,962          -350     -2.2%&quot;
## [61] &quot; 60 Bridgeport                   31,977     33,694         -1,717    -5.1%&quot;
## [62] &quot; 61 New City                     44,377     51,721         -7,344   -14.2%&quot;
## [63] &quot; 62 West Elsdon                  18,109     15,921         2,188    13.7%&quot; 
## [64] &quot; 63 Gage Park                    39,894     39,193          701      1.8%&quot; 
## [65] &quot; 64 Clearing                     23,139     22,331          808      3.6%&quot; 
## [66] &quot; 65 West Lawn                    33,355     29,235         4,120    14.1%&quot; 
## [67] &quot; 66 Chicago Lawn                 55,628     61,412         -5,784    -9.4%&quot;
## [68] &quot; 67 West Englewood               35,505     45,282         -9,777   -21.6%&quot;
## [69] &quot; 68 Englewood                    30,654     40,222         -9,568   -23.8%&quot;
## [70] &quot; 69 Greater Grand Crossing       32,602     38,619         -6,017   -15.6%&quot;
## [71] &quot; 70 Ashburn                      41,081     39,584         1,497     3.8%&quot; 
## [72] &quot; 71 Auburn Gresham               48,743     55,928         -7,185   -12.8%&quot;
## [73] &quot; 72 Beverly                      20,034     21,992         -1,958    -8.9%&quot;
## [74] &quot; 73 Washington Heights           26,493     29,843         -3,350   -11.2%&quot;
## [75] &quot; 74 Mount Greenwood              19,093     18,820          273      1.5%&quot; 
## [76] &quot; 75 Morgan Park                  22,544     25,226         -2,682   -10.6%&quot;
## [77] &quot; 76 O&#39;Hare                       12,756     11,956          800      6.7%&quot; 
## [78] &quot; 77 Edgewater                    56,521     62,198         -5,677    -9.1%&quot;
## [79] &quot;    Total                     2,695,598   2,896,016      -200,418    -6.9%&quot;</code></pre>
<p>This is now a vector of 79 elements, each of which is a string. To clean things up, strip the first (empty) element, and the last
element, which is nothing but the totals. We thus extract the elements from <strong>2</strong> to <strong>length - 1</strong>.</p>
<pre class="sourceCode r"><code class="sourceCode r">nnlist &lt;-<span class="st"> </span>nnlist[<span class="dv">2</span><span class="op">:</span>(<span class="kw">length</span>(nnlist)<span class="op">-</span><span class="dv">1</span>)]</code></pre>
</div>
<div id="extracting-the-population-values" class="section level3">
<h3><span class="header-section-number">1.0.1</span> Extracting the population values</h3>
<p>We first initialize a vector of zeros to hold the population values. It is the preferred approach to
initialize a vector first if one knows its size, rather than having it grow by appending rows or columns.
We use the <code>vector</code> command and specify the <code>mode=&quot;numeric&quot;</code> and give the <code>length</code> as the
length of the list.</p>
<pre class="sourceCode r"><code class="sourceCode r">nnpop &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">mode=</span><span class="st">&quot;numeric&quot;</span>,<span class="dt">length=</span><span class="kw">length</span>(nnlist))</code></pre>
<p>We again will use a loop to process each element of the list (each line of the table) one by one.
We use the <code>substr</code> command to extract the characters between position 27 and 39 (these values
were determined after taking a careful look at the structure of the table). However, there is still a problem, since
the population values contain commas. We now do two things in one line of code. First, we use <code>gsub</code>
to substitute the comma character by an empty <strong>&quot;&quot;</strong>. We turn the result into a numeric value by
means of <code>as.numeric</code>. We then assign this number to position <strong>i</strong> of the vector. The resulting
vector <strong>nnpop</strong> contains the population for each of the community areas.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> (<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(nnlist))) {
     popchar &lt;-<span class="st"> </span><span class="kw">substr</span>(nnlist[i],<span class="dt">start=</span><span class="dv">27</span>,<span class="dt">stop=</span><span class="dv">39</span>)
     popval &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">gsub</span>(<span class="st">&quot;,&quot;</span>,<span class="st">&quot;&quot;</span>,popchar))
     nnpop[i] &lt;-<span class="st"> </span>popval
}
nnpop</code></pre>
<pre><code>##  [1] 54991 71942 56362 39493 31867 94368 64116 80484 11187 37023 25448
## [12] 18508 17931 51542 64124 53359 41932 13426 78743 25010 39262 73595
## [23] 56323 81432 98514 18001 20567 54881 35912 79288 35769 29283 21390
## [34] 13391 18238  5918  2876 21929 17841 11717 25681 25983 49767 31028
## [45] 10185 31198  2916 13812 44619  7325 15109 23042 29651  6482  9426
## [56] 34513 13393 45368 15612 31977 44377 18109 39894 23139 33355 55628
## [67] 35505 30654 32602 41081 48743 20034 26493 19093 22544 12756 56521</code></pre>
</div>
<div id="creating-a-data-frame-with-population-values" class="section level3 unnumbered">
<h3>Creating a data frame with population values</h3>
<p>As a final step in the process of collecting the community area
population information, we combine the vector with the population
counts and a vector with community ID information into a data frame.</p>
<p>Since the community
area indicators are simple sequence numbers, we create such a vector to serve as the ID,
again using the length of the vector to determine the extent.</p>
<pre class="sourceCode r"><code class="sourceCode r">nnid &lt;-<span class="st"> </span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(nnlist))
nnid</code></pre>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
## [24] 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
## [47] 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69
## [70] 70 71 72 73 74 75 76 77</code></pre>
<p>We turn the vectors <strong>nnid</strong> and <strong>nnpop</strong> into a data frame using the <code>data.frame</code> command.
Since the variable names assigned automatically are not that informative, we next force them to
<strong>NID</strong> and <strong>POP2010</strong> using the <code>names</code> command. Also, as we did before, we make sure the ID variable
is an integer (for merging in GeoDa) by means of <code>as.integer</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">neighpop &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">as.integer</span>(nnid),nnpop)
<span class="kw">names</span>(neighpop) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;NID&quot;</span>,<span class="st">&quot;POP2010&quot;</span>)
<span class="kw">head</span>(neighpop)</code></pre>
<pre><code>##   NID POP2010
## 1   1   54991
## 2   2   71942
## 3   3   56362
## 4   4   39493
## 5   5   31867
## 6   6   94368</code></pre>
</div>
</div>
<div id="mapping-community-area-abandoned-vehicles-per-capita" class="section level2 unnumbered">
<h2>Mapping Community Area Abandoned Vehicles Per Capita</h2>
<div id="computing-abandoned-vehicles-per-capita" class="section level3 unnumbered">
<h3>Computing abandoned vehicles per capita</h3>
<p>Before proceeding further, we <code>left_join</code> the community population data to the community
area layer, in the same way as we did for the vehicle counts.</p>
<pre class="sourceCode r"><code class="sourceCode r">chicago.comm &lt;-<span class="st"> </span><span class="kw">left_join</span>(chicago.comm,neighpop, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;area_num_1&quot;</span> =<span class="st"> &quot;NID&quot;</span>))
<span class="kw">head</span>(chicago.comm)</code></pre>
<pre><code>## Simple feature collection with 6 features and 11 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 441440.4 ymin: 4627153 xmax: 451817.1 ymax: 4648971
## epsg (SRID):    32616
## proj4string:    +proj=utm +zone=16 +datum=WGS84 +units=m +no_defs
## # A tibble: 6 x 12
##   community area  shape_area perimeter area_num_1 area_numbe comarea_id
##   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;     
## 1 DOUGLAS   0     46004621.… 0                 35 35         0         
## 2 OAKLAND   0     16913961.… 0                 36 36         0         
## 3 FULLER P… 0     19916704.… 0                 37 37         0         
## 4 GRAND BO… 0     48492503.… 0                 38 38         0         
## 5 KENWOOD   0     29071741.… 0                 39 39         0         
## 6 LINCOLN … 0     71352328.… 0                  4 4          0         
## # … with 5 more variables: comarea &lt;chr&gt;, shape_len &lt;chr&gt;,
## #   geometry &lt;MULTIPOLYGON [m]&gt;, AGG.COUNT &lt;int&gt;, POP2010 &lt;dbl&gt;</code></pre>
<p>We will now create a new variable using the <strong>tidyverse</strong> <code>mutate</code> command as the ratio
of vehicle counts per 1000 population.</p>
<pre class="sourceCode r"><code class="sourceCode r">chicago.comm &lt;-<span class="st"> </span>chicago.comm <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">vehpcap =</span> (AGG.COUNT <span class="op">/</span><span class="st"> </span>POP2010) <span class="op">*</span><span class="st"> </span><span class="dv">1000</span>) 
<span class="kw">head</span>(chicago.comm)</code></pre>
<pre><code>## Simple feature collection with 6 features and 12 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 441440.4 ymin: 4627153 xmax: 451817.1 ymax: 4648971
## epsg (SRID):    32616
## proj4string:    +proj=utm +zone=16 +datum=WGS84 +units=m +no_defs
## # A tibble: 6 x 13
##   community area  shape_area perimeter area_num_1 area_numbe comarea_id
##   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;     
## 1 DOUGLAS   0     46004621.… 0                 35 35         0         
## 2 OAKLAND   0     16913961.… 0                 36 36         0         
## 3 FULLER P… 0     19916704.… 0                 37 37         0         
## 4 GRAND BO… 0     48492503.… 0                 38 38         0         
## 5 KENWOOD   0     29071741.… 0                 39 39         0         
## 6 LINCOLN … 0     71352328.… 0                  4 4          0         
## # … with 6 more variables: comarea &lt;chr&gt;, shape_len &lt;chr&gt;,
## #   geometry &lt;MULTIPOLYGON [m]&gt;, AGG.COUNT &lt;int&gt;, POP2010 &lt;dbl&gt;,
## #   vehpcap &lt;dbl&gt;</code></pre>
</div>
<div id="final-choropleth-map" class="section level3 unnumbered">
<h3>Final choropleth map</h3>
<p>For our final choropleth, we use the same procedure as for the vehicle counts,
but take <strong>vehpcap</strong> as the variable instead.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tm_shape</span>(chicago.comm) <span class="op">+</span>
<span class="st">  </span><span class="kw">tm_polygons</span>(<span class="st">&quot;vehpcap&quot;</span>)</code></pre>
<p><img src="handsonspatialdata_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>When compared to the total counts, we see quite a different spatial distribution.
In particular, the locations of the highest ratios are quite different from those of the highest counts. As a rule, one should <em>never</em> create a choropleth map of a spatially extensive variable, unless the size of the areal units is somehow controlled for
(e.g., equal area grid cells, or equal population zones).</p>
<div id="optional---save-the-community-area-file-as-a-shape-file" class="section level4">
<h4><span class="header-section-number">1.0.1.1</span> Optional - save the community area file as a shape file</h4>
<p>Finally, we can write the community area layer to the working directory. Note that, so far, all operations have been carried out in memory, and when you close the program, everything will be lost (unless you save your workspace).</p>
<p>We can write the community area to a shape file (actually, four files contained
in a directory) by means of the <strong>sf</strong> command <code>st_write</code>. This command has many
options, but we just use the minimal ones. The <strong>chicago.comm</strong> object will
be written to a set of files in the directory <strong>chicago_vehicles</strong> using the
<strong>ESRI Shapefile</strong> format. Note that if the directory already exists, it should be
deleted or renamed first, since <code>st_write</code> only creates a new directory. Otherwise,
there will be an error message.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_write</span>(chicago.comm,<span class="st">&quot;chicago_vehicles&quot;</span>,<span class="dt">driver=</span><span class="st">&quot;ESRI Shapefile&quot;</span>)</code></pre>
<pre><code>## Writing layer `chicago_vehicles&#39; to data source `chicago_vehicles&#39; using driver `ESRI Shapefile&#39;
## Writing 77 features with 12 fields and geometry type Multi Polygon.</code></pre>

</div>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Use <code>setwd(directorypath)</code> to specify the working directory.<a href="spatial-data-handling.html#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Use
<code>install.packages(packagename)</code>.<a href="spatial-data-handling.html#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>A good resource on coordinate reference systems is the <a href="http://spatialreference.org">spatialreference.org</a> site, which contains thousands of references in a variety of commonly used formats.<a href="spatial-data-handling.html#fnref3" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="exploratory-data-analysis-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/spatialanalysis/handsonspatialdata/edit/master/01-spatial-data-handling.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
